### ISSUE TITLE
problem whit locale:'it'

### ISSUE THREAD

**Issue by Feedback02** [moment/luxon#1001]
let date = DateTime.fromFormat("18/07/2021", "dd/MM/yyyy",{ locale: "fr" });
console.log(date.toLocaleString(DateTime.DATE_SHORT) );
output: 18/07/2021

and ok, it works. but if i set it as 'it'

 let date = DateTime.fromFormat("18/07/2021", "dd/MM/yyyy",{ locale: "it" });
console.log(date.toLocaleString(DateTime.DATE_SHORT) );
output:18/7/2021

i am doing something wrong?

**Comment by icambron** [comment]
Seems ok... what's the problem?

**Comment by Feedback02** [comment]
there is no 0 in front of the month in 'it' case =>18/7/2021 and it should be 18/07/2021

**Comment by icambron** [comment]
That doesn't seem to be what Intl thinks, though:

```js
new Intl.DateTimeFormat("it", DateTime.DATE_SHORT).format() // => "29/7/2021"
```

So more of an ICU data issue than a Luxon one. Interestingly, if you pass in `{ dateStyle: "short" }`, it does add the zero:

```js
new Intl.DateTimeFormat("it", { dateStyle: "short" } ).format() //=> "29/07/21"

// or in Luxon
date.toLocaleString({ dateStyle: "short" }); // => 18/07/21
```

So that's your workaround. In future versions of Luxon, we're going to replace `DateTime.DATE_SHORT` with the newer `{ dateStyle: "short" }`
