### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by haoweicrushu** [moment/luxon#1022]
**Describe the bug**
Format error

**To Reproduce**
```javascript
// version 1.28.0
const t = '2021-09-01T00:13:50+0800';
DateTime.fromJSDate(new Date(date)).plus({ hours: -8 }).setZone('Asia/Taipei').toFormat("yyyy-MM-dd'T'TT'+0800'");
// Result will be 2021-09-01T24:13:50+0800

// version 2.0.2
const t = '2021-09-01T00:13:50+0800';
DateTime.fromJSDate(new Date(date)).plus({ hours: -8 }).setZone('Asia/Taipei').toFormat("yyyy-MM-dd'T'TT'+0800'");
// Result will be 2021-09-01T00:13:50+0800
```

**Actual vs Expected behavior**
version 2.0.2 result will be ok

**Desktop (please complete the following information):**

- Browser Chrome 92.0.4515.159
- Luxon version 1.28.0
- Your timezone Asia/Taipei

**Additional context**

**Comment by icambron** [comment]
It's the other way around: this was a bug we couldn't fix in 1.x because of the set of browsers we supported, but fixed in 2.x. 24:13 would imply it's the next day...

However, the result you listed is also not what that code does. That code is doubly adjusting the time by both subtracting 8 hours off the local time (which I assume is UTC) _and_ setting the zone to Asia/Taipei...
