### ISSUE TITLE
Utc not converted to localeDateTime

### ISSUE THREAD

**Issue by maxstue** [moment/luxon#1027]
Hi,

I've got a dateTime from the server in ISO-UTC-format and I want to convert it to the locale time, in this case "Europe/Berlin", but it is not adding the offset time to the given utc time.

Time from server is: 2021-09-09T08:30:20.703
than i convert it with the following code 
``` 
    DateTime.fromISO(date, { zone: 'Europe/Berlin' })
      .setLocale('de-DE')
      .toLocaleString({
        day: '2-digit',
        month:  '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute:  '2-digit' ,
        second:  '2-digit'',
      })
```
than I get this time '09.09.2021, 08:30:20' but it should be '09.09.2021, 10:30:20'.
And when I output the time as ISO format with this code `DateTime.fromISO(date).setLocale('de-DE').toISO()` I get '2021-09-09T08:30:20.703+02:00' and that looks fine to me.

Am I doing something wrong here?

**Comment by dasa** [comment]
This seems to work:

```js
DateTime.fromISO('2021-09-09T08:30:20.703', { zone: 'utc' })
      .setLocale('de-DE')
      .setZone('Europe/Berlin')
      .toLocaleString({
        day: '2-digit',
        month:  '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute:  '2-digit',
        second:  '2-digit',
      })
```

**Comment by icambron** [comment]
@maxstue, Luxon doesn't know the string is in UTC because it doesn't say that. For ISO strings with no offset, Luxon uses the system zone by default, but with the `zone` option set, Luxon will use that zone instead. See [here](https://moment.github.io/luxon/#/zones?id=creating-datetimes-in-a-zone) in the docs.

You have two options for workarounds: a) the way @dasa shows it -- parse explicitly in UTC and then convert to your target zone. This seems like a clear expression of what you intended, so it's my suggestion as well. Or b) just add a 'Z' to your input string and keep your code otherwise as-is. That will tell `fromISO` that the time is expressed in UTC, so it will convert to Berlin time, with the result you expect.

**Comment by maxstue** [comment]
@dasa Thank you, that works :)

@icambron Thanks for the explanation, I understood the docs a bit differently. Like when no "Z" is set and i define the zone that it would convert the time to that zone.

**Comment by icambron** [comment]
@maxstue - to convert _to_ a zone, we must have a zone to convert _from_. The issue is what zone to use, since your string doesn't say. So Luxon uses `zone` for that too. So now you're converting from Berlin time to Berlin time, which has no effect. I'll see if I can make that clearer in the docs.

In theory, I could have created two separate options, like `zoneToConvertTo` and `zoneToAssumeTheStringIsExpressedInIfItDoesntSay` and you'd have wanted `Europe/Berlin` for the former and `utc` for the latter. But that's only useful if you have _all_ these conditions: a) there's no offset in the string, b) the string doesn't represent the system zone and is instead in some specific zone that must be specified, and c) it must be converted to a different time zone. Which is your case, but not really very common. Because it's rare and the workaround for that is so straightforward (`DateTime.fromISO(s, { zone: from }).setZone(to)`), I didn't bother creating that decoupling.

**Comment by maxstue** [comment]
@icambron yeah that makes sense, like I said it wasn't 100% clear in the docs because some examples  also have no Zone/Offest from wich to converted from.
After reading your explanation it makes sense writing it like this.

Thanks again for your so fast help :)
