### ISSUE TITLE
Wrong offset for date different from today

### ISSUE THREAD

**Issue by vejess** [moment/luxon#1040]
When I try to convert time (different from now) to local timeZone it gives me different results for different dates. After couple of days I saw that luxon take the offset from the date in the DateTime Object, not current offset of that timezone, and if the date that I want to convert is in summer time, and now is winter time, it gives me wrong offset, and wrong converted time. 

**To Reproduce**
var DateTime = luxon.DateTime;
var convertTimeWinter = DateTime.fromISO("2021-02-01T12:00:00", { zone: "Africa/Accra" }).toLocal().toISO();
console.log(convertTimeWinter );
//2021-02-01T14:00:00.000+02:00
var convertTimeSummer = DateTime.fromISO("2021-08-01T12:00:00", { zone: "Africa/Accra" }).toLocal().toISO();
console.log(convertTimeSummer )
//2021-08-01T15:00:00.000+03:00

**Actual vs Expected behavior**
Offset of the time zone always has to be actual one, not in time, it gives different results, and converting in time zones doesen't work.

**Desktop (please complete the following information):**

- OS:  Windows
- Version 91.0.4472.114
- luxon@2.0.2
-  "Europe/Sofia"

**Comment by icambron** [comment]
This behavior is correct. You're converting the time to Sofia's local time, which has a DST. Accra has a year-round offset of 0, so when you parse the time in that zone, you get 12:00 UTC. That translates to different local Sofia times at different parts of the year. Notice how in both cases that if you subtract the offset off the local Sofia time, you get 12:00, because changing the zone doesn't change the underlying time.

**Comment by icambron** [comment]
On reflection, I suspect you are probably misunderstanding what `toLocal()` does. If you remove it from the chain, do you get the output you expect?
