### ISSUE TITLE
Strange results when endOf and minus methods are used in different order

### ISSUE THREAD

**Issue by geertjansen** [moment/luxon#1045]
**Describe the bug**
I came across a problem, where i seem to be getting different results for a "previous month" time range, based on the order of methods.

**Actual vs Expected behavior**

```js
luxon.DateTime
  .fromISO('2021-09-25T12:00:00Z')
  .setZone('Europe/Amsterdam')
  .minus({months:1})
  .endOf('month')
  .toISO();
```

results in `2021-08-31T23:59:59.999+02:00`, as expected.

In the next example I only switch the order in which `minus` and `endOf` are called.

```js
luxon.DateTime
  .fromISO('2021-09-25T12:00:00Z')
  .setZone('Europe/Amsterdam')
  .endOf('month')
  .minus({months:1})
  .toISO();
```
results in `2021-08-30T23:59:59.999+02:00`, where I would expect the 31th of august.

**Desktop:**

- OS: MacOS
- Browser: MS Edge v 94.0.992.31
- Luxon version 2.0.2
- Timezone "Europe/Amsterdam"

**Comment by geertjansen** [comment]
I think I get the point, still it seems a bit strange that when I'm subtracting a month from the end of a date in oktober (31th) it'll return the 30th of september. That gives me the impression that there is some kind of awareness of month lengths relative to eachother.

**Comment by icambron** [comment]
That's true; there is. The goal of month plus/minus is to keep the day number the same but change the month. But it has to make _some_ choice when that day doesn't exist in the target month, and it does that by using the last day of the month. So subtracting a month of Oct 31 gives you Sept 30 rather than, say, Oct 1. But you're asking for the reverse, that Sep 30 minus a month would give Aug 31 instead of--per the goal above--Aug 30, which would be really weird!

**Comment by geertjansen** [comment]
Ok, thanks for clearing that up.
