### ISSUE TITLE
Comparison Methods?

### ISSUE THREAD

**Issue by lacivert** [moment/luxon#108]
I couldn't find any comparison method like two `DateTime`s, if one is before or after from another.

Momentjs has query functions: http://momentjs.com/docs/#/query/

Will be similar functions in Luxon? 
And what is the best way to compare two DateTime instances for now?

**Comment by woozyking** [comment]
Use natural js comparison operators like `>`, `<=`, etc.

**Comment by icambron** [comment]
Yup @woozyking is right. I'm going to leave this open to figure out where to document those. Probably deserves an entry in the "Math" page of the guide

**Comment by lacivert** [comment]
👍 Thank you very much. I think Math section is good. 

I also think this words would be useful for people who tries 'search' (like Ctrl+F): compare, comparison, after, before

**Comment by icambron** [comment]
Updated the docs in 3918e6b. Will get pushed to the website next time I cut a release.

**Comment by askerkhakh** [comment]
```
+d1 === +d2 // are d1 and d2 the same instant in time?
```
This looks ugly... Like incapsulation violation - knowledge that valueOf returns something useful and unary plus sign for calling it...

**Comment by icambron** [comment]
`valueOf` returning a number that is useful and being involved by the unary `+` is just how JS works. Your complaint is really with JS; Luxon is just following its idioms.

**Comment by gdebunne** [comment]
This is meant as a warning I imagine.

Since `<` and other math comparison operators are available, one may be tempted to use `==` or `===` for equality test. As pointed out, this will usually not work as expected with these immutable objects.

The idiomatic way of testing for equality is probably `d1.equals(d2)`,

or if you are only interested in raw timestamps, `d1.toMillis() === d2.toMillis()`

**Comment by askerkhakh** [comment]
> `valueOf` returning a number that is useful and being involved by the unary `+` is just how JS works. Your complaint is really with JS; Luxon is just following its idioms.

Yep, I don't like the unary plus in general, that's true. I don't like all that silly magic, that JS developers love (double negotiation, boolean "or" in non-boolean context and so on and so forth). Anyway, JS doesn't support operator overloading, so I don't think that using a "hack" with `valueOf` is obvious and expected, otherwise there wouldn't be this issue :wink: 
I wish there were ordinary comparison methods...

**Comment by delcon** [comment]
I recommend outputting and comparing ISO strings (any flavor) like so:
`"2022-04-26T06:00" < "2022-04-26T06:01"`

**Comment by gdebunne** [comment]
Note that lexicographical string comparison of ISO string is broken during one hour every year, due to DST.
Since the offset is after the hour in the string, two ISO strings are wrongly compared after one of the DST changes.

**Comment by titobf** [comment]
Something important to remember when using relational operators in javascript (<, >, <=, >=), is that null is converted to 0.
