### ISSUE TITLE
Get started button does not work second time if I scroll up after clicking it

### ISSUE THREAD

**Issue by PythonCoderAS** [moment/luxon#1096]
**Describe the bug**
If I click the "Get started" button and scroll back up to it, the button stops working.

**To Reproduce**
N/A

**Actual vs Expected behavior**
Expected: Button will work and redo animation
Actual: Nothing happens

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. Chrome 84, safari 14.0] Chrome 96
- Luxon version [e.g. 1.25.0] N/A
- Your timezone [e.g. "America/New_York"] America/New_York

**Additional context**
N/A

**Comment by icambron** [comment]
Thanks for the report, but I don't think there's much we can do about it. The button links to an anchor, and the anchor isn't dropped when you scroll back up. So the browser won't let you navigate to the anchor because it's already the current url.

In theory, the documentation tool that generates the page could use some JS to automatically drop the anchor from the URL when you scroll up, which would make the button work again, but that would need to be changed in the tool.

Honestly I'm considering dropping that hero section altogether; I don't think it provides much value.
