### ISSUE TITLE
Exception on deep frozen duration object when calling toFormat

### ISSUE THREAD

**Issue by shiro** [moment/luxon#1104]
**Describe the bug**
Luxon is advertised as being immutable, which means it's probably supposed to work fine when objects are deep-frozen.  
While working with a third-party library that freezes my object and trying to format the duration string, I got the following:  
`Uncaught TypeError: "fastNumbersCached" is read-only`.

I'm not familiar with the interval workings, but I assume its related to the commit described in #259 and does some modification for the sake of caching, but that means it's mutating the object.

**To Reproduce**
```js
function deepFreeze(object) {
    const propNames = Object.getOwnPropertyNames(object);

    for (const name of propNames) {
        const value = object[name];

        if (value && typeof value === "object") {
            deepFreeze(value);
        }
    }

    return Object.freeze(object);
}

console.log(deepFreeze(Duration.fromMillis(1000)).toFormat("hh"))
```

**Actual vs Expected behavior**
Since Luxon is supposed to be immutable it should work on deep-frozen objects, but doesn't.

**Desktop (please complete the following information):**

- OS: Linux (Arch x64)
- Browser firefox 95.0.2-1
- Luxon version 2.2.0
- Your timezone Japan/Japan

**Comment by icambron** [comment]
No, it being immutable does not mean that. It means it has an immutable _interface_, not that it keeps no internal state. The immutable interface actually _allows_ Luxon to do aggressive internal caching of its computations, since those cached values can't be invalidated by mutations. So for example, if it turns out that a specific DateTime's locale settings allow us to avoid the slow Intl.NumberFormat API and just use standard number tools ("fast numbers") that DateTime can remember that fact forever instead of checking it each time a format method is called on that instance, since any change to its locale settings would create a new instance, not mutate the current one.

Unfortunately, JS doesn't actually hide private fields from your code, or even have a formal way to mark them as such. You're effectively bypassing Luxon's interface and getting at its guts, where it memoizes stuff it needs to.

What Luxon _could_ do is a better job marking private, internally mutable fields, e.g. with leading underscores so that we could better advise reflective tools on how to avoid this kind of thing.
