### ISSUE TITLE
toRelative doesn't work with global timezone

### ISSUE THREAD

**Issue by jereztech** [moment/luxon#1128]
**Describe the bug**
toRelative doesn't work with global timezone

**To Reproduce**
```
Settings.defaultZone = "America/Sao_Paulo";
const isoDate = "2022-01-27T17:53:13.469"; // from backend in UTC
DateTime.fromISO(isoDate).toRelative(); // always use the raw date (isoDate) without defaultZone
```

**Actual vs Expected behavior**
toRelative must work with global timezone

**Desktop:**
- OS: macOS 12.2
- App: React Native 0.64.3
- Luxon version: 2.3.0
- Timezone: America/Sao_Paulo

**Additional context**
I fixed it in my project with the following code, but the ideal is that it works correctly:
```
export const fromNow = (isoString) => {
    let isoDate = DateTime.fromISO(isoString);
    return isoDate.plus({ minutes: isoDate.offset }).toRelative();
}
```

**Comment by icambron** [comment]
No, this is not a bug. The problem is your timezone is _not_ in UTC, because it has no zone information on it. So it Luxon also interprets it using your default zone, essentially cancelling the effect you're looking for. If you want Luxon to know the date from the server is in UTC, you have to tell it that. You can add a "Z" to the string or you can do `DateTime.fromISO(isDate, { zone: "utc" })`

As an aside, note that if your computer is already set to be in Sao Paulo's zone, you don't need to set the default zone at all, and you'll get a performance boost from using the system time zone as the default. You only need to set the default zone if you want Sao Paulo local times for everyone, regardless of what their computers are set to.
