### ISSUE TITLE
For momentjs users: localeData equivalent

### ISSUE THREAD

**Issue by estebanav** [moment/luxon#114]
Hello,

At my project we are trying to moving from momentjs to luxon, but we found out that there is no way to get an equivalent of localeData.

Are you in your plans to make equivalent functionality?

Thanks,

E.

**Comment by icambron** [comment]
There isn't really a direct analog, since Luxon doesn't load data from a locale file. It would be pretty easy to generate something with roughly the same info, but it isn't something that Luxon has just lying around. Additionally, some of the formatting stuff would require some real work to even extract the template into something resembling, say, the `_longDateFormat` key in Moment's `localeData`, because the equivalent of `LTS` and similar are only supported by Luxon's formatting, not parsing (we might fix this, but wouldn't as part of providing `localeData`). Finally, the relativeTime and calendar type stuff isn't in Luxon anyway, so there's no corresponding format strings. So you'd really have something like this:

```
return {
  weekdaysLong: Info.weekdays('long', { locale: loc }),
  weekdaysShort: Info.weekdays('short', { locale: loc })
  // etc for months, eras, and so on
```

Does that suffice for your needs or do you need something else?

**Comment by icambron** [comment]
I'm going to close this out. I'd be happy to reopen if I heard more on why it's needed.

**Comment by GavinThomas1192** [comment]
@icambron I am trying to implement a luxon localizer for react big calendar, since my work wont allow us using moment. 

`return (0, _localizer.set)({
    firstOfWeek: function firstOfWeek(culture) {
      var data = culture ? moment.localeData(culture) : moment.localeData();
      return data ? data.firstDayOfWeek() : 0;
    },
    parse: function parse(value, format, culture) {
      return locale(moment(value, format), culture).toDate();
    },
    format: function format(value, _format, culture) {
      return locale(moment(value), culture).toFormat(_format);
    }
  });
};`

I also need an alternative to localeData...

If successful I think React-big-calendar will do a PR allowing the use of luxon..

**Comment by icambron** [comment]
@GavinThomas1192 Looks like you need the first day of the local week. Unfortunately, I don't know of any way to get that. Moment does this by having locale files for every different place (e.g. it knows specifically that, say USA has its first day as Sunday and so on), but Luxon does all localization through the browser's Intl API. You can see the discussion about supporting this here: https://github.com/tc39/ecma402/issues/6, but as far as I know, that hasn't gone anywhere.

All that stuff is why Luxon only supports ISO weeks, not local weeks.

**Comment by joetidee** [comment]
We are using this function with Moment:

```
/**
 * Returns the index of the first day of a week, adjusted for the set locale.
 * @return {number} - A number relating to the index of the day, (0-6, Sun-Sat).
 */
const getFirstDayOfWeekIndex = () => moment.localeData().firstDayOfWeek();
```

What would be the equivalent using luxon?

**Comment by nycynik** [comment]
That is what was said above; there is no equivalent in luxon.
