### ISSUE TITLE
retrive number of mondays or tuesday etcc between interval or Duration or whatever.

### ISSUE THREAD

**Issue by repka3** [moment/luxon#1161]
Hi everybody,

I know this is prob stupid but after 2 hours on documentation  of luxon (Im using luxon since moment) , I can not for save my life find how to count mondays or tuesday between 2 DateTime, cant find a method cant find a loopable set of dates. I basically want to know between 2 DateTime how mnay monday, tuesday wed etc... to plot a graph on how many hours registered in a year/ how many hours monday etc (for the average hours/day/week). Can u help me ?

**Comment by dasa** [comment]
You could use this to get the day of the week: https://moment.github.io/luxon/api-docs/index.html#datetimeweekday

To loop through you could add a day to the start date until it's after the end day.

**Comment by icambron** [comment]
What @dasa says is probably the best way for long periods, because Luxon's Interval time doesn't have a lazy enumerator, like Twix's [iterate](http://isaaccambron.com/twix.js/docs.html#iterate).

However, if you're not using like thousands of years, you can do this:

```js
const start = DateTime.fromObject({ year: 2012, month: 10, day: 1 });
const end = DateTime.fromObject({ year: 2020, month: 5, day: 6 });

const interval = Interval.fromDateTimes(start, end);
const subIntervals = interval.splitBy({ days: 1 });
const tuesdays = subIntervals.reduce((tuesdays, subInt) => {
  const d = subInt.start;
  return d.weekday == 2 ? tuesdays + 1 : tuesdays;
}, 0);
```

which gave me 397. I haven't checked that 397 is the right number, or done any other testing, so there could be an off-by-one or something in there.

Note that `splitBy` eagerly computes the entire array of day-long intervals, so that's why it's not advisable for huge time periods.
