### ISSUE TITLE
.toJSDate() unexpected output

### ISSUE THREAD

**Issue by CiscoKidxx** [moment/luxon#1170]
I need to change the underlying date using a timezone and have the end result be a JS Date object. The following code gives me what I need however it is really slow when operating on hundreds of thousands of dates (10-15 minutes).

```
  let foo = new Date(
    new Date("2022-01-31T09:00:00.000Z").toLocaleString("en-US", {
      timeZone: "Pacific/Auckland"
    })
  );

// foo = 2022-02-01T04:00:00.000Z
```

I have tried the following to achieve this but the output is 2022-01-31T09:00:00.000Z
```
 let bar = DateTime.fromISO("2022-01-31T09:00:00.000Z")
      .setZone("Pacific/Auckland", { keepLocalTime: true })
      .toJSDate();

// bar = 2022-01-31T09:00:00.000Z
```

Is there a way to achieve the output from the first example using Luxon? The end result has to be a JS Date.

- OS: Windows
- Node
- Luxon version: 1.16.0
- Timezone: "America/Dallas"

**Comment by icambron** [comment]
That's not the result I get, which is:

```
bar = DateTime.fromISO("2022-01-31T09:00:00.000Z")
      .setZone("Pacific/Auckland", { keepLocalTime: true })
      .toJSDate()
bar // => Sun Jan 30 2022 10:00:00 GMT-0500 (Eastern Standard Time)
bar.toISOString() // => '2022-01-30T15:00:00.000Z'
```

Yours will be different because you're in Dallas time an I'm in New York time, but I'm not sure how you got that result. You are on a much older version of Luxon, so perhaps that is the issue?

In any case, that's computing the opposite of what you intend. This is the computation that code does (again, remember I'm in New York time, not Dallas time): 

"when it was 9:00 UTC, it was 4:00 New York time. When it was 4:00 _Auckland time_, it was 10:00 the previous day New York time, which was 15:00 UTC time that same previous day"

But what you seem to want is this:

"when it was 9:00 UTC, it was 22:00 Auckland time. 22:00 _New York time_ is 3am the next day UTC time"

So to get that, you just need to flip the zones around:

```js
bar = DateTime.fromISO("2022-01-31T09:00:00.000Z", { zone: "Pacific/Auckland" })
            .setZone("system", { keepLocalTime: true })
            .toJSDate();

bar //=>  Mon Jan 31 2022 22:00:00 GMT-0500 (Eastern Standard Time)
bar.toISOString() // '2022-02-01T03:00:00.000Z'
```

I'm not sure how much faster that will be. Under the covers, Luxon also formats things out. However, it does do some caching of Intl objects, and that might speed it up. You'll have to see.
