### ISSUE TITLE
[Interval] "overlaps" isn't truly half-open - might want to update docs

### ISSUE THREAD

**Issue by distinctdan** [moment/luxon#1188]
**Describe the bug**
The docs describe intervals as half-open, meaning they include the start point and exclude the end. However, that's not actually true for the `overlaps` method, which doesn't include either endpoint. For my use case, I'm building a calendar, and I've run into an issue with trying to determine if an event ends in a given week. The problem is that if the event ends at 12:00am, its end is greater than the current week, but then it's not included in the next week's interval:

```
// For the current week
eventOverlapsCurrentWeek: true
eventEndsInCurrentWeek: false // event end is greater than week end
[Sun 12:00am ------------- Week Interval ------------ Sat 11:59pm]
                     [Tue 12:00am ----- My Event ----- Sun 12:00am]

// For the next week - Doesn't include event.
eventOverlapsCurrentWeek: false
           [Sun 12:00am ------------ Week Interval ------------- Sat 11:59pm]
Sun 12:00am]
```

I get why `overlaps` works the way it does, and I agree it generally does what people expect. However, I would propose that we update the docs to clarify that it works slightly differently than the overview explains by not including the endpoints.

An alternative could be to add an `overlapsHalfOpen` method, which would include one of the endpoints, which is what I've ended up doing for my calendar. However, it has the following disadvantages:
 - Adds complexity to the API. It's not immediately obvious why someone would need this.
 - Order matters: `a.overlapsHalfOpen(b) !== b.overlapsHalfOpen(a)`

**Comment by icambron** [comment]
I don't think I follow -- you have `interval1 `that ends Sunday at 12am, and `interval2` that begins Sunday at 12am. Per half-openness, `interval1` doesn't include its end (meaning 12am sharp), so the last full millisecond included is Saturday 11:59:59.999pm and `interval2` doesn't start until 12am, so there's no overlap.

Can you elaborate on what you're looking for?

**Comment by distinctdan** [comment]
Sure thing, so for my first week interval, it actually ends at 11:59pm Saturday instead of 12:00am Sunday. I'm using `startOf('week')` and `endOf('week')` to generate the week intervals. 

In my particular case, I'm trying to determine if the event ends in the first week. Since my event ends at 12:00am Sunday, it doesn't fall within the 1st week. However, it's not included in the second week because the 2nd week interval doesn't include 12:00am Sunday.

It may be simpler to think about an event thats instantaneous and starts and ends at 12:00am Sunday. For my calendar, it wouldn't be included in either week if I use `week.overlaps(event)`

**Comment by icambron** [comment]
> It may be simpler to think about an event thats instantaneous and starts and ends at 12:00am Sunday. For my calendar, it wouldn't be included in either week if I use week.overlaps(event)

The reasoning for this is just that an interval that's 0 milliseconds long doesn't "overlap" with anything-- overlap meaning, loosely, that there's some amount of time that goes by in both intervals simultaneously. I'll concede that intervals don't do a great job reducing to instantaneous time slices, but this is really a property of half-open intervals generally: if the start and end are the same, then it's a bit weird to ask if it's that moment is in the interval or not, so half-open intervals of zero-length are generally considered empty, not as containing that one instantaneous slice. Set theory defines them the same way, fwiw.

> it actually ends at 11:59pm Saturday instead of 12:00am Sunday. I'm using startOf('week') and endOf('week') to generate the week intervals.

As a bit of an aside, note this means there really is a millisecond in neither week interval, the one between 11:59:59:59.999 and 12. It's not in the first one because it's half-open and thus doesn't include the end, and not in the second because that hasn't started yet. There's a bit of an impedance mismatch in Luxon between `endOf` on DateTimes and the half-openess of intervals, which IMO is a minor but annoying design flaw.

I don't think I'm 100% sure on exactly what comparison is failing your expectations here, but to go a little deeper on what I suspect is the core issue, half-openess is _why_ we always compare `end > start` instead of `>=`; the end isn't in the interval, so it has to be greater than the start to generate an overlap. If we considered it an overlap when firstOne.end == secondOne.start, then that would be fully open.

Your alternative is easy enough to implement. The full definition of `overlaps` is:

```js
  overlaps(other) {
    return this.e > other.s && this.s < other.e;
  }
```

but to me changing that to use >= on one side is _breaking_ half-openness, not fixing it. Of course, none of that makes it an unreasonable thing to need or want, if that's what your use case works out to need. So putting naming and semantics aside, and just considering if it's a useful addition, these are well-spotted:

> * Adds complexity to the API. It's not immediately obvious why someone would need this.
> * Order matters: a.overlapsHalfOpen(b) !== b.overlapsHalfOpen(a)

So taken together, I think that all means we won't add it, though of course it's easy to add in userspace.

**Comment by distinctdan** [comment]
Hmm, I think I see what you're saying. So the real issue is that my intervals aren't truly touching, since the end of my first week is 1 millisecond off from the start of week 2. Since intervals are defined as half open, the week really ought to go to 12:00am Sunday, since 12:00am isn't included in the interval.

Ok, I see what's going on, thanks for the explanation. At this point, we couldn't change the API or it would break people's stuff, and it probably still makes more sense for `startOf` and `endOf` to return times the way they do. For example, if we changed `endOf` to return 12:00am instead of 11:59:59, it would be on a different day, which would probably be unexpected.

Yeah, so I think I'm good from here. I don't know how common my use case is, using `startOf` and `endOf` to generate intervals, then checking them with `overlaps`, but maybe something to keep in mind for the docs. Thanks for the explanations, I'm going to go ahead and close this.
