### ISSUE TITLE
DateTime.toUTC isn't adding / subtracting the offset?

### ISSUE THREAD

**Issue by Wizzel1** [moment/luxon#1193]
**Is your feature request related to a problem? Please describe.**
I am trying to convert JSDates to UTC. For example : 

```ts
const myJSDate = new Date();
const myUTCDateTime = DateTime.fromJSDate(myJSDate).toUTC();
```

I was expecting the `toUTC` method to take care of adding/subtracting the offset and was surprised that the default offset is 0.

**Describe alternatives you've considered**
I am now doing this manually : 

```ts
const myJSDate = new Date();
const myDateTime = DateTime.fromJSDate(myJSDate);
const myUTCDateTime = myDateTime.plus({ minutes: myDateTime.offset });
```

Not sure if this is correct or if I am confusing something here but maybe the default offset should be the offset of the JSDate to UTC.

**Comment by icambron** [comment]
Changing the zone doesn't change the underlying time. From the docs:

> It's important to remember that a DateTime represents a specific instant in time and that instant has an unambiguous meaning independent of what time zone you're in; the zone is really a piece of social metadata that affects how humans interact with the time, rather than a fact about the passing of time itself. Of course, Luxon is a library for humans, so that social metadata affects Luxon's behavior too. It just doesn't change _what time it is_.


```js
let myJSDate = new Date();
myJSDate.toString() // => 'Sun May 01 2022 13:09:17 GMT-0400 (Eastern Daylight Time)'

let myDateTime = DateTime.fromJSDate(myJSDate)
myDateTime.hour //=> 13
myDateTime.offset //=> -240

let myUTCDateTime = myDateTime.toUTC()
myUTCDateTime.hour //=> 17 (it's 4 hours later in UTC time)
myUTCDateTime.offset //=> 0

myUTCDateTime.valueOf() == myDateTime.valueOf() //=> true, same underlying time
```

If you are expecting `myJSDateTime.toJSDate()` to return a JS date that is different than the one you started with, then you are misunderstanding "convert". Converting time zones changes the metadata about how the local time is represented; it doesn't change the underlying time. In particular, your workaround produces a different time; a time that represents a different moment in the history of earth. That's not "converting to UTC" that's "change the date so that its local time is the same as my original date's UTC time".

JS dates don't have zones; they represent the date as an epoch timestamp and they have methods for returning times in the runtime's zone. So converting back to a JS date effectively strips the time zone metadata back out. The time will be the same because we never changed the time.

You can make Luxon shift the time if you want:

```js
const myShiftedToUTCTime = myDateTime.setZone({ zone: "utc", keepLocalTime: true });
```

That will do what you're expecting, and is covered by the docs here: https://moment.github.io/luxon/#/zones?id=keeplocaltime

There are certainly cases where this is necessary, usually in tricking some third-party zone-unaware code into operating on JS dates as if they were in some other zone (in this case UTC). But I urge caution here; you have changed the underlying time, and that might have consequences to your application logic that you're not fully anticipating. And if you don't have a use case that looks like that, it's likely that you've misformulated the problem you're solving.

Teleporting to a different time zone might change how the clocks represent the time, but it wasn't time travel.

**Comment by Wizzel1** [comment]
Wow, thanks for the detailed and quick reply. I guess I had a fundamentally wrong understanding of how time works in programming. 

I use luxon for cloud functions and I want to have a "base" time to work with throughout the backend without having to worry about a time zone. So far this has worked quite well, mainly because I only need the date (time doesn't matter in my app, in fact I currently set it manually to 0 once I have the UTC time of a date). 

The reason I used the code above was because I use the date-fns package to get the first day of a week:
[startOfWeek](https://date-fns.org/v2.28.0/docs/startOfWeek.) 

But this method returns a value with timezone, for example : 

`startOfWeek(today, { weekStartsOn: 1 }) => // 04/24/2022 23:00:00 GMT+1`

This leads to problems, because I set the hours to 0, and now I have a whole day more in this week (monday the 25th would be start of week in this case)

**Comment by icambron** [comment]
Right, `startOfWeek` in date-fns doesn't know what zone you mean, so you have to sort of trick it by changing the time instead the zone. Which works, but be careful about not using that JS date for anything else.

Can I suggest using Luxon's start of week?

```js
const dateTime = DateTime.fromJSDate(new Date()).toUTC().startOf("week")
dateTime.toJSDate().toISOString() //=> '2022-04-25T00:00:00.000Z'
```

`startOf("week")` is zone-aware in Luxon, because when the week starts is a social fact that happens at a different absolute time in each zone. So you change the zone, _then_ ask it for the start of the week, _then_ convert it back to a JS date, and presto, you have the date you want without any shenanigans. You are fundamentally asking a zone-sensitive question, so Luxon is better tool for this. You'll avoid a lot of subtle bugs, especially with DSTs, by doing zone-sensitive operations with zone-sensitive tools.
