### ISSUE TITLE
Adding 5 years doesn't result in 5 years diff

### ISSUE THREAD

**Issue by Maxim-Mazurok** [moment/luxon#1205]
**Describe the bug**
I'm writing a test for my code to calculate annualized return, where I use `const totalYears = endingDate.diff(beginningDate).as("years");`
And I want to specify such `beginningDate` and `endingDate` so that `totalYears` will be exactly `5`.
I'm doing it like this:
```ts
const beginningDate = DateTime.fromMillis(0);
const endingDate = beginningDate.plus({ years: 5 });
```
But that doesn't result in a 5-year diff, it's slightly less.

**To Reproduce**
https://runkit.com/embed/oa645v1uf4yy
```ts
const { DateTime } = require("luxon");

const beginningDate = DateTime.fromMillis(0);
const endingDate = beginningDate.plus({ years: 5 });

const totalYearsCasual = endingDate
  .diff(beginningDate, undefined, { conversionAccuracy: "casual" })
  .as("years");

const totalYearsLongterm = endingDate
  .diff(beginningDate, undefined, { conversionAccuracy: "longterm" })
  .as("years");

console.log({ totalYearsCasual, totalYearsLongterm });
```

**Actual vs Expected behavior**
Actually I'm getting this: `{totalYearsCasual: 5.002625570776256, totalYearsLongterm: 4.999304115302391}`

I expect to get this: `{totalYearsCasual: 5, totalYearsLongterm: 5}` (or at least one of them to be 5).

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Chrome 101 or NodeJS 17
- Luxon version 2.4.0
- Your timezone Australia/Sydney

**Comment by icambron** [comment]
Right, in your original you did the diff in milliseconds and then converted to years. The milliseconds is the actual amount of time, so nothing to do with calendars, and then you asked Luxon how many years that number of millis coverts to. That conversion can't account for DSTs or whatever specific leap years occurred in those five years, because it doesn't know what five years they were; it's now just a pile of milliseconds. Converting using longterm accuracy means that leap years are handled *on average* but in five years you'd have either one (less than average) or two (more than average). And if you end on a different offset than you started because the DST rules changed in the interim, there's also no way the conversion can know that.

Taking the diff in years actually does the math using the calendar, same as adding the years. So March 12,2022 is 5 years before March 12, 2027, whatever happens in between.

See the Math doc for more on losing information and calendar vs time math.
