### ISSUE TITLE
Offset and offset name inconsistencies caused by `Date.prototype.getTimezoneOffset()`

### ISSUE THREAD

**Issue by tbaliukynas** [moment/luxon#1212]
**Describe the bug**
When working with a historic time zone that has an offset containing minutes and seconds, Luxon provides incorrect offset/offset name in Chromium-based browsers or Node.js environments (really anything that uses V8 JavaScript engine).

For example, `DateTime.fromISO('1900-06-01T12:00:00Z').toString()` returns `1900-06-01T14:02:00.000+02:02` when run with `Settings.defaultZone.name  === 'Europe/Kiev'` but the `offsetNameLong` says that the offset is `GMT+02:02:04`.

This is most likely related to V8's implementation of `Date.prototype.getTimezoneOffset()` where the offset is always returned as a whole number instead of a decimal one (https://github.com/nodejs/node/issues/33306). However, I think that the offset value and the offset name should not contradict each other.

**To Reproduce**
A minimal code example that demonstrates the problem when executed in Chrome:
```ts
const tz = Settings.defaultZone.name;  // Europe/Kiev
const date = '1900-06-01T12:00:00Z';

DateTime.fromISO(date).toString();     // 1900-06-01T14:02:00.000+02:02
DateTime.fromISO(date).offsetNameLong; // GMT+02:02:04
DateTime.fromISO(date).offset;         // 122

DateTime.fromISO(date).setZone(tz).toString();     // 1900-06-01T14:02:04.000+02:02
DateTime.fromISO(date).setZone(tz).offsetNameLong; // GMT+02:02:04
DateTime.fromISO(date).setZone(tz).offset;         // 122.06666666666666
```

**Actual vs Expected behavior**
The offset value should contain a fractional part right from the beginning (without explicitly calling `setZone()` with the default time zone name). This is how it works in Firefox at the moment:
```ts
DateTime.fromISO('1900-06-01T12:00:00Z').toString();     // 1900-06-01T14:02:04.000+02:02
DateTime.fromISO('1900-06-01T12:00:00Z').offsetNameLong; // GMT+02:02:04
DateTime.fromISO('1900-06-01T12:00:00Z').offset;         // 122.06666666666666
```

**Desktop**

- OS: Windows 10, version 21H2
- Browser: Mozilla Firefox 100, Microsoft Edge 101
- Luxon version: 2.4.0
- Your timezone: [Europe/Vilnius](https://en.wikipedia.org/wiki/Time_in_Lithuania) (UTC offset: +02:00; DST: +03:00)

**Comment by icambron** [comment]
Are you sure your computer is set to Europe/Vilnius and not Europe/Kiev? As in, are you getting Europe/Kiev for `Settings.default.name` because you set the computer to that as opposed to having done `Settings.defaultZone = "Europe/Kiev"? I'm going to assume it's the computer setting and that, for our purposes, your zone is really Europe/Kiev, because I can't make sense of the results otherwise. So...

Your default zone is the system zone, which happens to be Europe/Kiev. It's _called_ "Europe/Kiev" but it's really `system`, i.e. the browser's native zone. To Luxon very different from an IANA zone with that same name. The way Luxon works is that:

* if the zone is an explicit IANA zone, use the Intl API to compute the offset. This gives accurate results
* if the the zone is the system zone, then use `getTimezoneOffset()`. And like you said, in Chromium this doesn't provide decimals there. I'd love it if they did

That's why `setZone("Europe/Kiev")` or even `Settings.defaultZone = "Europe/Kiev"` changes the result; they're telling Luxon to use a particular object as the zone instead of the system zone that just happens to be Kiev.

So how could Luxon fix that? Well, we could _always_ use the zone's IANA name even for the system zone, then plug that explicitly into the offset calculator and be confident that we will get the right result.  Basically the same `setZone()` call you did, but inside of `offset`. The problem with this is that it would be much slower. `getTimezoneOffset` is close to free, whereas using the Intl API is much slower. That means we'd be degrading performance for everyone whether they have fractional minute offsets or not. So we're not going to do that.

In this case, we could in theory parse the offsetNameLong and observe it has `:04` on the end. But to Luxon that string is opaque; for example it could just as easily say "Standard Ukrainian Time".  Luxon attaches no semantics to it, so it doesn't really make sense to use as anything other than a display property. I don't think we can reasonably change that either. Using it would only work on a minority of historical zones, its behavior would depend on the locale, etc. I don't think we're going to code that into Luxon.

So the net is:

* we can't (reasonably) fix this in Luxon. It needs to be fixed in V8
* The workaround is simple. Before you do anything, do this: `Settings.defaultZone = Settings.defaultZone.name`. That seems silly, but it does the trick: Luxon will use the explicit IANA zone as the default zone instead of the implicit system zone that just happens to have the same name.
* If you want a fancier workaround that preserves good performance where possible, then you can check that a) it's chromium and b) the offset name looks like X, and if so call `setZone(Settings.defaultZone.name)` on it.

If your answer to my question at the top is "no, my browser is really in Europe/Vilnious when I ran this test", then I'm very confused. If that's the case, tell me and I'll reopen this.
