### ISSUE TITLE
Possible to add something like `isOffsetPresentlyFixed`?

### ISSUE THREAD

**Issue by jbg** [moment/luxon#1215]
**Is your feature request related to a problem? Please describe.**

I need to handle the case that a time zone *currently has* DST rules specially in a UI, in the context of timestamps strictly greater than the current moment in time.

`isOffsetFixed` would seem appropriate for this, but it returns `true` for many time zones that do not currently have DST. As far as I can see, it returns `true` if a zone has ever had DST rules, which is reasonable because you may be handling historical timestamps, but makes it unsuitable for our case.

**Describe the solution you'd like**

An additional property that indicates whether DST rules exist for the zone for current or future timestamps. (In other words, according to the current rules of the zone, DST is presently in force or will be in force at some future time).

Effectively `isOffsetFixed` but ignoring rules that no longer apply.

**Describe alternatives you've considered**

I have had a look at the `Zone` object but can't see this information exposed there.

**Comment by icambron** [comment]
This isn't quite possible. Luxon doesn't know when the DSTs are (there's no API for that); it can only compute the offset for a given date. `isOffsetFixed` only checks if the zone _could_ have a DST, which from Luxon's perspective is any IANA zone, even ones that have never had a DST. I regret exposing that method because it's confusing.

So we can't know if there is a future DST without checking a list of future dates. It's instructive to look at `isInDST`, whose implementation is this:

```JS
get isInDST() {
    if (this.isOffsetFixed) {
      return false;
    } else {
      return (
        this.offset > this.set({ month: 1, day: 1 }).offset ||
        this.offset > this.set({ month: 5 }).offset
      );
    }
  }
```

You could imagine a very similar check that detects whether the year has a DST at all, by checking, say, Jan 1 and July 1 and seeing if they have different offsets. This may fit your needs.

However, I don't want to add that to Luxon, because I already regret `isInDST`; those date choices are iffy and I don't like the Luxon API making promises it might not be able to deliver on. Some zone could have some strange rules that aren't detected, or non-DST changes could create false positives (e.g. a zone permanently changing its offset). Luxon shouldn't do heuristics.

So my recommendation is to write that code in your own code base, and recognize it probably won't be perfect.

**Comment by jbg** [comment]
Thank you for the explanation, it makes good sense. I'll close this now, perhaps one day the Web API will expose more of the TZDB. In the meantime I think the least-bad approach for our case is probably to bundle the TZDB and check that.
