### ISSUE TITLE
Suggestion: Interval `isAfter{Start,End}` and `isBefore{Start,End}` methods

### ISSUE THREAD

**Issue by OliverJAsh** [moment/luxon#123]
Currently the `Interval` type provides two methods:

- `isBefore` to check if the Interval end (plus 1—not sure why this is?) is before a given `DateTime`
- `isAfter` to check if the Interval start is after a given `DateTime`

It might be useful to provide further helpers in the form of `isAfter{Start,End}` and `isBefore{Start,End}`. This would also make the API more explicit. I keep forgetting which helpers refer to the start and end of the interval.

What do you think?

**Comment by OliverJAsh** [comment]
In fact, the existing helpers tell you if the interval is before/after a given date time, not the other way round as I expected. In hindsight I don't think my suggestion makes sense. Ignore my nonsense :-)

**Comment by icambron** [comment]
The plus 1 is a little weird but from supporting Twix, it confused people to if the half-open interval considered itself "before" its not-included endpoint. That said, I'm not sure I completely agree with the current behavior.

Yeah, read it in the order it appears in the code: "this `Interval` `isBefore` `some time`". If I were to change that to make it more clear, I'd move it to a static method in Info like `isBefore(Interval|DateTime, Interval|DateTime)` or similar.

Finally, remember that it's easy to use the endpoints as DateTimes and they're easy to compare because they support `valueOf`, e.g. `someInterval.start < someDateTime`

**Comment by damianobarbati** [comment]
+1 for this: would you consider adding isBefore/isAfter and isSameOrBefore/isSameOrAfter like we had in moment? Currently fallbacking to `.diff`.
