### ISSUE TITLE
Question: If zone is undefined shouldn't it throw an error? DateTime.fromObject.toFormat

### ISSUE THREAD

**Issue by xmariopereira** [moment/luxon#1248]
I built a small function to return the offset based on a zone. I am using DateTime.fromObject.toFormat.

And I noticed if the zone value is undefined, it uses the local zone as default. 

If I add opt with key 'zone', but the value is undefined, why is it not throwing an error or a warning?

**To Reproduce**

```

const { DateTime } = require("luxon");

function getDateTimeOffSet(localTimeZoneName) {
  return DateTime.fromObject(new Date(), { zone: localTimeZoneName }).toFormat('ZZ');
}

exports.getDateTimeOffSet = getDateTimeOffSet; 

```

Note: localTimeZoneName value needs to be undefined.

***Actual vs Expected behavior***

Actual behavior: returns 00:00. VM local zone is UTC.

Expected behavior: Error? Undefined Zone?

***Package info***
- Linux
- luxon: 3.0.1

**Comment by icambron** [comment]
No, we really shouldn't. In JS, undefined just means it's not provided. So both `{}` and `{ zone: undefined }` have an undefined zone (try it: `{}.zone`) .  And since `zone` isn't required by `fromObject()`, it's totally fine for it to be undefined.

There are some ways to differentiate the case of "we didn't provide zone at all" and "we provided the key but the value was undefined" by using `Object.keys()` but this is swimming against the current of how JS works. In fact, it would be pretty unfortunate if we did that; it should be programmatically possible to simply not provide the zone option by setting it to `undefined`, and it would be awkward in many situations in which the options are built programmatically if we had to explicitly remove the key if we didn't want to set the zone.

In fact, your code snippet is a great example! How would you provide not-a-zone and get the behavior you got?
