### ISSUE TITLE
Inconsistent fromISO setZone behavior with UTC/00:00

### ISSUE THREAD

**Issue by fgblomqvist** [moment/luxon#1295]
**Describe the bug**
When using `fromISO` and passing `setZone: true` on a system with UTC timezone, you get inconsistent outcomes in terms of whether the resulting DT has the TZ offset as UTC or 00:00.

**To Reproduce**
```ts
process.env.TZ = "utc"

const dt = DateTime.fromISO("2022-10-03T14:41:38.100Z", { setZone: true });
console.log(dt.toISO()); // 2022-10-03T14:41:38.100Z

const dt2 = DateTime.fromISO("2022-10-03T14:41:38.100+00:00", { setZone: true });
console.log(dt2.toISO()); // 2022-10-03T14:41:38.100Z

const dt3 = DateTime.fromISO("2022-10-03T14:41:38.100", { setZone: true });
console.log(dt3.toISO()); // 2022-10-03T14:41:38.100+00:00
```

**Actual vs Expected behavior**
`dt` makes sense, it retains the UTC timezone that was specified. `dt2` should be retained as `00:00` since it is specified as such. Finally, I would expect `dt3` to be `Z` since the timezone of the system is explicitly UTC, not a `00:00` one.

**Desktop (please complete the following information):**

- OS: macOS
- Node 16
- Luxon version: 3.0.4
- Your timezone: Europe/Amsterdam

**Additional context**
Might be related to https://github.com/moment/luxon/issues/992 and https://github.com/moment/luxon/issues/638.

**Comment by icambron** [comment]
For `dt2`, this is correct. `setZone` means that Luxon is setting the zone on DateTime to whatever is implied by the string. An offset of 00:00 in an ISO string doesn't imply that the time is in a particular zone, but you are explicitly telling Luxon to set the zone anyway., and the best it can do is use the fixed-offset one. It can't set the zone to "some zone with a current offset of 0 but I don't know which one", even if that's what the string says. From the docs:

> Note that if only an offset is provided by the string, the zone will be a fixed-offset one, since Luxon doesn't know which zone is meant, even if you do.

The fixed-offset zone with an offset of 0 is UTC, hence the Z.

One way to better understand this is to put aside `toISO()` for a moment. Each of your dt instances has a `zone` property, which is an object representing the time zone. That zone is used in computations and formatting. What object do you expect to be at `dt2.zone`? It has to be something.

```
> dt2.zone                                                                                                                                                                          
FixedOffsetZone { fixed: 0 }   
```

It's a fixed-offset zone with an offset of 0, which is precisely UTC. Then the `zone` property is used to determine how the offset is rendered in `toISO()`

`dt3` is exactly #992, which you linked to (saved me from looking it up, so thank you!). Note that the `setZone` does nothing here, since the string doesn't specify any offset or zone information. We take the zone from the system:

```
> dt3.zone                                                                                                                                                                          
SystemZone {}
```

That system zone is indeed equivalent to UTC, but Luxon doesn't know that. My position on it remains the same: I acknowledge it's an issue, but I don't think it's practical to fix. I could be convinced on this.

**Comment by fgblomqvist** [comment]
I understand your point. As someone who has not spent probably hundreds of hours digging into DT/TZ stuff in JS, my hunch is just "why don't you just get the time zone name instead of the offset" and check if it's UTC, but I'm guessing it's perhaps more complicated than `Intl.DateTimeFormat().resolvedOptions().timeZone`? 😅

**Comment by fgblomqvist** [comment]
It's not so much of a problem as a nuisance. E.g. if you leave out the timezone of the string I'd want the zone to get set to UTC if that's what the server is operating on (using Node in my case). Too bad the performance isn't good enough with the Intl API, but setting `Settings.defaultZone` ain't a bad option tbh, will keep it in mind.

**Comment by icambron** [comment]
In fact, if you're strictly in Node, all you need to do is:

```js
if (process.env.TZ == "utc") {
   Settings.defaultZone = "utc"
}
```

Note there's no real perf hit here because computing offsets for UTC doesn't require the Intl APIs (it was only _finding out_ the system zone that was a pain). 

I'm going to go ahead and close this.
