### ISSUE TITLE
Feature request : add weekday in hasSame query

### ISSUE THREAD

**Issue by vjau** [moment/luxon#1321]
AFAIK, `hasSame` query function doesn't support `weekday` as a unit.

It would probably be a nice thing to have. 

Thank you.

**Comment by diesieben07** [comment]
That is not how `hasSame` works. `hasSame` checks the queried unit, but also all higher order units. What are the "higher order units" of "weekday" (which isn't a unit)?

Do you want this to behave like `a.weekday === b.weekday` or like `a.hasSame(b, 'day')` (would assume the "higher order units" are week, month, quarter and year)? In either case, why not do that instead as it would be more clear instead of overloading `hasSame` with this very different funtionality?

**Comment by vjau** [comment]
I didn't get the "higher order" part. 
You mean that if i do `DateTime.now().hasSame(otherDT, 'day'); //~> true if otherDT is in the same current calendar day`
like in the doc, it will be in fact `//true if otherDT is in the same current calendar day, month and year` ?
Perhaps the doc could be modified this way ?

**Comment by diesieben07** [comment]
`a.hasSame(b, 'day')` checks that `a` has the same day, month, quarter and year as `b`, that's what I mean by "higher order units". So `DateTime.fromISO('2022-10-10').hasSame(DateTime.fromISO('2021-10-10'), 'day')` is `false`, because the year is different.
