### ISSUE TITLE
Subtracting 1 year from leap year (date 2024-02-29T00:00:00.000Z)

### ISSUE THREAD

**Issue by damianof** [moment/luxon#1322]
**Describe the bug**
Unexpected behavior of luxon add when subtracting 1 year from February 29th of a leap year.
Subtracting 1 year from 2024-02-29 returns 2024-02-28 (instead of 2024-03-01).
Subtracting 1 year from 2024-02-28 also returns 2024-02-28 (which I believe is correct in this case).

**To Reproduce**
Code to reproduce issue here:
https://gist.github.com/damianof/bc8dba42e283f195aef4cf851a63a8bb

**Actual vs Expected behavior**
- actual 2023-02-28
- expected  2023-03-01

**Desktop (please complete the following information):**
- Happens in both Node.js and Chrome Browser

**Comment by diesieben07** [comment]
I think this is expected behavior.
From the [docs on calendar math](https://moment.github.io/luxon/#/math?id=how-to-think-about-calendar-math):
> It's best not to think of calendar math as requiring arcane checks on the lengths of intervening periods. Instead, think of them as **adjusting that unit directly and keeping lower order date components constant.**

"That unit" is "years" here, so lower order units (the month and day) should remain constant. This is possible for the month, but the day has to be adjusted, because of leap years.

**Comment by icambron** [comment]
@diesieben07 is correct -- this is expected. Luxon wants to make it Feb 29, but it can't and so it settles for Feb 28. If you want to add 365 days, you can do that explicitly
