### ISSUE TITLE
FromFormat("yy") resolve 59 as 2059 oppose to 1959.

### ISSUE THREAD

**Issue by hxtree** [moment/luxon#1329]
**Describe the bug**

It was expected that "YY" would to resolve to past date for "59" but resolves to future date:

**To Reproduce**

```
DateTime.fromFormat('1/17/59', 'M/d/yy")

datetime.toFormat('yyyy-MM-dd');
```

**Actual vs Expected behavior**
Actual resolved to 2059-01-17.
Expect to resolves 1959-01-17. 

**Desktop (please complete the following information):**

- OS: Linux / NodeJS 16
- Luxon version : "3.0.4"

(Microsoft Excel does differently)

**Comment by dobon** [comment]
This is (very frustratingly) the API working as intended. Take a look at
the entry for "yy" in the table of tokens:
https://moment.github.io/luxon/#/parsing?id=table-of-tokens

"two-digit year, interpreted as > 1960 (also accepts 4)"

Well they had to draw the line somewhere, right? D'oh!

**Comment by dobon** [comment]
If you dig through the code, this is the current implementation that is causing the problem for you: 
(`year` is the 2-4 digit number parsed from the "yy" part of the regex)
https://github.com/moment/luxon/blob/ee02e9913c082221e0357c3fc43fcd1cd48e4a57/src/impl/util.js#L185-L189

So as you can see, it would be trivial to change it to any other cut-off date, but the implementation was authored such that the arbitrary "which century?" line is at 60. If you are using this for interpreting date of birth, then you'll need to implement some code to counteract the 'untruncateYear' method's opinion.

Here's an un-untruncateYear method that moves the cut-off line to 'the current year' instead of 1960:
(`dt` is the `luxon.DateTime` that is returned from executing `luxon.DateTime.fromFormat('1/17/59', 'M/d/yy')`)
```
function fixLuxonUntruncateYear(dt) {
  if (luxon.DateTime.now().year < dt.year) {
    dt = dt.minus({years: 100});
  }
  return dt;
}
```

**Comment by icambron** [comment]
Yeah, unfortunately, there's just no good answer to this. It's an ambiguous value and puts Luxon in the uncomfortable position of having to make a decision.

If someone writes a PR that creates `Settings.twoDigitCutoffYear`, I'd accept it

**Comment by dobon** [comment]
I came to the same conclusion, am currently writing such a PR and would appreciate your review when it is ready. :)

**Comment by dobon** [comment]
@icambron PR ready for review https://github.com/moment/luxon/pull/1330

**Comment by icambron** [comment]
I'll cut a new release soon

**Comment by dobon** [comment]
Definitely run the tests too, if you haven't already. I wrote this PR in the online GitHub Visual Studio Code thing, which I am very unfamiliar with, and didn't actually confirm my tests (or, uh, code) work because I couldn't figure out how to configure it properly.

**Comment by dobon** [comment]
Hah, I see that tests are automatically run on merge to master and they revealed that I forgot an import 'Settings' on the tests... Patch incoming.
