### ISSUE TITLE
DateTime.local() behavior differs when undefined is passed vs null

### ISSUE THREAD

**Issue by Gkleinereva** [moment/luxon#1351]
**Describe the bug**
`DateTime.local(undefined)` behaves the same way as `DateTime.local()`.  This behavior makes sense to me.  However, `DateTime.local(null)` throws a type error.  It seems to me that this should duplicate the behavior of passing undefined, or at the very least omit the error and simply produce an invalid DateTime.

Alternatively, I think this behavior should be documented.

**To Reproduce**
```javascript
import { DateTime } from 'luxon';

const validDate = DateTime.local(undefined);

const throwsTypeError = DateTime.local(null);
```

**Actual vs Expected behavior**
I wouldn't expect calling the function with `null` to throw a type error.  I think it should either behave the same way as calling it with `undefined`, or return an invalid DateTime.

**Desktop (please complete the following information):**

- OS: Windows and Ubuntu (in my case, WSL2)
- Browser: Edge 108.0.1462.46
- Luxon version: 3.1.1
- Your timezone: America/Los_Angeles

**Additional context**
Thank you so much for your hard work, this library is one of my favorites  :D

**Comment by icambron** [comment]
No, this is correct behavior, because `DateTime.loca()` accepts a variable number of arguments. In general, passing `undefined` is the same as not passing anything at all, so `DateTime.local()` and `DateTime.local(undefined)` are the same. This is an important distinction between `null` and `undefined`: null is the value of absence and undefined is the absence of a value. Try this out in your dev console:

```js
function foo(bar) {
   console.log(typeof bar == "undefined")
}

foo()
foo(undefined)
foo(null)
```

You'll see that from inside the function, `bar()` and `bar(undefined)` are identical. Luxon does not know whether you called `DateTime.local()` or `DateTime.locale(undefined)`.

In theory, Luxon could work around this by checking the length of the `arguments` magic variable, but this is a not a good idea. To begin with, it means you can't programmatically pass the absence of an argument to use the lower arities. Consider computing the argument for `DateTime.local()` and having that computation decide you want to invoke the no-args version of it. That would be a hassle if Luxon did weird stuff about undefined. Secondly, it adds a bunch of ugly boilerplate code to every variadic function. More importantly, it just goes against the design of the language, which is the real source of those first two issues. Perhaps `undefined` was a poor design choice on the part of JS, but it's there and general-purpose libraries need to impedance match with it.

**Comment by Gkleinereva** [comment]
Thanks for your feedback, @icambron!

In reading your response, I understand why calling `DateTime.local()` is the same as calling `DateTime.local(undefined)`.  I agree that this behavior makes sense.

I'm curious, however, why calling `DateTime.local(null)` resulting in a type error is desired behavior.  If you have a chance, could you clarify this point?  Thanks!

**Comment by icambron** [comment]
Unlike `undefined`, `null` is an actual value, of type `null`. Luxon doesn't really use null arguments, but in general they can be valid arguments. `you.setBoss(null)` means "you don't have a boss". If you provide a null argument to Luxon, you are saying "I _am_ supplying this parameter, but its value is null" to which Luxon should say, "that parameter isn't allowed to be null".

The proper analogy of this to `undefined` is if `DateTime.local()` required an argument, as many methods do. Then `undefined` should be rejected, because the caller hasn't provided the proper arguments.
