### ISSUE TITLE
ZZZ format does not work as intended

### ISSUE THREAD

**Issue by MakakWasTaken** [moment/luxon#1362]
**Describe the bug**
The `DateTime.fromFormat` function does not function as intended for the format code ZZZ

**To Reproduce**
```typescript
const dateTime = DateTime.fromFormat('+0100', 'ZZZ')
```

**Actual vs Expected behavior**
I expected the ZZZ format to be able to succesfully handle it in accordance with the following:

| Standalone token | Format token | Description                                                    | Example                                                       |
| ---------------- | ------------ | -------------------------------------------------------------- | ------------------------------------------------------------- |
| ZZZ              |              | techie offset                                                  | `+0500`                                                       |

from: [Formatting](https://github.com/moment/luxon/blob/master/docs/formatting.md)

**Desktop:**

- OS: Windows 11
- Luxon version: 3.2.1
- Your timezone: +0100

**Comment by icambron** [comment]
Fixed in e7810521. Two notes:

1. Since there's no actual time specified, you'll get the current time. YMMV on whether that is actually useful or not
2. Without the `{ setZone: true }` option, the offset doesn't actually do anything. By default, the parsed offset tells Luxon how to interpret the date and time information in the string (e.g. +0100 tells us the string is expressed in UTC+1) and that gets reflected in how the time is converted to a local time. Because in this case there is no other info in the string, there is nothing to interpret in accordance with the specified offset. In contrast, the `setZone` option will cause the resulting DateTime instance to be set to UTC+1 (or whatever the string says), so it'll be the same result as `DateTime.now().setZone("UTC+1")`
