### ISSUE TITLE
Better regex from DateTime.fromFormatExplain()

### ISSUE THREAD

**Issue by tounsoo** [moment/luxon#1378]
Hello,

I'm trying to create an Input component for date with a mask functionality. Mask function works with regex and I was trying to see how I can make a the Input component for date be flexible with the format it gets from the prop.

I found that luxon(which I was using already) has `DateTime.formFormatExplain` that spits out regex of the format it used which is AWESOME!

But it is a bit plain that it allows any number for month and days.

```
const formatRegex = DateTime.fromFormatExplain('02/02/2024, 'MM/dd/yyyy').regex;
 ^ = /^(\d{2})(\/)(\d{2})(\/)(\d{4})$/I
```

What I hope is to get a regex that will guard month and day properly with leap year accounted for. I do see many people suggesting lloooonnnggg regex in StackOverflows and I thought it would be awesome if some of those were tested and provided by luxon natively. 

Here's one of the post from Stackoverflow : https://stackoverflow.com/questions/42516815/regex-date-mm-dd-yyyy-formatting-javascript

**Comment by diesieben07** [comment]
One problem with this would be the regression in invalidReason and invalidExplanation for such invalid inputs. Currently trying to parse 02/29/2023 will result in "unit out of range". If the format regex itself wouldn't even match this, it would just be "unparsable".

**Comment by tounsoo** [comment]
My use case is using a mask input that takes in regex to mask the string.

**Comment by icambron** [comment]
Yes, I understand why you want this, but it isn't a good idea for Luxon to use a smarter regex. This is mostly for the reason @diesieben07 alluded to: namely that it prevents Luxon from distinguishing between an invalid date (e.g. "1999-02-29") and a misformatted one. 

In addition, it would add a fair amount of complexity . As an example, the format string may not provide a year and expect to default to the current year, which would need some other regex that prebakes in the year in order to embed the leap year logic into the regex. Another example is that besides year/month/day, we'd need similar regex magic for week-year/week/weekday. Finally, Luxon already has way too much regexing.

So we're going to pass on this one.

**Comment by tounsoo** [comment]
Oh, I thought that `DateTime.fromFormatExplain('00/00/0000', 'MM/dd/yyyy').regex` would still provide the same regex and that it was just for consumers to use. Didn't know that those were used to validate dates.

**Comment by icambron** [comment]
Yeah, the idea of fromFormatExplain is to help you debug why your string didn't match the format by exposing the process Luxon uses. So it provides the regex Luxon uses to parse the string. Luxon then validates the parsed values to check for stuff like invalid dates.
