### ISSUE TITLE
Inconsistent duration calculations around some dates

### ISSUE THREAD

**Issue by bogdanb** [moment/luxon#1389]
**Describe the bug**

Luxon seems to get wrong results for some date diff operations.

**To Reproduce**

Try the code below (you can find it at https://runkit.com/bogdanb/luxon-year-100):

```
const z = luxon.DateTime.fromISO('0099-12-31', {zone: "utc"})
const a = luxon.DateTime.fromISO('0100-03-01', {zone: "utc"})
const b = luxon.DateTime.fromISO('0100-03-02', {zone: "utc"})

console.log("diffs:",  a.diff(z), b.diff(z))
console.log("diffs as days:", a.diff(z).as('days'), b.diff(z).as('days'))
console.log("day diffs:", a.diff(z, 'days'), b.diff(z, 'days'))
console.log("day diffs as days:", a.diff(z, 'days').as('days'), b.diff(z, 'days').as('days'))
```

**Actual vs Expected behavior**

I would expect the two methods to get the same results, and, for each method, the two diffs to be separated by one day. In practice, the first calculation method returns 60 & 61 days, while the second returns 60 and 62 days. (Unless I’m missing something, the first one should be the correct one.)

Note that if you use `0100-01-01` (or a later date) for `z`, then the two calculation methods agree.

**Desktop (please complete the following information):**

- OS: Windows (but I doubt it matters).
- Browser: Chrome & Firefox, plus I think RunKit runs directly in node.
- Luxon version: 3.2.1
- Timezone: UTC

**Additional context**

Note that year 100 is not a leap year, because even if it’s divisible by 4, it’s divisible by 100 but not by 400. I’m not sure this is the problem, I tried other years like that and I could not reproduce the issue.

**Comment by bogdanb** [comment]
I also got weird duration diffs for other year pairs. I’m not sure exactly but based on some tests that are failing in one of my projects it kind of looks like it’s related to a 400-year cycle, though the rule is not obvious.

For example,
```
const z = luxon.DateTime.fromISO('0001-12-31', {zone: "utc"})
const a = luxon.DateTime.fromISO('0500-03-25', {zone: "utc"})
const b = luxon.DateTime.fromISO('0500-03-26', {zone: "utc"})
```
also get different results between the two methods (181975/181976 and 181976/181977), though here each method is consistent with itself.

**Comment by diesieben07** [comment]
This is a _very_ subtle bug... Holy moley. Took me like the past 2 hours to find.

The problem here is not `diff`, but actually `plus`:
`DateTime.fromISO('0099-12-31', {zone: "utc"}).plus({days: 61}).toISODate()` produces `0100-03-01`, not `0100-03-02`. What is happening is that deep inside Luxon it calls `Date.UTC` with a computed date object (day, month, etc.). `Date.UTC` however treats years before 100 as 19XX. So year 99 turns into 1999. Luxon works around this by checking if the year is < 100 and if so, using `setUTCFullYear` afterwards. Here is the problem: year 2000 is a leap year, year 100 is not. So if you do a plus operation that goes from year 99 into year 100, the native JavaScript Date object thinks it is crossing from year 1999 into year 2000 - and year 2000 is a leap year. Luxon then goes in and fixes it back to year 100 - but the damage is done, the calculation was done with "this is a leap year" in mind.

I will probably write a pull request later to fix it.

**Comment by bogdanb** [comment]
@diesieben07 Good find!

Any idea when this will get into a release? No rush nor any pressure intended, just need to know how/when to schedule a deps update on my side.
