### ISSUE TITLE
FromFormat parsing with YYYY/MM/DD or YYYY-MM-DD

### ISSUE THREAD

**Issue by Bhupendersinghbisht** [moment/luxon#1395]
Hello, 

I have long parsing list(array) which can be in YYYY/MM/DD ,YYYY-MM-DD Or YYYY/M/D , YYYY-M-D format. 
Can i pass date in format with / or - and get that parsed on single validation?

**Comment by skpanagiotis** [comment]
Hello,  
Maybe there could be a new method (if developers want) for example `DateTime.fromFormatArray('2023/03/16', ['yyyy/mm/dd', 'yyyy-mm-dd', 'yyyy/m/d', 'yyyy-m-d'])`, which will has as parameter an `Array<string>` with the acceptable date formats.   

In this way, the given Date will be tested, for parsing, for every given format, until the given Date parsed successfully.  

Also you can do something like this:  

```
const acceptableFormats = ['yyyy/mm/dd', 'yyyy-mm-dd', 'yyyy/m/d', 'yyyy-m-d'];
let dateTime: DateTime;
acceptableFormats.forEach((x) => {
    if (!DateTime.fromFormat('2023/03/16', x).invalid) {
        dateTime = DateTime.fromFormat('2023/03/16', x);
        break;
    }
});
```

**Comment by diesieben07** [comment]
Personally I don't think this is sort of thing is a good idea, because it can lead to ambiguity and errors very quickly. Your formats have to be very carefully chosen to not allow ambiguity.
This is why generally when you're interacting "with a computer" (i.e. through some kind of API) you're using a machine-readable, well defined format (like ISO 8601 or a unix timestamp) and when you're interacting "with a human" (through a UI) you're using a proper user interface (i.e. a date picker or something similar), which makes sure the data input is not ambiguous and is properly validated.
The case where you're having a human enter a string to be parsed needs to be treated with care, because humans are usually bad at being consistent and making sure they stick to the proper format (unless maybe they are a programmer). This is why when you have a string based user input it is especially important to have proper validation to make sure they put in the correct thing. Guessing based on the input can lead to bad results.

As such I don't think we should encourage this sort of pattern by adding a dedicated method for it. Especially because it is extremely simple to implement in your own code.
To give a concrete example of how I would implement the example given by @skpanagiotis:
```js
let input = prompt("Enter a date:");
input = input.replaceAll('/', '-');
const dateTime = DateTime.fromFormat(input, 'y-m-d');
```

Trying to parse `m` and `mm` in order doesn't really give you anything, because anything that can be parsed by `mm` can already be parsed by `m`; same for the other tokens.

**Comment by janvorwerk** [comment]
> ```
> const dateTime = DateTime.fromFormat(input, 'y-m-d');
> ```
> 
> Trying to parse `m` and `mm` in order doesn't really give you anything, because anything that can be parsed by `mm` can already be parsed by `m`; same for the other tokens.

Make sure you use a capital M:

    'y-M-d'
