### ISSUE TITLE
Interval.prototype.divideEqually does not include the day DST starts

### ISSUE THREAD

**Issue by zombieleet** [moment/luxon#1413]
**Describe the bug**
`Interval.prototype.divideEqually` does not include the day DST started

**To Reproduce**

```javascript
const luxon = require('luxon');
const march = luxon.DateTime.fromFormat('2023-03-31', 'yyyy-MM-dd')
const interval = luxon.Interval.fromDateTimes(march.startOf('month'), march.endOf('month'))
const daysInMarch = interval.divideEqually(Math.round(interval.length('days')))

// this totally ignores 26th of March (which was the day DST started in Berlin)
console.log(daysInMarch.toString())
```

**Actual vs Expected behavior**
All dates in march should be included (including DST)

**Desktop (please complete the following information):**

- OS: OSX
- NodeJS: 19.16.1
- Luxon version: 3.3.0
- Your timezone: Europe/Berlin

**Comment by diesieben07** [comment]
March is 31 days in 2023, that is correct. However those 31 days are not all 24 hours long. One of them (the 26th of march) is only 23 hours long. As such your interval is only 743 (not 744, which would be 24 * 31) hours long.
As such, when you ask Luxon to split the interval into 31 equal parts, those parts are not 24 hours long, they are 23.9677..., hours long. This means that the start of each split drifts further and further before midnight. Then, because the 26th of december is only 23 hours long, but your interval parts are almost 24 hours long, the 26 is skipped.

If you want the actual days, you should use
`daysInMarch.splitBy({days: 1})`, which produces your desired output.

Also refer to the [documentation on calendar vs. time math](https://moment.github.io/luxon/#/math?id=calendar-math-vs-time-math).

I hope this helps!
