### ISSUE TITLE
Timezone setting not working on constructor

### ISSUE THREAD

**Issue by ericmorand** [moment/luxon#143]
Consider the following example:

```
let dateInNewYork = new Date(2010, 9, 4, 13, 45, 0);

let dt = DateTime.fromJSDate(dateInNewYork, {
  zone: 'America/New_York'
})
```

I'm creating a DateTime that represents 04/10/2010 13:45:00 in New York.

But here is the result of a toRFC2822() call:

`Mon, 04 Oct 2010 07:45:00 -0400`

The date is set to 07:45 in New York.

**Comment by icambron** [comment]
`fromJSDate` doesn't work like that. It sounds like you want to mean "make a datetime with the same local time in the target zone as this date object's local time in the system's local zone"? That would be pretty weird: a Javascript date represents a specific global time, not just a local time. Remember, Luxon doesn't see those arguments  you passed into the native date constructor; it just sees a date object that says "I'm whatever time it is 1286214300000 milliseconds after it was Jan 1, 1970 in Greenwich". While Luxon *could* interpret the input as a local time that needs anchored to the specified zone, that's not how Luxon does things; it never changes the underlying time unless you really tell it to.

You have two options:

1. Construct the whole thing in Luxon:

```js
var dt = DateTime.fromObject({year: 2010, month: 10, day: 4, hour: 13, minute: 45, zone: 'America/New_York'});
dt.toISO() //=> "2010-10-04T13:45:00.000-04:00"
```

That's different because when all we have is numbers, we get to choose what zone to interpret them as being expressed in, whereas with the JS Date you've already decided that because the Date constructor uses the local zone.

2. Use `keepCalendarTime`. This option doesn't work in the constructor (I may change that - it would be a fair request), but it works in `setZone`:

```js
dt = DateTime.fromJSDate(dateInNewYork).setZone('America/New_York', {keepCalendarTime: true});
```

That extra flag says "yes, change the actual time". (FYI, I'm going to change that option name to `keepLocalTime` soon)

**Comment by ericmorand** [comment]
Thanks a lot for all those explainations. That makes senses.
