### ISSUE TITLE
DateTime.local().offset command returning Eastern Daylight Savings. How to fetch EST instead?

### ISSUE THREAD

**Issue by calicoder77** [moment/luxon#1461]
Good day,

First off incredible work on the project so far. I have a command like this:

`DateTime.local().offset`

and it returns the daylight savings time I'm in currently. I would like to use Zulu time (UTC) but don't see any docs on how to actually do that. My ultimate goal is to be able to get the proper UTC + or - for my area without the DST. Is this possible? How exactly would I go about doing this?

Thanks

**Comment by diesieben07** [comment]
Unfortunately there is no straightforward way to do this, because the Intl API does not expose this information. However you can get close by "probing". Use a resource like [this table](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country) to find a suitable date and then move your local date to a position on the timeline that would be outside DST in all zones (or all zones you care about). Then use that DateTime's offset.

**Comment by calicoder77** [comment]
Hi @diesieben07,

Thanks for the quick reply. Guess I can live with the DST being on every so often.
