### ISSUE TITLE
CivilDate and CivilTime

### ISSUE THREAD

**Issue by lundmikkel** [moment/luxon#155]
Is it me, or doesn't Luxon support [CivilDate and CivilTime](https://github.com/tc39/proposal-temporal)?

**Comment by icambron** [comment]
Nope, there are only datetimes (in Temporal terms: ZonedInstants with tools to manipulate them as CivilDateTimes), because that's all that's actually in the browser. Once an implementation of Temporal ships, I'll add support for them. I have no plans to support them before then.

**Comment by lundmikkel** [comment]
So I wasn't necessarily thinking about the particular types, more about the concept of a date without time and time without a date. Always having them combined is often the cause of horrible practices (such as trying to convert a local date (CivilDate) into UTC).

I'm not quite sure what you mean with "that's all that's actually in the browser". What JS supports? Or what kind of concepts can be supported?

**Comment by icambron** [comment]
Well, in principle it would certainly be possible to build pure dates and pure times by abusing the native Date type in funny ways, but I decided early on that was out of scope. I'd prefer to wait until I have a real implementations of civildate and civiltime available in the browser, because I suspect that otherwise it will be a ton of code.

For what it's worth, setting the zone to UTC on a DateTime will make it act like a Date.
