### ISSUE TITLE
Browser error: exports is not defined

### ISSUE THREAD

**Issue by mariomka** [moment/luxon#161]
Seems to browser version ("browser": "build/cjs-browser/luxon.js") build don't work. It throws some errors in console:

```
Uncaught ReferenceError: exports is not defined
```

JSFiddle example loading luxon from unpkg: https://jsfiddle.net/9ws9xmw5/

**Comment by icambron** [comment]
The cjs-browser build is meant to be loaded via `require()`. It's included in the NPM module because I want, say, webpack users using NPM-loader to get it instead of the build meant for Node. Consequently, it doesn't export a browser global and it expects `exports` to be available.

The upshot is that I don't expect to work when pulled in as a browser global like that. Instead, you want the global build. It's not included in the NPM module and thus not in unpkg either. It's here: https://moment.github.io/luxon/global/luxon.min.js. Here's a fork of your fiddle that uses it: https://jsfiddle.net/drf0bnh2/1/

Let me know if:

 * I've misunderstood the concern
 * I've misunderstood something about how browser-code-in-npm is supposed to work
 * I can make it easier for CDNs to get the right builds

**Comment by mariomka** [comment]
Thank for your answer.

I'm developing a date time picker ([vue-datetime](https://github.com/mariomka/vue-datetime)) based on luxon and I had problems to run an example in JSFiddle. I'll use that global build.

I don't have too much experience with CDNs like unpkg but I think you can add an `unpkg` property (I thought it was `browser`...) to point the global build if u want to add to NPM build. See more unpkg/unpkg#63

**Comment by tiberiuzuld** [comment]
Hi @icambron ,
We currently have the same issue.
We want to migrate from moment to luxon.
We don't use webpack and CDN's for us is a no go because we have users on local private networks without access to internet.

We can download the CDN file and save it manually but is harder to check for new versions.
We make references manually in the index.html to scripts in node_modules.
Can the build for browser be included in the npm build folder ?

Thanks

**Comment by icambron** [comment]
I can include it in the NPM package, sure. For the reasons above you'll need to construct your own path into it.

Reopening this to track it.

**Comment by tiberiuzuld** [comment]
Thats ok we will set our own path to it.

Thanks

**Comment by icambron** [comment]
Added the browser global to the NPM package in version 0.5.6

**Comment by tiberiuzuld** [comment]
Works thank you!
