### ISSUE TITLE
Inconsistency in leap year difference of days

### ISSUE THREAD

**Issue by Rockhount1793** [moment/luxon#1611]
**Describe the bug**

**To Reproduce**
Please share a minimal code example that triggers the problem:

const dateCheckIn = DateTime.fromISO("2024-01-01")
const dateCheckOut = DateTime.fromISO("2024-02-29")
let _diferenceDays = dateCheckOut.diff(dateCheckIn,["years","months","days"]).as("days")
console.log("difference days",_diferenceDays) // result 58 expected 59

- OS: [Windows 11]
- Browser [Edge 122]
- Luxon version [3.4.4]
- Your timezone ["America/Bogota"]

**Additional context**
Gracias por su gran trabajo!

**Comment by icambron** [comment]
See [losing information](https://moment.github.io/luxon/#/math?id=losing-information), which describes this issue in detail. 

The problem is that you're taking the diff in year/month/day. So it's 0 years, 1 month, 28 days. Then you asked Luxon to convert that to days. In Luxon's conversions, a month is a 30 days; the diff doesn't remember the _specific_ month was January.

All you need to do is take the diff in the unit you actually want to use:

```js
 dateCheckOut.diff(dateCheckIn, "days").get("days") //=> 59
```
