### ISSUE TITLE
Luxon homepage not working

### ISSUE THREAD

**Issue by mobilutz** [moment/luxon#1618]
**Describe the bug**

The Luxon homepage https://moment.github.io/luxon/ does not work.

**To Reproduce**

Visit https://moment.github.io/luxon/

**Actual vs Expected behavior**

Homepage being displayed.

**Additional context**

It seems that the unpkg.com responses lead to the problem, see here as an example: https://unpkg.com/docsify/lib/docsify.min.js

**Comment by icambron** [comment]
If you remove the trailing slash it works. I'd certainly accept a PR fixing it

**Comment by rluba** [comment]
Nope, I can confirm that it is not working for me – with or without the slash. Without the slash redirects to with slash.

The problem is that docsify.min.js responds with a 520 error:
<img width="1016" alt="luxon" src="https://github.com/moment/luxon/assets/4600573/4f523709-88a8-4bdc-b90b-ac10bf40f412">

**Comment by mobilutz** [comment]
It is working again, see screenshot.
![Screenshot 2024-04-18 at 13 15 44](https://github.com/moment/luxon/assets/491877/df23f949-2882-4a00-a688-d69df3f612c0)


I guess the problem was that unpkg.com had a problem or so ...
