### ISSUE TITLE
duration of 118.7 days outputs different for `DateTime.toRelative()` and `DateTime.diff().rescale()`

### ISSUE THREAD

**Issue by n0099** [moment/luxon#1650]
**Describe the bug**

**To Reproduce**
```js
a = luxon.DateTime.fromSeconds(1713645066)
b = luxon.DateTime.fromSeconds(1723901475)
a.toISO() // '2024-04-20T20:31:06.000+00:00'
b.toISO() // '2024-08-17T13:31:15.000+00:00'
a.toRelative({base:b, round: false}) // '3.89 months ago'
b.diff(a).rescale().toHuman() // '4 months, 6 days, 17 hours, 9 seconds'
b.diff(a).shiftTo('day').toObject() // {days: 118.7084375}
```

**Actual vs Expected behavior**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome 128
- Luxon version: 3.5.0
- Your timezone: UTC

**Additional context**

**Comment by n0099** [comment]
```js
b.diff(a, undefined, { conversionAccuracy: 'longterm' }).rescale().toHuman()
// '3 months, 2 weeks, 12 days, 33 hours, 32 minutes, 50 seconds, 1000 milliseconds'
```

**Comment by diesieben07** [comment]
If you will look at the actual object you'll find that there are not 1000ms in the Duration:
```js
const a = DateTime.fromSeconds(1713645066)
const b = DateTime.fromSeconds(1723901475)
console.log(b.diff(a, undefined, { conversionAccuracy: 'longterm' }).rescale().toObject());
// {"months":3,"weeks":2,"days":12,"hours":33,"minutes":32,"seconds":50,"milliseconds":999.999998624844} 
```
The problem here is just floating point accuracy. We are stuck with floating point numbers in JavaScript. `toHuman` uses `Intl.NumberFormat` under the hood. The default options for it have `maximumFractionDigits` at 3, which causes the rounding.
```js
b.diff(a, undefined, { conversionAccuracy: 'longterm' }).rescale().toHuman({maximumFractionDigits: 10})
// 3 months, 2 weeks, 12 days, 33 hours, 32 minutes, 50 seconds, 999.9999986248 milliseconds
```

> If I .shiftTo('years', 'months', 'weeks', 'days', 'hours', 'minutes', 'seconds') after .rescale() it will prepend useless 0 years,  at the beginning.

Yes, because you explicitly told Luxon to include "years" in the duration, _but there are no years_.
