### ISSUE TITLE
Differences between docs and result for locale FR and some formats with "à" between date and time

### ISSUE THREAD

**Issue by ThomasGaboriau** [moment/luxon#1664]
**Describe the bug**
In the formats preset [docs](https://moment.github.io/luxon/#/formatting?id=presets), there are some formats with the "à" seperator that is not here when running the code.

**To Reproduce**
```typescript
import { DateTime } from 'luxon';

const d = DateTime.fromISO('2024-10-29T10:00:00+00:00').setLocale('fr');
console.log(d.toLocaleString(DateTime.DATETIME_SHORT));
``` 
Stackblitz for convenience : [stackblitz](https://stackblitz.com/edit/hidpqe?file=index.ts)

**Actual vs Expected behavior**
All `DATE_TIME_MED_XX` and `DATE_TIME_SHORT_XX`  formats differ from docs and real use : 
- `DATETIME_SHORT` => prints `29/10/2024 11:00` instead of `29/10/2024 à 11:00`
- `DATETIME_MED` => prints `29 oct. 2024, 11:00` instead of `29 oct. 2024 à 11:00`

**Desktop:**
- OS: Windows
- Tested in Chrome and Firefox
- Luxon 3.5.0

**Comment by diesieben07** [comment]
The docs are only an example. The output of `toLocaleString` is generated by the browser and is not guaranteed to output any particular format (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/format#return_value)). You should not rely on this method producing any exact format. If you really need that, use `toFormat`.

That said, we could update the docs, if they are no longer accurate compared to what most browsers generate.

**Comment by diesieben07** [comment]
There is no direct API for this "separator", because one is not offered by the browser. I did some experimentation and this "separator" seems to be driven by some kind of heuristic. Chrome/Node.JS (both use V8) and Firefox seem to act the same here in my tests. If `month` is set to `long` the separator will be shown, if not, it will just be a comma. This is the case for all three locales I tested: fr ("à"), en ("at") and de ("um").

One possible way might be to "force" (this is really not a guarantee) the browser to show the separator by using `month: 'long'`, use `formatToParts` and manually replace the long month format with your own.

When using `toFormat` you're expected to add "glue parts" like this, which are not actual date/time components yourself directly in the format.

**Comment by ThomasGaboriau** [comment]
Thanks a lot for the time you spent on this.
I came up with [something](https://stackblitz.com/edit/hidpqe-zfuxp4?file=index.ts) based on your comment, but the code feels bad and I'm not fond of the "no guarantee" part. I leave it here in case someone esle comes here later.

So I guess no seperator will do just fine.

Thanks again, I'm closing the issue.
