### ISSUE TITLE
fromISO → toLocaleString inconsistency when in zone "system"

### ISSUE THREAD

**Issue by andraaspar** [moment/luxon#1666]
**Describe the bug**
See below.

**To Reproduce**
```js
luxon.DateTime.fromISO('1800-11-01', {zone:"system"}).toLocaleString()
→ '10/31/1800'
luxon.SystemZone.instance.name
→ 'America/New_York'
luxon.DateTime.fromISO('1800-11-01', {zone:"America/New_York"}).toLocaleString()
→ '11/1/1800'
```

**Actual vs Expected behavior**
```js
// Actual
'10/31/1800'
// Expected
'11/1/1800'
```

**Desktop (please complete the following information):**

- OS: Microsoft Windows 11 Pro 10.0.22631 Build 22631
- Browser: Google Chrome 130.0.6723.117 (Official Build) (64-bit)
- Luxon version: 3.5.0
- Your timezone: "America/New_York"

**Additional context**
Reproducible on the home page here: https://moment.github.io/luxon/#/

**Comment by diesieben07** [comment]
This is an issue with historic time zones, which have weird offsets from UTC (in this case something like UTC-4:56:02).

The reason you're seeing a difference between the system zone and a named zone is due to the way Luxon gets offsets for the two.
For the system zone, we just call `new Date(ts).getTimezoneOffset()`, which gives the offset in minutes. In this case this turns out to be `-296`. But this is not quite correct, the offset has sub-minutes components, for which JavaScript just doesn't have an API.
For named zones, Luxon does a more or less elaborate scheme using the `Intl.DateTimeFormat` API to calculate the offset manually. This is much slower (because `Intl.DateTimeFormat` is quite slow), but due to Luxon calculating it manually this will take sub-minute components into account.

Historic time zones like this just cannot be accurately dealt with in JavaScript unfortunately.

**Comment by andraaspar** [comment]
Thank you for the explanation. What would be the best course to take if one needs to support historic calendar dates, assuming that there will be no interaction between historic dates and date times?

1. Someone in a similar issue mentioned always using `{zone:'utc'}` for calendar dates. Would that work, or do you see any caveats?
2. Any other recommendations? Maybe a different library? Or no library, and just rely on JS Date?

**Comment by diesieben07** [comment]
I would recommend going with the "always use UTC" route.
