### ISSUE TITLE
toFormat incorrectly calcuclates over year boundry for some tokens

### ISSUE THREAD

**Issue by davecarlson** [moment/luxon#1674]
**Describe the bug**

If you have trying to get the week number over the new year, it seems that it incorrectly calculates it:
console.log(DateTime.fromISO("2024-12-30").toFormat("yWW"));

**To Reproduce**
Please share a minimal code example that triggers the problem:

console.log(DateTime.fromISO("2024-12-30").toFormat("yWW"));

**Actual vs Expected behavior**
Actual result: 202401
Expected result: 202501

**Desktop (please complete the following information):**

- Browser [e.g. Chrome 84, safari 14.0]
- Luxon version [e.g. 1.25.0]
- Your timezone [e.g. "America/New_York"]

**Additional context**

**Comment by diesieben07** [comment]
The `y`-tokens show the normal Gregorian calendar year. So, for `2024-12-30` it shows the year 2024, because that is what the Gregorian year is.

My guess, considering that you're outputting the week number and also because it would match your expected output, is that you want the week year instead. The token for week year is `kk` or `kkkk`.
