### ISSUE TITLE
Incorrect offset when setting timezone using zoneName

### ISSUE THREAD

**Issue by jonahkagan** [moment/luxon#171]
Here's a little example of what I'm seeing. I've set my computer's local timezone to Hawaii time (`"Pacific/Honolulu"`). This code is running via react-native 0.49.5 using luxon 0.4.0.

```
const d = DateTime.local();
console.log(d.offsetNameLong, d.offsetNameShort, d.offset, d.zoneName)
const d2 = d.setZone(d.zoneName);
console.log(d2.offsetNameLong, d2.offsetNameShort, d2.offset, d2.zoneName)
```

Output:
```
GMT-10:00 GMT-10 -600 Etc/GMT+10
UTC+10 UTC+10 600 UTC+10
```
What's causing issues for me is that one offset is positive while the other is negative. I would expect them to match. It seems like the cause might be that the zoneName in the first line of output doesn't match the offset names in that line of output.

Let me know if you have any idea what's going on or if you need more info. Thanks!

**Comment by icambron** [comment]
Tricky one.

You appear not to have time zone support from Intl. For example, when I run your code in Chrome, I get `Hawaii-Aleutian Standard Time HST -600 Pacific/Honolulu` for both `console.log` outputs. You shouldn't have to use UTC offsets because the Intl API should supply your real TZ name. If this is RN on Android, check out [this](http://moment.github.io/luxon/docs/manual/install.html#react-native).  Otherwise, I'm pretty confused about why `DateTime.local().zoneName` would give you `GMT-10:00` in the first place instead of Pacific/Honolulu.

That said, it should still work. One problem is that Luxon is providing you a zone name it doesn't know how to parse. On my computer:

```js
DateTime.local().setZone("UTC-10").zoneName //=> UTC-10 (good)
DateTime.local().setZone("Etc/GMT-10").zoneName //=> UTC-10 (good)
DateTime.local().setZone("GMT-10").zoneName // => America/New_York (not good)
```

There's an exacerbating bug here: 

```
DateTime.local().setZone("GMT-10").invalidReason => "unsupported zone"
````

That's correct, and `zoneName` should be returning null for invalid instances. That might have made the issue more obvious. Instead it's giving me the default zone. I'll fix that.

Anyway, to fix that issue, we need to make sure that either a) Luxon can parse "GMT-10" or b) Luxon produces "Etc/GMT-10" as the output from `zoneName` in these situations; Luxon ought to be able to parse anything it produces.

But all that *still* doesn't explain what you're seeing, because at worst `setZone(thingLuxonDoesntUnderstand)` should set the zone to your default zone, which is actually already `GMT-10`, not `+10,` so it ought to have worked anyway, albeit with an invalid Luxon instance. So there's something odd there. I wonder if it's a Luxon bug that only shows up in the absence of Intl support?

I'm going to fix the two issues above and also write an if-you-don't-have-Intl test case to double check that no sign is getting flipped anywhere.

**Comment by jonahkagan** [comment]
Thanks for digging in! It does seem tricky.

What do you mean when you say that "Luxon is providing you a zone name it doesn't know how to parse." Are you referring to `"GMT-10"`? If so, I don't think Luxon ever gave me that as `zoneName`, only as `offsetNameShort`.

I expected that in the first `console.log` line, `zoneName` would be `"Etc/GMT-10"`, but got `"Etc/GMT+10"`. In other words, you laid out options (a) and (b), and I think that option (b) hits the issue, not option (a). I just am throwing this out to check my understanding - you definitely have a deeper better knowledge of what's going on than I do.

**Comment by icambron** [comment]
Er, right. `GMT-10:00` has the same problem though. That's not a string Luxon accepts a zone name for `setZone()`

I agree that (b) is the better fix.

**Comment by icambron** [comment]
[note: I deleted my comment and your response, because my comment was wrong and I don't want to confuse people in the future.]

Can you run this:

```js
 new Intl.DateTimeFormat("en", { timeZoneName: "long" }).format()
```

I bet that returns `Etc/GMT+10`. I was able to reproduce that behavior by setting my TZ env var to `Etc/GMT-10` and running it in Node. So here's my guess:

 1. In your environment, for some reason `Pacific/Honolulu` is being reduced to `Etc/GMT-10` before any Javascript even sees it. Honolulu in particular has no DST so you'll get accurate times, but if it does the same thing for other zones, that would be really bad. This may be an RN-specific issue.
 2. There's a V8-level bug where the output to that formatter has the wrong sign. I think that's just something that needs filed with Chromium

From Luxon's point of view, it asked Intl what the time zone is called, got "Etc/GMT+10", and then just relayed that to you. When you passed that zone name back in, Luxon interpreted it correctly (or, more specifically, Intl interpreted it correctly). The end result is that the offsets got flipped.

So I'm not sure there's much we can do. Luxon can't realistically second-guess Intl here. I think we just need Chromium to fix the bug.

**Comment by jonahkagan** [comment]
I ran that command and it returned this: `"2/4/2018, GMT-10:00"`

**Comment by icambron** [comment]
That's is surprising. Can you also try this: ` Intl.DateTimeFormat().resolvedOptions().timeZone`?

**Comment by jonahkagan** [comment]
Yep, that returned `"Etc/GMT+10"`

**Comment by icambron** [comment]
OK, so there's the issue. That's how [Luxon does it too](https://github.com/moment/luxon/blob/d485b16ba0aef87d2a9b9956f6c2593e0cfda16c/src/zones/localZone.js#L24). So I think you'll need to get that fixed upstream (or find out why it's not just Pacific/Honolulu!)

**Comment by jonahkagan** [comment]
Ok thanks. I already found a workaround so I'm set
