### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by dbucci24** [moment/luxon#185]
Hello! I would like to translate the project into Spanish! is it already translated?

**Comment by icambron** [comment]
https://moment.github.io/luxon/docs/manual/intl.html

**Comment by dbucci24** [comment]
@icambron what does it mean? Can I translate all that?

**Comment by icambron** [comment]
Oh, you mean you want to translate the documentation? Sorry, I thought you meant translate the outputs from Luxon. There's no existing translation of the docs, no. If you want to translate it, feel completely free to do so, though I'd ask that you host it elsewhere, since I won't be able to maintain it.

**Comment by dbucci24** [comment]
How can I host it somewhere else?

**Comment by icambron** [comment]
If you fork this repository, you should be able to build and publish it in Github pages (i.e. dbucci24.github.io/luxon).
