### ISSUE TITLE
Question: how to compare if datetimes are the same

### ISSUE THREAD

**Issue by trevordmiller** [moment/luxon#200]
Moment has `isSame` to compare if datetimes are the same (not specific to a unit) - ie:

`moment('2010-10-20').isSame('2010-10-20'); // true`

How can you compare entire datetimes with Luxon? From the docs, it seems only comparing pieces of the datetime - the units - is supported: https://moment.github.io/luxon/docs/manual/moment.html#query

**Comment by trevordmiller** [comment]
Nevermind, I found it: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-equals

Seems like the equivalent of `dateTime.isSame(anotherDateTime)` from Moment in Luxon is `dateTime.equals(anotherDateTime)`. This might be worth adding to the Query section of the moment vs luxon docs:
https://moment.github.io/luxon/docs/manual/moment.html#query

**Comment by icambron** [comment]
`equals` is really not quite the same thing, since it also compares stuff like the time zone and locale, whereas `isSame` just compares the times. But check out the docs here: http://moment.github.io/luxon/docs/manual/math.html#comparing-datetimes

There's also `hasSame`, which is the equivalent of `isSame`: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-hasSame. The only difference is that Moment's defaults the second argument to `millisecond`, whereas that doesn't make much grammatical sense with "has". 

So the issue re: the docs is that there isn't quite a clean one-to-one correspondence.

**Comment by trevordmiller** [comment]
@icambron That makes sense, thank you for the info!
