### ISSUE TITLE
Can't get weekdays in Spanish locale

### ISSUE THREAD

**Issue by cdelgadob** [moment/luxon#225]
I am evaluating Luxon as an alternative to momentjs, but the locale support doesn't seem to work.

Here is a simple example while trying to get the weekdays: [RunKit code sample](https://runkit.com/embed/cd1fyzb3mt5k)

I have read docs that says that Node is compiled with just one locale: 'en'

Maybe this is related to this, as it seems that Luxon relies in the native JavaScript Date object underneath? If that is so, how could I solve that?

Thanks

**Comment by icambron** [comment]
Yes, Luxon uses the Intl API, which requires ICU support. From the install guide:

> If you want to work with locales, you'll need to have full-icu support installed in Node. You can build Node with it, use an NPM module to provide it, or find it prepackaged for your platform, like brew install node --with-full-icu. If you skip this step, Luxon still works but methods like setLocale() will do nothing.

When you installed `full-icu` (since I see you require it in the RunKit), you should have gotten a message that says this:

```
Node will use this ICU datafile if the environment variable NODE_ICU_DATA is set to “node_modules/full-icu”
or with node --icu-data-dir=node_modules/full-icu YOURAPP.js
 For package.json:
{"scripts":{"start":"node --icu-data-dir=node_modules/full-icu YOURAPP.js"}}

By the way, if you have full data, running this in node:
> new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
... will show “enero”. If it shows “January” you don't have full data.
News: Please see https://github.com/icu-project/full-icu-npm/issues/6
```

You can also use an env var like here: https://github.com/moment/luxon/blob/master/scripts/repl

I've tried to avoid replicating full-icu's documentation here, but I may have to reverse that.
