### ISSUE TITLE
Duration equality does not consider alternate ways of writing duration

### ISSUE THREAD

**Issue by Korkkii** [moment/luxon#233]
ISO 8601 standard accepts both `PT1H` and `PT60M` as 1 hour duration, but luxon's Duration's `equals` method return false for equality check. 

```
const asHour = Duration.fromISO('PT1H')
const asMinutes = Duration.fromISO('PT60M')
console.log(asHour.equals(asMinutes)) // return false when expecting true

const anotherHour = Duration.fromISO('PT1H')
console.log(asHour.equals(anotherHour)) // return true as expected
```

**Comment by icambron** [comment]
Yeah, equality of durations is component equality. This seems a bit silly for hours vs minutes, but consider hours vs days: they really do behave differently. See [calendar math](https://moment.github.io/luxon/docs/manual/math.html); a day and adding 24 hours can have different results. So it would be weird for them to be equal. I want equal to mean "fully interchangeable".

Of course, I could have made milliseconds, seconds, minutes, and hours all boil down to milliseconds and *otherwise* compare componentwise, but that sounds complicated and unintuitive, especially considering that you can can just do `asHour.as('milliseconds') === asMinutes.as('milliseconds')`.

I'd like to make that even easier; see #235, which would allow `+asHour === +asMinutes`.

Anyway, I'd like to keep the current behavior.
