### ISSUE TITLE
Luxon timezones not working on Firefox 45

### ISSUE THREAD

**Issue by doutatsu** [moment/luxon#256]
`DateTime.fromISO(date, { zone: zone })` is broken on Firefox 45 and possibly other versions. Latest Firefox is fine though. This code works just fine on Safari and Chrome.

As far as I can see, the only zone that works is `UTC`, everything else results in `unsupported zone` error on the `DateTime` object. To test this further I tried running `DateTime.local().zoneName` which returns `undefined`. So I am not sure what is getting broken in Luxon.

**Comment by icambron** [comment]
Yeah, what's broken here is Firefox's zone support. FF added support for zones in 51 and `formatToParts` in 52. I didn't break that out in the [support matrix](https://moment.github.io/luxon/docs/manual/matrix.html) because AFAIK, older versions of auto-updating browsers are rare in practice. If you really need to support it, see the polyfill instructions on that page.

**Comment by doutatsu** [comment]
Ah thanks @icambron, I should have realised it could be the reason!
