### ISSUE TITLE
Duration I/O via days:hh:mm:ss.ms

### ISSUE THREAD

**Issue by networkimprov** [moment/luxon#292]
The most human-writable/readable duration format is

`days[:hh[:mm[:ss[.ms]]]]`

Delimiters are locale-specific, and days & ms are arbitrary length (tho ms is limited in practice). Years and months are omitted, as they don't define a certain number of days.

To support that, I'd suggest adding...  
`Duration#toLocaleString()`  
`Duration.fromLocaleString(ls)` and maybe `Duration#setAll(ls)`

I need both now, so I suppose I'll .split() the input string and convert the items to numbers, sigh :-)

**Comment by icambron** [comment]
This feels more like a plugin than a Luxon feature. A few thoughts:

> days[:hh[:mm[:ss[.ms]]]]

Is there a standard somewhere about this format?

> Delimiters are locale-specific

Luxon can only do locale-aware things if the Intl API provides support for it.

> I suppose I'll .split() the input string and convert the items to numbers, sigh :-)

Somebody will have to do it

**Comment by networkimprov** [comment]
There is a de facto standard; see the digital clocks at timed sporting events. In EU the delimiters would be dot for colon and comma for dot (I believe). I'd be surprised if this wan't possible with the Intl api...

**Comment by icambron** [comment]
The Intl API doesn't have duration support at all. There's a proposal, but it's ways off from actually being in browsers.

The fix I would take here is an implementation of `Duration.fromFormat` that mirrors the datetime one, though we'd need to figure out how the optional pieces would be expected to work.

Here would be my implementation of your more narrow need. I like it more because it keeps the allocations of units, which shouldn't have to be normalized (e.g. 34 hours)

```js
Duration = window.luxon.Duration;
parse = (text) => {
  const regex = /^(\d+)(?::(\d+)(?::(\d+)(?::(?:(\d+)(?:\.(\d+))?)?)?)?)?$/;
  const result = text.match(regex);
  if (result) {
    const [days, hours, minutes, seconds, milliseconds] = result.slice(1).map(s => parseInt(s));
    return Duration.fromObject({
      days,
      hours,
      minutes,
      seconds,
      milliseconds
    });
  } else {
    return Duration.invalid("unparsable");
  }
}
```

```js
[
  "3",
  "3:12",
  "3:12:33",
  "3:12:33:12",
  "3:12:33:12.34"
].forEach(s => console.log(parse(s).toString()));
```

However, I don't think it should go in Luxon, for these reasons:

* it's easy to do in userland
* there's no standard for it, and I'm unconvinced about it being a de facto standard
* it can't be internationalized
* I'd rather support a generalized `fromFormat`

**Comment by networkimprov** [comment]
I don't see an issue for Duration.fromFormat() should I make one?

**Comment by networkimprov** [comment]
Re `/^(\d+)(?::(\d+)(?::(\d+)(?::(?:(\d+)(?:\.(\d+))?)?)?)?)?$/` my version allows decimal values in any position, and doesn't limit any position to its "normal" max.
