### ISSUE TITLE
Setting Locale Slowing Down The Application

### ISSUE THREAD

**Issue by YogendraChauhan** [moment/luxon#298]
**Settings.defaultLocale = 'en-GB'; Or 'hi'**

Setting default locale other than **'en-US'** slowing down the application. 

Please check the issue.

**Comment by icambron** [comment]
Yes, Luxon has to use the Intl APIs built into the browser when the locale is something other than en-US, and the Intl API is not very fast on some (all?) browsers, as well as on Node. So that is expected.

If you have a particular performance issue, I'd be happy to help figure out the root problem, but you'll need to create an example for me. Feel free to open other, more specific tickets with those details.
