### ISSUE TITLE
Full range of dates not supported for ISO strings

### ISSUE THREAD

**Issue by gampleman** [moment/luxon#299]
JS Dates are supposed to support dates from `-8640000000000000` to `8640000000000000` milliseconds. However, Luxon doesn't seem to support all operations in this range:

```
luxon.DateTime.fromMillis(8640000000000000)
>> DateTime {ts: 8640000000000000, zone: LocalZone, loc: Locale, invalid: null, weekData: null, …}
luxon.DateTime.fromMillis(8640000000000000).toString()
>> "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+01:00"
luxon.DateTime.fromMillis(8640000000000000).toISO()
>> "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+01:00"
luxon.DateTime.fromMillis(8640000000000000).toLocaleString()
>>  "9/13/275760"
luxon.DateTime.fromMillis(8640000000000000).toJSDate()
>> Sat Sep 13 275760 01:00:00 GMT+0100 (BST)
```

Doing some binary searching, it seems that the maximum range that is safe for string formatting is `253402300799999` (which corresponds to `9999-12-31T23:59:59.999+00:00`, so at a guess the issue may well be with having more than 4 year digits).

(Also exposing constants with the max and min available dates would be helpful especially for use in `reduce` functions).

**Comment by icambron** [comment]
I didn't get quite the same results:

```js
DateTime.fromMillis(8640000000000000).toISO()
'275760-09-12T20:00:00.000-04:00'
> DateTime.fromMillis(-8640000000000000).toISO()
'0NaN-NaN-NaNTNaN:NaN:NaN.NaN-04:56'
DateTime.fromMillis(-8640000000000000).offset
-296
> DateTime.fromMillis(-8640000000000000 + 296 * 60 * 1000).toISO()
'-271821-04-20T00:00:00.000-04:56'
```

I looked into this and figured out what was happening. It's a little gross. Basically, internally, Luxon keeps track of a sort of shadow time, an instance of a JS Date object that has the same year, month, day, etc as the time we want, except in UTC. This turns out to make a lot of computations easier and avoids lots of painful time zone issues, and also is what supplies accessors and formatters their calendar data. But to do this, Luxon has to add the offset to the real timestamp and create a new Date object out of the result, which in these extreme cases overflows the date. For example, in my case, it thinks my offset at -8640000000000000 is -296 minutes (I'm not sure why it's not -300, but an issue for another day), and when it tacks on that number of minutes to the highly negative timestamp, we get an invalid date because that result *is* out of bounds. In the positive direction, it's no issue because my offset removes time. People on the other side of UTC would have that all in reverse, with a broken +8640000000000000 and a working -8640000000000000. Thus the min and max dates that work depend on your timezone, but we could create constants that buffer the native min and max by 24 hours and be safe.

I think that just is what it is, but it doesn't explain why you're getting such extremely different results. I'd like to know more about how you tested this and got such massively lower numbers.

**Comment by icambron** [comment]
As of 1.18.1 (and specifically #576), this at least tells you the time is invalid. We still don't support that full range, but that's probably the best we'll do in terms of actually fixing those.

I'd like to expose some constants, but I've recently found a lot of wildly big offsets, which could definitely blow past any min or max numbers I set and still end up invalid. I think I'd still take a PR setting `DateTime.MAX_MILLIS` and `DateTime.MIN_MILLIS` as, like `-8640000000000000 + 24 * 60 * 60 * 1000`
