### ISSUE TITLE
More information in error messages

### ISSUE THREAD

**Issue by tzachshabtay** [moment/luxon#304]
I'm setting `Settings.throwOnInvalid = true;` so the exceptions will not be swallowed (just an opinion here, btw, but I think this should have been the default, would have saved me a lot of time), but those exceptions are missing the argument that caused the exception in the first place.

For example, I'm seeing this error:
"Error: Invalid DateTime: unparsable"

But I'd like to see this error:
"Error: Invalid DateTime (Jun 32, 1909): unparsable"

**Comment by icambron** [comment]
Yeah, the errors could be better.

**Comment by icambron** [comment]
I poked around at this. The way we do this is simply to throw the `invalidReason`. I think my initial thought was to make it so that you can programmatically check the `invalidReason`. That makes me want to put error-specific info in a separate field and then provide both to the throw. Now it's a little complicated, but probably still worth it.

**Comment by icambron** [comment]
This is done in #360. For example:

```js
DateTime.fromFormat("fasdf", "y").invalidExplanation
//=> 'the input "fasdf" can\'t be parsed as format y'

Settings.throwOnInvalid = true;

DateTime.fromFormat("fasdf", "y")
//=> Error: Invalid DateTime: unparsable: the input "fasdf" can't be parsed as format y
```

Will be in 1.5.0
