### ISSUE TITLE
shiftTo with negative Duration gives weird results

### ISSUE THREAD

**Issue by benneq** [moment/luxon#305]
```
const duration = Duration.fromMillis(-1000)
    .shiftTo('years', 'months', 'days', 'hours', 'minutes', 'seconds');

console.log(duration.years, duration.months, duration.days, duration.hours, duration.minutes, duration.seconds);
```

Output:
```
-1 12 4 23 59 59
```

Expected Output:
```
0 0 0 0 0 -1
```

**Comment by benneq** [comment]
Does `toFormat` internally use `shiftTo`?

Maybe it's possible to include a simple workaround in `shiftTo`. And later provide something more optimized. Something stupid simple like this:
```
shiftTo(...units) {
  if(this.isNegative()) {
    return negate().shiftTo(units).negate();
  }

  // .. rest of shiftTo code
}
```

BTW: The `isNegative()` method could be really useful. Maybe you want to add it to `Duration`?

**Comment by icambron** [comment]
There's an `isHighestOrderNegative()` helper. I agree we could make it public. I actually tried your solution when I wrote my first comment; it didn't work because `negate()` will just renormalize it back to the form we don't like

**Comment by benneq** [comment]
Negativity is really a strange thing within Durations. Maybe you've got to rethink the concept of it.

Here's what I mean:
```
{
  minutes: -5
  seconds: 1
}
```
Is this a valid Duration? Maybe(?!)
What's its actual value? (-5*60 - 1) = -299 seconds
Is it negative? yes
Highest order negative? yes

Now look at this:
```
{
  minutes: -1
  seconds: 65
}
```
Is this a valid Duration? Maybe(?!)
What's its actual value? (-1*60 + 65) = +5 seconds
Is it negative? no
Highest order negative? yes

I guess you need a clear specification at first for negative values. I'm not sure if it makes sense to allow a mix of positive and negative values. **I just want to provide some (maybe useful?) questions and hints:**

Does it make any sense to store `-1 minute +65 seconds`? I'm not sure.
Wouldn't it be more useful to never store negative values within the Duration object? Example:
`Duration.fromMillis(-1000)` becomes `{milliseconds: 1000, negative: true}`.

How about `Duration.ofObject` will not allow any negative values anymore. Example:
`Duration.fromObject({seconds: -1})` results in an error. Correct way to call it would be: `Duration.fromObject({seconds: 1, negative: true})` or something similar.

According to a moment issue ( https://github.com/moment/moment/issues/2408 ) the ISO format allows a mix of positive and negative values. But it also provides a global negativity sign: `"-P6H3M" -- parses as "-6 hours and -3 minutes"`

------

BTW: Strange. I used this code and it seems to work:
```
duration = Duration.fromMillis(-3605000)
    .shiftTo('days', 'hours', 'minutes', 'seconds');

console.log(duration.days, duration.hours, duration.minutes, duration.seconds);
// => -1 22 59 55

duration = Duration.fromMillis(-3605000).negate()
    .shiftTo('days', 'hours', 'minutes', 'seconds').negate();

console.log(duration.days, duration.hours, duration.minutes, duration.seconds);
// => 0 -1 0 -5
```
Don't know why it shouldn't be possible to call the same methods within `shiftTo`.

**Comment by colinhemphill** [comment]
Yeah, negative durations are acting very oddly. I'm doing a countdown timer using `.minus(1000)`, and  getting some unexpected results when the timer goes below 0. At 1 second under 0, logs show:

`
values: {
  hours: 0,
  milliseconds: -6000,
  minutes: 0,
  seconds: 5
}
`

But `toFormat('mm:ss)` comes out as "-1.59". If I run normalize on the same duration, it shows:

`
values: {
  hours: -1,
  milliseconds: 0,
  minutes: 59,
  seconds: 59
}
`

Am I doing something terribly wrong, or is this a bug?

**Comment by icambron** [comment]
@benneq Finally got a chance to read this through. Some thoughts:

 * rejecting mixed values is tempting but it would come with a lot of headaches, since you can add or subtract durations. One thing I don't want to do is to automatically convert durations to have matching units when doing multi-duration operations. That pretty much requires me to support mixed negative and positive durations
 * In general, Luxon should only convert between units when explicitly asked to. "Is this overall negative?" requires that. Your example with millis is easy, but `{ days: 30, months: -1 }` requires a conversion to even decide that
 * I agree that just checking the highest-order unit leads so some unhelpful behavior. I think I need to fix this in the interface somehow. I'll give it some thought

**Comment by icambron** [comment]
@colinhemphill Yes, that appears to be the same issue. When Luxon converts to minutes and seconds it decides to use -1 minute + 59 seconds, when it should have just said -1 second

**Comment by icambron** [comment]
OK, I went pretty deep on this and I think it's all working as I expect it to. See 1c9403c, which I haven't released yet.

First, mixed units like in the examples above work much better:

```js
> Duration.fromMillis(-1000).shiftTo('years', 'months', 'days', 'hours', 'minutes', 'seconds').toObject()
{ years: 0, months: 0, days: 0, hours: 0, minutes: 0, seconds: -1 }
> Duration.fromObject({ hours: 0, milliseconds: -6000, minutes: 0, seconds: 5 }).normalize().toObject()
{ hours: 0, milliseconds: 0, minutes: 0, seconds: -1 }
```

Second, I added support for ISO-8601 with mixed units. The spec doesn't include them, but if you don't want to produce mix-units ISO outputs, don't.

Third, there is no logic at all about the sign of the highest order unit. It's all baked into the way the units cascade.

I just released a bunch of other changes, so I'm going to let this one sit for a few days. I'll put it in 1.6.0.

**Comment by icambron** [comment]
1.6.0 is out

**Comment by benneq** [comment]
Thank you :) I'll give it a try in the next days. So far it looks pretty good.

BTW: I just checked how the Java JDK's "java.time" handles this, because it took years for them to finally include a good working DateTime library. And the main developer of `java.time` had years of experients with "Joda-Time" (the Java equivalent to moment.js). So it should be well-thought-out (?)

First: They split durations into TWO different concepts: "Duration" and "Period":
 - "Duration" is a "time-based amount of time". (days, hours, minutes, seconds, millis, nanos)
 - "Period" is a "date-based amount of time". (years, months, weeks, days)
This way the "Duration" part doesn't suffer the `+1 month -30 days` problem, I guess.

But it also has some disadvantages:
- "Duration" internally consists of 2 values: `long seconds` (can be negative) and `int nanos` (always positive). So you can't have `-1 minute +61 seconds`, because it will simply be stored as "1 second".
- "Period" internally stores `int years`, `int months` and `int days` (all can be negative).

They don't handle 23h / 25h days (daylight saving time) within "Duration" nor weeks within "Period":
- When you create a `Duration.ofDays(1)` it's simply stored as `86400 seconds`.
- When you create a `Period.ofWeeks(2)` it's simply stored as `14 days`.

`toString()` (as to be expected) isn't equal to your input:
- "Duration" always only outputs the part behind the `T` of the ISO String, e.g. `PT24H`
- "Period" always only outputs the part before the `T`, e.g. `P1Y-1M1D`

Then I checked the source of the `isNegative()` methods of both classes:
- "Duration" uses `return seconds < 0`. This is completely clear.
- "Period" uses `return years < 0 || months < 0 || days < 0`. **This is weird.** When I have `+1 year -1 day` it's negative.
I guess they had a similar problem as Luxon and this was the best solution they came up with.

**Comment by icambron** [comment]
@beneq In a sense, Luxon has those two concepts too, just mixed into a single object that tries to do the right things with the right fields. Days are a calendar field and hours are a time field, etc. The trade-off is that we need the same interface for both.

I honestly think the Luxon API is smoother (just one type, and put your units in it), more consistent and explicit (keep all the units intact by default because they communicate intent), and it's certainly more flexible (e.g. conversionAccuracy options). We lose some niceities available to Java's Duration that are available to it because it's restricted to time fields and thus has less intent is baked in (e.g. less wrong to reduce `{minutes: 1, seconds: -61}` to `{seconds: -1}` than the equivalent with months and days). I think that's well worth it.

On the specific question of negativity, I've concluded three things:

 * `isNegative` is not a thing we should have. Like you said, the Period behavior for that is whack. I've removed all attempts to assign signs to durations. If you want to know, you have to covert to a single unit (as simple as `+dur`) where it's unambiguous and check its sign
 * `negate()` negating all the units is clearly correct. I can't find a case where it doesn't behave as expected, even with very odd mixed units.
 * Getting the normalization and shiftTo behavior to match human intuitions on mixed units is tricky but unambiguous, and I think I've got them right in Luxon now. I don't know if any other libraries get this right.

**Comment by icambron** [comment]
There are bunch of use cases for both the `conversionAccuracy` modes, but yes, it will never be precise in the sense you need here. You could also do what you did here with a combination of `DateTime#plus` and `DateTime#diff`
