### ISSUE TITLE
Expose Formatter class or something similar for performance

### ISSUE THREAD

**Issue by hulbert** [moment/luxon#307]
Hi there 👋 , excited to see this project's direction! We've been using moment heavily for over three years in a Node.js codebase so are taking a close look at Luxon.

In the past, we've had to rewrite really hot codepaths to avoid using moment#format [0]. 

From what I understand, the main reason `moment#format` is not terribly fast is because the formatting string is parsed each time the method called. I see that Luxon's `DateTime#toFormat` internally uses a Formatter class, but there does not seem to be a publicly exposed or documented way to do this. As such, `DateTime#toFormat` would likely suffer from the challenges of `Moment#format`.

To address this, it'd be lovely if the Formatter class, or a simplified version, were made public so that performance sensitive code can have the parsing done once instead of repeatedly.

(We may be able to contribute this but would ask for guidance of the API design.)

---

[0]: Example of a profiled, faster `momentInTime.format('HH:mm')` where `momentInTime` is a `moment` object:

```js
function format(momentInTime) {
   return padTime(momentInTime.hour()) + ':' + padTime(momentInTime.minute())
}
    
function padTime(number) {
    return _.padStart(number, 2, '0')
}
```

**Comment by icambron** [comment]
The Formatter doesn't quite work like that. The Formatter itself only represents the formatting options, not the result of the parse, so being able to plug it in directly to `toFormat` wouldn't help. I think you want something closer to the result of `Formatter.parseFormat`, which is an array of little objects representing each token. Instead of exposing Formatter (which would massively increase the API surface area of Luxon), the solution would be something like:

 1. Add a method to DateTime called `parseFormat` that returns a `ParsedFormat` object, which is a simple wrapper around what `Formatter.parseFormat` returns.
 1. Allow `toFormat` to accept that object as the format

I'd be willing to accept those changes if you can show that the parsing really does take a big fraction of the time, at least for English and the default calendar (I *know* it's not the slowest part of Intl formatting; the Intl system holds that honor).

**Comment by icambron** [comment]
I tried out my suggestion above, just to see how it would work. It's about 10% faster when using a preparsed token, as amortized over hundreds of thousands of `toFormat` calls:

```
DateTime#toFormat x 258,840 ops/sec ±0.47% (93 runs sampled)
DateTime#toFormat with preparse x 283,440 ops/sec ±2.25% (94 runs sampled)
```

You can see the experiment here: https://github.com/moment/luxon/tree/try-preparsed-format. It would need a bit more work before it would be ready to merge, but 10% is a small enough improvement that I don't think it's worth pursuing further.
