### ISSUE TITLE
DateTime.max supports only args instead of an array

### ISSUE THREAD

**Issue by oleg-koval** [moment/luxon#324]
Currently `DateTime.max` doesnt accept an array with `dateTimes`, I just wonder why? And if array of `dateTimes` is provided it just returns it back.

spec:

```javascript
test('DateTime.max returns the only dateTime if solo', () => {
  const m = DateTime.max(DateTime.fromJSDate(new Date(1982, 5, 25)));
  expect(m).toBeTruthy();
  expect(m.valueOf()).toBe(DateTime.fromJSDate(new Date(1982, 5, 25)).valueOf());
});

test('DateTime.max returns the max dateTime', () => {
  const m = DateTime.max(
    DateTime.fromJSDate(new Date(1982, 5, 25)),
    DateTime.fromJSDate(new Date(1982, 3, 25)),
    DateTime.fromJSDate(new Date(1982, 3, 26))
  );
  expect(m.valueOf()).toBe(DateTime.fromJSDate(new Date(1982, 5, 25)).valueOf());
});

test('DateTime.max returns undefined if no argument', () => {
  const m = DateTime.max();
  expect(m).toBeUndefined();
});

test('DateTime.max is stable', () => {
  const m = DateTime.max(
    DateTime.fromJSDate(new Date(1982, 2, 25)),
    DateTime.fromJSDate(new Date(1982, 3, 25)).reconfigure({ locale: 'en-GB' }),
    DateTime.fromJSDate(new Date(1982, 3, 25)).reconfigure({ locale: 'en-US' })
  );
  expect(m.locale).toBe('en-GB');
});
```

So if you have an array with `dateTimes` you need to do:

```javascript
DateTime.max(...dateTimesArray)
```

Which is completely ok, but should not be just an array supported as well / instead?

**Comment by icambron** [comment]
@oleg-koval I did it that way because I suspect most callers are more like `DateTime.max(myOneTime, myOtherTime)` than `DateTime.max(myArrayOfTimes)` and I didn't want to make everyone add brackets, so I made the (presumably rarer) array callers add dots instead. I can see why someone would disagree with that choice

**Comment by oleg-koval** [comment]
@icambron yeah I see your point, it definitely has more pros than cons, that's why I've closed this issue

**Comment by jhnns** [comment]
`Math.max()` and `Math.min()` have a similar signature but I think an array would have been a better choice. The function call may fail because of a max stack size exceeded error when you pass a large number of date times (which I think is not total unlikely).

The maximum number of arguments depends on the JS engine, see https://stackoverflow.com/a/24595052
  Browser | apply() | literal
 ------|--------|------------
Chrome 35  | 126213  |  65535
Firefox 30 | 500001  |  65535
Safari 7   |  65537  | 522159
