### ISSUE TITLE
[FEATURE] allow negative interval?

### ISSUE THREAD

**Issue by zypA13510** [moment/luxon#326]
Currently, specifying an `end` before `start` would result in an invalid `Interval` because of "invalid endpoints". I'm not sure why is it like this in the first place, but please consider if we can allow negative interval. I have a function like this:
```js
const EPOCH = DateTime.fromMillis(0) // 1970-01-01T00:00:00.000Z
/**
 * Calculate difference in `myDate` and `EPOCH` in months
 * @function
 * @param {Date} myDate
 * @return {number} The number of calendar month between `myDate` and `EPOCH`
 */
const myFunction = (myDate) => {
  let dateTime = DateTime.fromJSDate(myDate)
  let diff = Interval.fromDateTimes(EPOCH, dateTime)
  let totalMonthsFromEpoch = Math.floor(diff.length('months')) // Should return -1 for 1969-12-31
  return totalMonthsFromEpoch
}
```
It would fail and output `NaN` if given a date before the `EPOCH` constant. And since `Duration` allows it, I don't quite see why it is not allowed on `Interval`.

**Comment by icambron** [comment]
See #145 for a discussion of this. TLDR: the idea of an interval that runs backwards makes sense, but it would be a lot of work to break Interval's assumption that time moves forward.

Like one of the commenters in #145, at least some of the problem here is that what you really wanted was a duration all along:

```js
var EPOCH = DateTime.fromMillis(0);
var durationInMonths =   DateTime.local().diff(EPOCH, 'months'); // returns a duration
durationInMonths.months //=> 584.7820525421894

DateTime.local(1969, 3, 1).diff(EPOCH, 'months').months //=> -9.993279569892474
```

I know there's some [documentation](https://moment.github.io/luxon/docs/manual/math.html#losing-information) suggesting you can use Intervals as a sort of late-binding duration (i.e. meaning you don't have to decide you want months when you set it up) and it's true that not having negative intervals makes that hard in some scenarios. But I feel like the workaround is adequate, and in your case, you don't need the late-binding behavior anyway.

Making intervals be able to be truly negative (meaning, for example, they iterate backwards) would be a lot of work, and we're unlikely to support them anytime soon. Much more likely, we'll just change the factory methods to flip the inputs if they're put in backwards, which if anything is a step in the opposite direction.

**Comment by zypA13510** [comment]
Sorry, I must have missed that duplicate somehow.

But no, duration would not work in my situation: 1970-03-01 - 1970-01-01 should equals 2.0 months (strictly follow the calendar) in my requirement, and 1969-12-01 - 1970-01-01 = -1 month. This is not possible with duration, whatever conversion algorithm I choose.

Of course, I can set up an if block guarding the interval creation, and return negative if end<begin -actually I have done this already - but then I figured that this should probably be included in the library, that's why I opened this issue. Judging from your reply, the main issue seems to be implementation difficulty. So if anyone is willing to open a PR, it would be welcomed, right? Maybe you should add a "pull-request welcome" tag instead of "need thought" on #145 then.

**Comment by icambron** [comment]
With durations:

```js
var first = DateTime.fromISO("1969-12-01");
var second = DateTime.fromISO("1970-01-01");
first.diff(second, "months").months; //=> -1

var third = DateTime.fromISO("1970-03-01");
first.diff(third, "months").months; //=> 3, not sure why you want 2
```

I think you might be getting tripped up on this: epoch is 1970-01-01 at midnight **UTC**, whereas by default the datetimes you create with, say, `fromISO` are in your local timezone. That's why it's not exactly the round number of months like in my example above; Luxon takes your `fromMillis(0)` very literally. You can resolve that a few different ways, depending on your requirements, but the most obvious is to construct the "target" date in UTC, like, e.g. `DateTime.fromISO("1969-12-01", { zone: UTC })` or just `DateTime.fromISO("1969-12-01T00:00:00Z")`. This all comes from the fact that Luxon tracks DateTimes, not just Dates.

**Comment by zypA13510** [comment]
@icambron Ok, nevermind. I figured out the problem is not with duration, but with longterm duration. Even if the unit is set to month at `diff()` call, it would return based on another unit (milliseconds I guess?) and convert back to months, thus completely ignores calendar month. I was fooled to assume the only difference between casual and longterm is the conversion rate.
