### ISSUE TITLE
Minified version on site is broken

### ISSUE THREAD

**Issue by punkman** [moment/luxon#357]
Minified file linked on the site in the section "Download - Browser global" is broken, Debug version is fine.

I think the version is, 1.4.4, the last one.
With debug version I get a regular DateTime string with min version I see 'shortTshort'.

If needed here a JSFiddle to test it: https://jsfiddle.net/gsey7hdu/

Probably I'm one of the last guys around not using a packet manager/preprocessor :)
Thanks

**Comment by icambron** [comment]
Yikes, that is not good.

**Comment by icambron** [comment]
Seems to be some sort of issue in the minifier. I have no idea how to even investigate it, though. I think I'll try some experiments with using the minifier directly, but I'm kinda shooting in the dark.

**Comment by icambron** [comment]
I fixed this by uglifying the file directly instead of using the Rollup plugin. This isn't a great solution and I really need to fix the root issue, but I'm not sure how to tackle that, and the quick fix sure beats having a broken build.

In the meantime, issues include:

* Does the scriptmap work as expected?
* The file is a little bigger
