### ISSUE TITLE
Forced rezoning, regardless of the local time

### ISSUE THREAD

**Issue by dandv** [moment/luxon#375]
I need to do something dirty because much like [our ancestors](https://moment.github.io/luxon/docs/manual/zones.html#dst-weirdness), the creators of Excel appear to have been morons about timezone, and [Excel has no native concept of universal time](https://docs.sheetjs.com/#dates). Apparently, [Librecalc isn't any better](https://bugs.documentfoundation.org/show_bug.cgi?id=121781).

What I need to do is force a particular timezone into a JS Date object, and account for DST. Imagine I need to write JS Date timestamps into a spreadsheet as times in the Beijing time zone, which doesn't observe DST. I can't simply use `plus`, and using `setZone` with `keepLocalTime: true` will make the output date dependent on the timezone the script is run in, which is incorrect.

What is the recommended way to do this? The best I came up with was to re-parse the date from its ISO representation:

```js
// muck up the time zone the opposite way; Beijing is UTC+8, not -8
DateTime.fromISO(timestamp.toISOString().replace('Z', ''), { zone: 'UTC-8' }).toJSDate();
```

BTW, shouldn't specifying the `zone` option override the 'Z' in the ISO string? I've found that I had to remove it, or else the `zone` option is ignored.

**Comment by icambron** [comment]
I am a bit confused about what you're trying to do. You want to produce JS date objects that, when asked for their local time in a non-China env, gives the intended China local time?

If so, `keepLocalTime` is exactly what you want. It means "change the underlying time such that the local time stays the same, not the universal time". So like:

```js
dt.toUTC().setZone("UTC+8", { keepLocalTime: true }).toJSDate()
```

The resulting JS date doesn't know it's in UTC-8; it's just a wrapper for a timestamp. We've just messed with the timestamp to make its local time right. Per your objection: the "local" refers to the local time of DateTime object, not the system (I wish I'd called `DateTime.local` `DateTime.system()` instead to disambiguate that). The `toUTC()` above is making sure the instance's idea of what that local time is matches your intentions. You can see it in action:

```js
var dt = DateTime.local()
dt.toUTC().toISO() //=> "2018-12-02T01:53:38.412Z" (it's currently almost 2am in UTC)
dt.toUTC().setZone("UTC+8", { keepLocalTime: true }) //=> "2018-12-02T01:53:38.412+08:00" (same local time, different timestamp)
```

(Ironically, your proposed solution *is* dependent on the zone your code runs in, since it will only be "Z" in a UTC env).

> BTW, shouldn't specifying the zone option override the 'Z' in the ISO string? 

No, "Z" really specifically means "this time is expressed in UTC", so setting the zone on the parse won't override that. That `zone` argument sets the default zone (e.g. if the string doesn't say, which in this case it does) and the zone on the object created.

I hope that helps!

**Comment by dandv** [comment]
To clarify, I was looking for the equivalent to date-fn's [utcToZonedTime](https://www.npmjs.com/package/date-fns-tz#utctozonedtime).

**Comment by icambron** [comment]
That is just `setZone` in Luxon

**Comment by richardoSGSI** [comment]
@dandv 
> To clarify, I was looking for the equivalent to date-fn's [utcToZonedTime](https://www.npmjs.com/package/date-fns-tz#utctozonedtime).

thanks for sharing this. this is exactly what i need, too

**Comment by dlandtaa** [comment]
It's possible but it's kind of nuanced. You have to use `toUTC()` along with `setZone()` with the `keepLocalTime: true` option.

Despite the name, I don't think using `keepLocalTime` is affected by time zone in which the script is run. I think it's just saying it will change the time zone without changing the time (which ironically, is actually resulting in a different time). Anyway, I am in `America/Chicago` and this works fine for me:

```
const dt = DateTime.fromISO('2024-02-10T01:01:01.000Z');
console.log(dt.toUTC().toISO()); // '2024-02-10T01:01:01.000Z'
const dt2 = dt.toUTC().setZone('Asia/Shanghai', { keepLocalTime: true });
console.log(dt2.toISO()); // '2024-02-10T01:01:01.000+08:00'
```
