### ISSUE TITLE
Where is the description for fromFormat?

### ISSUE THREAD

**Issue by dandv** [moment/luxon#382]
At https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromFormat, we have

> the format the string is expected to be in (see description)

Can the page clarify where the description is?

**Comment by icambron** [comment]
I think what happened there is that the format strings used to be in the method description just above, but I moved them and didn't update the parameter documentation. Instead of saying "see description", it should link to [here](https://moment.github.io/luxon/docs/manual/parsing.html#table-of-tokens). Ideally, they *would* be right in the method documentation, but the formatting options are limited in ESDoc.

**Comment by SankarshanDudhate** [comment]
I'll fix this one

**Comment by icambron** [comment]
Fixed in a68acf9
