### ISSUE TITLE
Expose original creation input

### ISSUE THREAD

**Issue by kamranayub** [moment/luxon#405]
Have some existing moment code like this:

```js
if (!date.isValid()) {
	const { input } = date.creationData;

    // manually attempt to try different format parsing
}
```

But I am not seeing an equivalent way to get at the original string provided to `DateTime` instance to achieve the same thing in Luxon. Any ideas?

**Comment by icambron** [comment]
Yeah, Luxon doesn't have this feature. There are a couple challenges:

 * you can create DateTimes from other DateTimes. It makes it confusing to keep creation information passed through the chain. This was a serious headache in Moment, and its even worse with Luxon where every operation creates a new instance
 * unlike Moment, in Luxon there are a lot of different methods for creating DateTime instances from strings and these would each need to support it and then provide metadata on which of those methods created it

One thought is that you might want to move your parsing stuff all to the same place, so that you have the original string right there. I understand that IRL apps can be complicated for all sorts of reasons, but from the outside, it's a bit weird that some part of the application would be parse the DateTime, then pass it around, where some other part picks it up, examines it, and reparses it if it's invalid.

I would strongly prefer not to add this feature to Luxon, and I'd have to be convinced it justifies the complexity it would add.

**Comment by kamranayub** [comment]
That makes sense, I think it should be doable to pass the original input!
Since Moment had that info, we didn't pass it but this code lives in a
React component so it should definitely be able to get at the string value
to pass it in. Thanks for the explanation!
