### ISSUE TITLE
Add `is{Before,After}(DateTime, Unit)`

### ISSUE THREAD

**Issue by RichiCoder1** [moment/luxon#433]
I ran into this while converting another library.

Luxon doesn't have `isBefore(DateTime, Unit)` or `isAfter(DateTime, Unit)`. These looks easy enough to port (https://github.com/moment/moment/blob/develop/src/lib/moment/compare.js#L5), so I was wondering ya'll be willing to take a contribution or add this?

**Comment by icambron** [comment]
You can use `<` and `>`. See https://moment.github.io/luxon/docs/manual/math.html#comparing-datetimes

**Comment by RichiCoder1** [comment]
That doesn't cover comparing with units and the logic for doing so is just complicated enough that I thought it worth asking, or at least documenting.

**Comment by icambron** [comment]
Perhaps we need some better docs there, sure. The unit thing is just this:

```js
dt1.startOf("hour") < dt2.startOf("hour")
```

I mention that in the Moment comparison docs, but not in the math docs, and I think that would be a useful clarification.

Which IMO is clearer than having a second argument that someone reading it has to understand. Moment can't do that because `startOf` mutates, which makes it more awkward to use in situations like this.

**Comment by RichiCoder1** [comment]
Yup! I'd be willing to make that doc contribution if you'd like.
