### ISSUE TITLE
Locale-relevant named zones?

### ISSUE THREAD

**Issue by allquixotic** [moment/luxon#447]
`luxon.DateTime.fromISO("2019-02-17T15:34:28.922-05:00", {setZone: true}).setLocale('en-us').toFormat("f ZZZZ");` returns `02/17/19, 3:34 PM UTC-5`.

I would like to have it display the named zone "EST" (Eastern Standard Time), because "EST" is the time zone that the users will associate with this particular timestamp in this locale. Is there a better way to do this?

I realize it can't always be 100% accurate, as the timezone displayed may not match the user's expectation, but `UTC+-(offset)` is less desirable for my users because it requires some effort to recognize which time zone is referred to.

For the most part, the only time zones I'll be dealing with are Alaskan, Pacific, Mountain, Central and Eastern in the US. I'm OK if it falls back to UTC+offset for times outside of those, but I really need it to say PST or PDT, CST or CDT, etc. for the North American timezones depending on which offset was supplied.

I can definitely recognize how this would be terrifically annoying to parse from Luxon's end, because for example, both EST and CDT are UTC-5. But if the date supplied lies within a span of time when the Eastern Time is in EST, then it should display EST; if the date lies within a span of time when the US is in daylight time, it should display CDT. 

Obviously this could not be used if only a time is supplied with no date component (unless you want to assume "the present date per the system clock" for the date) and that's fine. I just need to parse ISO times and spit out a short time string with US-friendly named zones.

I read [zones.md](https://github.com/moment/luxon/blob/master/docs/zones.md) which makes me reailze that doing this correctly for all possible time instants and all possible timezones is impossible if all you have for input is a UTC offset, like in an ISO timestamp. On the other hand, however, I consider it part of the "localization information" of the `en-us` locale that `2019-02-17T15:34:28.922-05:00` is in the **EST** (Eastern Standard Time) timezone, and it can be deterministically resolved as such based on the fact that this time instant occurs within a span of time when the United States' DST calendar is within Standard Time.

If there's already a way to do this with Luxon, please share the code or relevant part of the docs. If not, consider this a feature request.

**Comment by icambron** [comment]
This isn't something Luxon can do:

 1. It would require maintaining a mapping of locale and offset combinations to time zones. Luxon doesn't do that kind of thing, and it's not going to just do it for the US.
 2. It would involve making some incorrect assumptions, e.g. the parts of the US that don't have a DST and would get miszoned. This might not matter for your application, but Luxon itself can't make assumptions like that.
 3. It just isn't really true that if I pick en-US as my locale that I am necessarily in the United States, so this would require some kind of extra option or something. That's getting a little complicated.
 4. Luxon doesn't actually know the DST rules, so it wouldn't know whether which zone to pick -- is it `-6` because it's CST or MDT? It would have to try them both and find out which one's offset matched. That's not a deal breaker but it makes the solution uglier.

But mostly the problem is item 1 and the other problems are just window dressing. Fortunately, it's pretty easy for your application to do, because you only need to maintain the small subset of zones you need, as opposed to Luxon, which would need all of them. Something like this:

```js
function assumeUS(isoString) {

  const zonePossibilities = {
    "-240": ["America/New_York"],
    "-300": ["America/Chicago", "America/New_York"],
    "-360": ["America/Boise", "America/Chicago"],
    "-420": ["America/Los_Angeles", "America/Boise"],
    "-480": ["America/Anchorage", "America/Los_Angeles"],
    "-540": ["America/Anchorage"]
  }

  const basic = DateTime.fromISO(isoString, { setZone: true });
  const pos = zonePossibilities[basic.offset.toString()];

  if (pos) {
    for (zone of pos) {
      const zoned = basic.setZone(zone);
      if (basic.offset === zoned.offset) return zoned;
    }
  }
  return basic;
}

[
  "2019-02-17T15:34:28.922-05:00",
  "2019-02-17T15:34:28.922-06:00",
  "2019-02-17T15:34:28.922-07:00",
  "2019-02-17T15:34:28.922-08:00",
  "2019-02-17T15:34:28.922-09:00",
  "2019-06-17T15:34:28.922-04:00",
  "2019-06-17T15:34:28.922-05:00",
  "2019-06-17T15:34:28.922-06:00",
  "2019-06-17T15:34:28.922-07:00",
  "2019-06-17T15:34:28.922-08:00"
].map(s => {
  const r = assumeUS(s).toFormat("f ZZZZ");
  console.log(r);
});
```

**Comment by mj1856** [comment]
Also, consider `2019-11-03T01:00:00-05:00`.  Is that `EST` or `CDT`?

It's both, actually.  Simultaneously.

https://www.timeanddate.com/worldclock/converter.html?iso=20191103T060000&p1=179&p2=64

**Comment by icambron** [comment]
Ah, good point, @mj1856. I hadn't thought of that one

**Comment by Kilowhisky** [comment]
FYI, there are plenty of libraries that support doing this as long as you have some positional coordinates. 

Since this is a common thing, maybe putting some helpful libraries in the docs may be helpful. 

https://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates

I found this one particularly helpful. 

https://github.com/mapbox/timespace
