### ISSUE TITLE
Comparing DateTimes with different timezones

### ISSUE THREAD

**Issue by Hisagr** [moment/luxon#471]
I haven't been able to find a way to compare 2 DateTimes with different time zones using `diff()`.

Here's what I tried: 

```
const now = DateTime.local().setZone('America/Toronto');
const moscow = DateTime.local().setZone('Europe/Moscow');
const diff = moscow.diff(now,'minutes'); 
// produces { minutes: 0.00008333333333333333 }
// when it should be 7 hours
```
Does `diff()` ignores the time zone? What's the workaround for this? 

Update: Ok, I figured why this happens  [here](https://moment.github.io/luxon/docs/manual/zones.html#setzone), but the question still remains. Any help would be highly appreciated.

**Comment by icambron** [comment]
Right, now is now no matter what time zone you're in. If you want to compare the offsets, you can do

```js
d.setZone("America/Toronto").offset - d.setZone(”Europe/Moscow").offset
```

**Comment by justanotheranonymoususer** [comment]
Can you elaborate regarding a workaround? I'm trying to port code from Moment to Luxon, and it's pure luck that I caught this issue before publishing it. My code looks similar to (simplified):

```javascript
const now = DateTime.now().setZone('America/New_York');
const date1 = now.set({ day: 1 });
const duration = date1.diff(now, ['days', 'hours']).toObject();
```

In Moment, I got the correct amount of hours, even if `date1` got a new timezone because of daylight saving. How do I implement it correctly in Luxon? Luxon saved me some typing and I got better and safer code with immutable objects, but it's not worth it if the most sensitive part, the time handling, is not solid. Appreciate your help.

**Comment by justanotheranonymoususer** [comment]
I did the following and in my quick test it works:

```javascript
const duration = date1.toUTC().diff(now.toUTC(), ['days', 'hours']).toObject();
```

It would be great if you could confirm that it's correct in all cases.

**Comment by justanotheranonymoususer** [comment]
Actually, after more testing, I understand that it's probably by design. If I run `diff` with only `hours`, it returns the correct value. But if I add `days`, it tries to return a user friendly calculation where a day is not necessarily just 24 hours. So in my case I can just get the hours and divide them by 24 manually.
