### ISSUE TITLE
shiftTo + normalize is not always correct

### ISSUE THREAD

**Issue by ycmjason** [moment/luxon#512]
Please see the following code:

```js
const dayToMs = day => day * 24 * 60 * 60 * 1000

luxon.Duration.fromMillis(dayToMs(365))
  .shiftTo('years', 'months', 'days', 'hours', 'minutes', 'seconds', 'milliseconds', 'weeks')
  .normalize()
  .toObject() // { years: 1, ..., days: 0 } <--- correct

luxon.Duration.fromMillis(dayToMs(364))
  .shiftTo('years', 'months', 'days', 'hours', 'minutes', 'seconds', 'milliseconds', 'weeks')
  .normalize()
  .toObject() // { years: 1, ..., days: 4 } <--- incorrect?
```

I believe this to be a bug. 364 days should translates to 0 years 11 months 30 or 29 or 28 or 27 days instead?

**Comment by icambron** [comment]
Yeah, weird

**Comment by icambron** [comment]
After thinking about this, I realized this isn't really a bug. It's more a consequence of units not being mutually consistent. In Luxon's "casual" units mode, 365 days is a year, 12 months is a year, and a month is 30 days, but note that 12 * 30 = 360, not 365. So `shiftTo` converts 364 days to 0 years, 12 months (the first 360 days), and 4 days (the leftover days). `normalize` says "ooh ooh, I know! 12 months is a year!" The problem is that each step loses the context of the previous step. Durations are dumb piles of units; they don't "know" you started with something that looks like an almost-year.

There is a solution, though. You just have to sacrifice the convenient-but-not-actually-true conventions for how long each unit is. Luxon supports this:

```js
> Duration.fromObject({ days: 364, conversionAccuracy: "longterm" }).shiftTo('years', 'months', 'days', 'hours', 'minutes', 'seconds', 'milliseconds', 'weeks').normalize().toObject()
{ years: 0,
  months: 11,
  weeks: 4,
  days: 1,
  hours: 4,
  minutes: 39,
  seconds: 53,
  milliseconds: 999.9999982319423 }
```

Those numbers look dumb, which is why they're not the default, but they result in consistent behavior across multiple conversions. I encourage you to read this section of the docs: https://moment.github.io/luxon/docs/manual/math.html#duration-math
