### ISSUE TITLE
How to replace literals of dateformat?

### ISSUE THREAD

**Issue by berrynana** [moment/luxon#523]
current default literals are '/'. but our system need to '-' literals.

how can i replace literals?

**Comment by icambron** [comment]
What literals? Can you post an example?

**Comment by berrynana** [comment]
AS IS: luxon.DateTime.fromFormat('20191231', 'yyyyMMdd').setLocale('es-US').toLocaleString({ year: 'numeric', month: '2-digit', day: '2-digit' }); // return 12/31/2019

so, need to add literal option in toLocaleString()

TO BE: ....toLocaleString({ year: 'numeric', month: '2-digit', day: '2-digit', literal: '-' }); // return 12-31-2019

**Comment by icambron** [comment]
No, there is no such option in the API. The whole idea of `toLocaleString()` is that you let the Intl API pick the ordering and literals and numbering system and so on for you based on the locale. You have four options:

 * Find and replace them in the output
 * Use `toLocaleParts()`, map across the results and replace the literals as you would like
 * Find a locale that formats as you'd like
 * Use `toFormatString()` and specify exactly what you want

Since I don't know what need is driving your desire for replacing slashes with hyphens, I don't know which one to advice. I will caution that *in general* you don't want to do any of that. Instead, you want to accept that you don't know what literals people in arbitrary locales will use a priori and accept whatever `toLocaleString` tells you.
