### ISSUE TITLE
DateTime.{max, min} doesn't return DateTime object but a string when filled with ISO string array

### ISSUE THREAD

**Issue by sbucaille** [moment/luxon#539]
As said in the title, when I want to retrieve the min or max of a list of ISO formatted strings, the method returns the string on the concerned date, not a DateTime object of it.

Proof :
![image](https://user-images.githubusercontent.com/24275548/60989728-f7169000-a346-11e9-994c-3a675fe1f501.png)

The method should create and return an instance of the max or min date. Or maybe change documentation to fit the result which would be generic type returned depending on what we put in argument ?

**Comment by icambron** [comment]
No, it should just throw if you pass it something other than instances `DateTime`. Taking strings and returning strings just happens to work because `max()` only depends on the items implementing `valueOf`

**Comment by sbucaille** [comment]
Okey, but the problem is that in Typescript, according to the documentation, it expects a DateTime to be returned, not a string, so it consider it as a type error. Because of that, I can't use it in my Angular project.

**Comment by icambron** [comment]
There's no TypeScript in Luxon. The docs do say it takes DateTime instances as parameters: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-max, and we definitely don't support passing anything else to it, so what you got is just undefined behavior. So on the one hand, I'd be happy to throw if you send it something that doesn't match the types it expects because that will prevent confusion, but it's not going to coerce other things into DateTimes.

If you have your own TypeScript defs or you've pulled third-party ones, you should make sure it only allows you to pass DateTime *in*. Something like:

```js
static max(...dateTimes: DateTime[]): DateTime;
```

**Comment by icambron** [comment]
argument type checking is now in 1.17.0, see d552dfbf79b52cdab6bb578a7521ea915bb64d88
