### ISSUE TITLE
Date formating with token "t" diffrent in chrome and firefox

### ISSUE THREAD

**Issue by rameezcubet** [moment/luxon#554]
```
const test = DateTime.fromSQL('2019-08-06 13:20:54', { zone: 'utc' })
    .toLocal()
    .toFormat('d LLLL yyyy t')
alert(test)
```
if you run the above code in chrome it will alert "6 August 2019 18:50" and if you run the same code in firefox it will alert "6 August 2019 6:50 PM" 

As per the documentation([https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens)) what shows in firefox is correct and text showing in  chrome is wrong

jsfiddle
-------------
http://jsfiddle.net/gpb8u2ow/

**Comment by icambron** [comment]
1. It depends on your locale. Are you sure you don't just have different locale settings in your different browsers? My are set up as `en-US`, so I get 6:50 PM in both browsers. The quickest way to check is by running:

```js
luxon.DateTime.local().locale
```

I'm pretty sure that's what it will turn out to be. But here's some more details:

2. You can also control the locale explicitly through `Settings.defaultLocale = "en-US"` or `someDateTimeInstance.setLocale("en-US")`

3 Under the covers, Luxon is really doing this to create the `t` string:

```js
new Intl.DateTimeFormat(dt.locale, { hour: "numeric", minute: "2-digit" }).format(dt.toJSDate())
```

So it's browser-native capabilities and Luxon just wraps that in convenient tools. So it can't really get it wrong, only the browser can.

4. That doesn't guarantee it's going to be the same in all browsers, since some browser could choose to implement your locale differently, although in practice, they seem to use the same CLDR data.
