### ISSUE TITLE
semver version numbers

### ISSUE THREAD

**Issue by networkimprov** [moment/luxon#555]
Is Luxon following semver? If not, it might be a "good idea".

Some 1.x releases apparently only add fixes (i.e. no new features), and those should be 1.x.y releases.

**Comment by networkimprov** [comment]
Also, a 2.0 release would imply breaking changes to the API.

**Comment by icambron** [comment]
We have a number of reverse-incompatible changes slated for 2.0.

We aren't completely exact with minor versions vs patch versions because it's not always clear what changes are changes in behavior vs bug fixes; one dev's bug fix is another dev's breaking change, so there's a judgement call there. We tend to make API-compatible behavior changes that aren't purely unambiguous bug fixes minor versions.

Does that answer your question?

**Comment by ericmorand** [comment]
> one dev's bug fix is another dev's breaking change, so there's a judgement call there. 

Isn't it as simple as "if changing something makes the test suite fails then it's a breaking change"?

**Comment by icambron** [comment]
Yes.

If we went by the letter of semver, we'd have to make a major version on that, which of course we're not going to do. But what you're suggesting is basically what we do with minor versions vs patch versions. For example, if we were to make a change to make ourselves more consistent with ISO 8601, that's a bug fix (spec compliance!) but also breaks some tests and possibly some users, so we'd have made that minor bump. If it was handling some case that previously threw an unexpected error or returned clearly bogus results, we'd just bump the patch.

I think that's broadly consistent with what other projects do.

**Comment by networkimprov** [comment]
I agree that's sensible. Maybe include a link into the changelog in each Github release comment?

**Comment by ericmorand** [comment]
@icambron, I have a very unpopular position on this: I consider bumping major version as a non-issue and a normal thing to do. In other words, major version are just a technical requirement whose purpose in _only_ to identify breaking changes.

That means that, for me, having a library at major version 57 is normal and expected if there have been 56 BC since version 1.

I know this is not a popular point of view, but really, I think developers should stop considering major version as relevant for anything else than an information for semver-compatible dependencies manager.

**Comment by networkimprov** [comment]
Are you suggesting major-version increments for changes in output, or only API names and function arguments?
