### ISSUE TITLE
fromJSDate giving different dates based upon format

### ISSUE THREAD

**Issue by skrjon** [moment/luxon#574]
I am unsure if this is a Luxon issue or of its a known JS Date Issue. When using a date Year-Month-Date separated by hyphens fromJSDate outputs a date on the previous day. 

It converts **1961-01-02** into **1961-01-01T16:00:00.000-08:00**.

**Using fromJSDate on JS Date Objects**
```
> DateTime.fromJSDate(new Date("01/02/1961")).toISO();
'1961-01-02T00:00:00.000-08:00'
> DateTime.fromJSDate(new Date("1961/01/02")).toISO();
'1961-01-02T00:00:00.000-08:00'
> DateTime.fromJSDate(new Date("1961-01-02")).toISO();
'1961-01-01T16:00:00.000-08:00'
```

**Using JS Date on these formats.**
```
> new Date("1961-01-02")
1961-01-02T00:00:00.000Z
> new Date("1961/01/02")
1961-01-02T08:00:00.000Z
> new Date("01/02/1961")
1961-01-02T08:00:00.000Z
```

**Comment by icambron** [comment]
This isn't a Luxon thing, just a quirk in the Date constructor. It's interpreting your hyphenated date as a UTC time, not a local time. Luxon just sees the date passed in; it doesn't know what it was parsed from. You have a few options:

1. Be careful in how you build JS Date objects to avoid this behavior
2. Let Luxon parse your dates. I recommend this if the hyphenated date is what you use, since you can just Luxon's `fromISO()` handle it
3. In general, I don't recommend parsing dates at all if you don't need to. You can just use Luxon's `local()` or `utc` methods to make this easy
