### ISSUE TITLE
[Suggestion] Change weekdaysNarrow from MTWTFSS to MTWRFSU

### ISSUE THREAD

**Issue by ekleung** [moment/luxon#599]
Hello,

I've noticed that in `weekdaysNarrow` from https://github.com/moment/luxon/blob/master/src/impl/english.js
or
https://moment.github.io/luxon/global/luxon.js
or
https://moment.github.io/luxon/global/luxon.min.js,

the current definition is`["M", "T", "W", "T", "F", "S", "S"]`. I believe this may cause some confusion when trying to figure out if the code is outputting Tuesday vs. Thursday, or Saturday vs. Sunday.

May I suggest changing the current definition to `weekdaysNarrow = ["M", "T", "W", "R", "F", "S", "U"];`? This way there is no ambiguity. According to https://en.wikipedia.org/wiki/Talk:Names_of_the_days_of_the_week, the suggested convention is "widespread in academia", meaning - in a sense - that it is a "common" convention. I don't believe there is an ISO definition for weekdaysNarrow, however please correct me if I'm mistaken.

Is this a good idea? Any thoughts are highly appreciated! Thanks!

**Comment by GillesDebunne** [comment]
A Google search for `MTWRFSU` does not bring back a lot a results (`pmset` on MacOS). If this convention is not so widespread, it might confuse users.

**Comment by icambron** [comment]
I don't think we should do this for functional reasons. The idea is that you're using this in like calendar headings or some other context where it's obvious that the first is Saturday and the second is Sunday. Secondly, this is from the ICU data, so a lot of experts have already decided that this is the thing to do. As another data point, I have been writing calendaring software for not quite half my life and I have never actually seen that convention used.

But I also oppose this on technical grounds. The definition above is from the English.js polyfill. We use it instead of Intl formatter when the locale is English because a) not every platform has Intl yet and b) because it's way faster than Intl. However, we shouldn't customize it because the whole point is to be a fast, consistent implementation of the subset of features we get from Intl in English. For example, we'd have these drawbacks:

 1. We can't customize other languages, so it's weird to be different than Intl in one language but not others
 1. There are scenarios, such as setting alternative calendars, where we need to use Intl even in English, and that would add inconsistencies
 1. If Intl became fast enough, we'd switch to using it exclusively, since we are going to drop support for pre-Intl platforms very soon

So I'm going to respectfully decline this request.
