### ISSUE TITLE
Loss of information when parsing fractional values in ISO duration string

### ISSUE THREAD

**Issue by kanteankit** [moment/luxon#608]
I have a ISO duration string: `PT0.001S`. I am parsing this string as:

```
luxon.Duration.fromISO( "PT0.001S").toObject()
```
The output I get is
```
{ seconds: 0, milliseconds: 0 }
```

I want to show the user the output as `0.001 seconds` or `0.1 milliseconds`. But, luxon is completely ignoring the decimal values when converting it as an object.

**EDIT (5 Nov)**
The input string is `PT0.0001S`

**Comment by icambron** [comment]
I don't understand the tick marks in that input string. A typo?

At any rate, after making the most obvious change, I can't reproduce this. Are you sure you're on the latest version?

```js
luxon.Duration.fromISO( `PT0.001S`).toObject()
{seconds: 0, milliseconds: 1}
```

(It is a little odd that we parse that as 1 millisecond instead of 0.001 seconds, but it looks like we required all the numbers to be whole. Worth revisiting in a later version.)

**Comment by kanteankit** [comment]
Sorry for the wrong input. The correct input is `PT0.0001S`

**Comment by icambron** [comment]
Luxon only supports millisecond precision, so 0.1 milliseconds is the same as 0. In fact, Luxon even rounds down to prevent rounding cascades.
