### ISSUE TITLE
Unexpected behaviour when adding day

### ISSUE THREAD

**Issue by dauledk** [moment/luxon#621]
I am running the newest version of Luxon, and just found this unexpected behaviour?

```
const testDate = DateTime.fromISO('2019-04-18T14:00:00.000+01:00');
testDate.plus({ day: 1 }).set({ hour: 9, minute: 18 }).toISO();
// "2019-04-19T09:18:00.000+02:00"
```

Why is the offset changed - is this not a bug?

**Comment by icambron** [comment]
The offset did not change; it was never +1. The string being parsed is *expressed* in +1 but Luxon converts it to a local time, and presumably you're in +2. E.g., here is for me:

```js
var testDate = DateTime.fromISO('2019-04-18T14:00:00.000+01:00');
testDate.toISO(); // "2019-04-18T09:00:00.000-04:00" (notice it made the adjustment, but the time is my local time)
testDate.plus({ day: 1 }).set({ hour: 9, minute: 18 }).toISO(); //=> "2019-04-19T09:18:00.000-04:00"
```

How can you work around it? Just use `setZone`:

```js
testDate = DateTime.fromISO('2019-04-18T14:00:00.000+01:00', { setZone: true });
testDate.toISO(); // => "2019-04-18T14:00:00.000+01:00"
testDate.plus({ day: 1 }).set({ hour: 9, minute: 18 }).toISO(); //=> "2019-04-19T09:18:00.000+01:00"
```

Why don't we do that by default? Two reasons: a) it is often confusing to developers if important things like zone would be determined by the string, and would lead to bugs where formatted-back-out strings were in all different zones without the developer realizing it and b) since it's a fixed-offset zone, it loses DST information (e.g. which country's +1 is meant here?) so this forces people to think about what information they really have instead of hoping that the "zone" is really the originator's zone.

**Comment by dauledk** [comment]
Thanks an awesome reply, really helpful!
