### ISSUE TITLE
Chinese/japanese month issue.

### ISSUE THREAD

**Issue by luannguyenQV** [moment/luxon#628]
I meet a problem when format month by **zh-HK** or **ja-JP**:

```
let date = new luxon.DateTime('2019-01-01T00:00:00Z')
data.setLocale("en-US").toFormat('MMMM') // ---> "December"
data.setLocale("zh-HK").toFormat('MMMM') // ---> "12" ==> It's should be chinese language

```
Thanks.

**Comment by icambron** [comment]
You want to use `LLLL`, not `MMMM`:

```js
luxon.DateTime.local().reconfigure({locale: "zh-HK"}).toFormat("LLLL") //=> "12月"
```

`MMMM` is meant to use situations where you're gluing things together, like `date.toFormat("MMMM月dd日")`, whereas `LLLL` is meant for the case where you're going to simply output the month by itself, like you did. In many languages, the representation between these modes is different.

Luxon considers 月 to be "outside" the name when in formatting mode (M) and "inside" when in standalone mode (L) because that's how the Intl API does it (at least in Chrome), and Luxon is simply parsing those results:

```js

// MMMM is like this
new Intl.DateTimeFormat("zh", { month: "long", day: "numeric" }).formatToParts()
// => [{type: "month", value: "12"},
           {type: "literal", value: "月"}, <--- here it's a literal, like the ":" in 5:35
           {type: "day", value: "10"},
           {type: "literal", value: "日" }]

// vs

// LLLL is like this
new Intl.DateTimeFormat("zh-HK", { month: "long" }).formatToParts()
//=> [{type: "month", value: "12月"}]  <-- here it is part of the month
```

Perhaps Intl is wrong to do that, but Luxon doesn't decide that.

**Comment by icambron** [comment]
See also #549
