### ISSUE TITLE
toISO for UTC includes "Z" instead of "+0:00"

### ISSUE THREAD

**Issue by valmack** [moment/luxon#638]
**It would be helpful to have the option of "Z" or "+0:00" for ISO formatted UTC datetimes.**

It seems as if the code internal to `toISO` should allow this...
https://github.com/moment/luxon/blob/5bf5f2b04a0d16417c35e2c1f71348d559a4de2b/src/datetime.js#L218-L220

and indeed, `.toFormat("ZZ")` does provide the UTC offset in number format even for UTC datetimes as I discovered here: https://github.com/moment/luxon/issues/238

...but the result of `.toUTC().toISO()` is a string ending in "Z".

----

Btw, I am using a Django backend and unfortunately `django.utils.timezone` does not support "Z" in its ISO format. (It uses `pytz` internally).

**Comment by icambron** [comment]
This is certainly possible, but is there a use case beyond broken ISO parsers?

>  I am using a Django backend and unfortunately django.utils.timezone does not support "Z"

Are you sure? See https://github.com/django/django/blob/master/django/utils/dateparse.py#L112

**Comment by valmack** [comment]
> Are you sure? See https://github.com/django/django/blob/master/django/utils/dateparse.py#L112

Thanks. I did not know about `dateparse`!

I don't have another use case. I just think it would be helpful to support both formats for interoperability but is this a bug?

Based on the snippet I pasted above it seems like the expected behavior should be the number formatting.

**Comment by icambron** [comment]
No, it's not a bug. Z is very much part of the spec, and ISO parsers are expected to implement it. I've never seen one that doesn't. The code actually goes out of its way to put the Z in there, as you can see [here](https://github.com/moment/luxon/blob/5bf5f2b04a0d16417c35e2c1f71348d559a4de2b/src/datetime.js#L185). That's because in my experience, most people tend to prefer it.

There's not really anything wrong with adding an option for it (would be a matter of wiring through `allowZ`). I just don't want to add them if there's no compelling use case: more to test, support, document, etc.

**Comment by valmack** [comment]
> The code actually goes out of its way to put the Z in there, as you can see [here](https://Github.com/moment/luxon/blob/5bf5f2b04a0d16417c35e2c1f71348d559a4de2b/src/datetime.js#L185).

I see. So allowZ is the explicit way to change +0:00 to Z, but it’s not exposed in the API to be set false.

I’ll just leave this for anyone new to datetimes who may have been confused like me:

——

I didn’t want to handle parsing this differently server side (maybe you can’t control the server side implementation or it’s a third party you’re sending data to) so I just sent the datetime from the client without the offset. The server then converts the string to UTC, assuming the string was already UTC. The absence of offset may be interpreted as the +0:00 offset.

Otherwise you will have to string replace Z with +0:00.

**Comment by icambron** [comment]
I would instead recommend sending the Z and using a standard ISO parser on the server. That makes it less likely that someone gets confused down the line.

Note that `Z` are `+0:00` are not quite interchangeable. This is because you might be in a timezone that happens to be `+0:00` sometimes. For example:

```js
DateTime.local().setZone("Europe/London").toISO() // => "2020-01-05T15:32:55.555+00:00"
```

whereas Z implies UTC.

**Comment by valmack** [comment]
> This is because you might be in a timezone that happens to be `+0:00` sometimes. For example:
> 
> ```js
> DateTime.local().setZone("Europe/London").toISO() // => "2020-01-05T15:32:55.555+00:00"
> ```
> 
> whereas Z implies UTC.

Oh ty!

In my case this is fine because it has the offset. So the server can read that and convert it to UTC and I think string replace __from__ Z __to__ +0:00 would still be fine here, just not the other way around.
