### ISSUE TITLE
hour: "numeric" is shown as "2-digit" if paired with weekday but not month or year

### ISSUE THREAD

**Issue by fabyeah** [moment/luxon#640]
This seems to be a bug?

```
const format = {
  weekday: 'long',
  hour: 'numeric',
  minute: '2-digit'
};

return dt.toLocaleString(format);
```

Expected output: **5:21**
Actual output: **05:21**

If `month` or `year` are added to the format object, or if `weekday` is removed, `hour` is correctly formatted as `numeric`.

Example: https://codesandbox.io/s/eager-merkle-ixlr9

**Comment by icambron** [comment]
I tried this on both Chrome and Firefox and got this:

<img width="516" alt="eager-merkle-ixlr9_-_CodeSandbox" src="https://user-images.githubusercontent.com/244988/71775095-d0799080-2f48-11ea-9a02-920ec246da8c.png">

What browser are you in?

Whichever browser, Luxon is really just asking the Intl.DateTimeFormat API to do the work, so you should also see the issue doing this:

```js
new Intl.DateTimeFormat("en", format).format(new Date("2020-01-04:05:21"))
```

**Comment by fabyeah** [comment]
<img width="408" alt="Screenshot 2020-01-05 at 05 51 32" src="https://user-images.githubusercontent.com/4738527/71775345-8f50a300-2f7f-11ea-9b78-2e78ee2f7ffb.png">

That's weird. I'm using Chrome on macOS.

```
new Intl.DateTimeFormat("en", format).format(new Date("2020-01-04:05:21"))
```

gives me `Saturday 5:21 AM`

But when set to german (as is my browser) like so

```
new Intl.DateTimeFormat("de", format).format(new Date("2020-01-04:05:21"))
```
I get `Samstag, 05:21`

Maybe that is the preferred formatting for german, but then why does it differ depending on what parameters are included in the format?

**Comment by icambron** [comment]
I'm also on a Mac. Doesn't *seem* like it could be because of German, since yours also says "Wednesday". But maybe it has something to do with it.

In any case, with German specified in the Intl constructor, I also get `Samstag, 05:21`, and I also see the dropped 0 if I remove the weekday.

The Intl API spec is pretty complicated and has some allowances for the implementation to to make decisions based on combining the parameters you put in and the information it has about how the language works; it's not as straightforward as it looks. However, I am not deeply familiar with the ins and outs, so I'm not sure whether it's a bug in Chrome or not. Perhaps it is, in which case, a ticket with Chromium is needed.

But in any case, there's nothing much Luxon can do about it. Luxon is just the messenger.

**Comment by icambron** [comment]
I guess I will reopen this to more fully explore why you're getting different results from intl than from luxon.

**Comment by fabyeah** [comment]
In Firefox as well as in Safari I get the correct output:

<img width="554" alt="Screenshot 2020-01-05 at 22 23 50" src="https://user-images.githubusercontent.com/4738527/71786305-514c9100-300a-11ea-95be-76a108557ae9.png">

I guess it's a Chrome issue then, as you said.

**Comment by fabyeah** [comment]
I have created a Chromium bug ticket here: https://bugs.chromium.org/p/chromium/issues/detail?id=1039138

**Comment by diesieben07** [comment]
The Chromium ticket has been closed as "wont fix", because the Intl spec does not mandate the engine to return exactly what was asked for. That is correct and Luxon is at the mercy of the underlying browser here. Luxon's toLocaleString can only be as good as the underlying browser.
Because there isn't anything actionable for Luxon to do here, I am going to close this.
