### ISSUE TITLE
Incorrect behavior or misunderstood documentation about DateTime.toJSDate

### ISSUE THREAD

**Issue by wesleyegberto** [moment/luxon#655]
Hi

I'm using `toJSDate` to get the JS date from a zoned DateTime but it seems to be losing the zone I've setted.

Here is the code I'm testing, my current zone is America/Sao_Paulo (-3:00) and I'm using America/New_York (-5:00).

```js
const localNow = DateTime.local();
const zonedNow = localNow .setZone("America/New_York");
const now = zonedNow.toJSDate();

console.log('Dates:', localNow.toString(), zonedNow.toString(), now.toString());
```

Output:
```
Dates: 2020-02-04T17:29:40.006-03:00 2020-02-04T15:29:40.006-05:00 Tue Feb 04 2020 17:29:40 GMT-0300 (Brasilia Standard Time)
```

The documentation [toJSDate](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toJSDate) shows that it returns a Date equivalent, so I'm specting to get the same hour.
If `toJSDate` ignores the zone and only returns the local hour I think it needs to update the docs.

Am I missing something?

**Comment by icambron** [comment]
Yes, you've misunderstood how dates are represented in programming. From the Luxon docs:

> It's important to remember that a DateTime represents a specific instant in time and that instant has an unambiguous meaning independent of what time zone you're in; the zone is really piece of social metadata that affects how humans interact with the time, rather than a fact about the passing of time itself. Of course, Luxon is a library for humans, so that social metadata affects Luxon's behavior too. It just doesn't change *what time it is*.

It then goes on to describe what operations are affected by the zone (formatting and math operations). But as applied here: the _underlying time_ represented by the date isn't being changed by `setZone`. It would be supremely weird if `someDateTime.setZone(...).toJSDate()` resulted in something different than `someDateTime.toJSDate()` because the actual moment in time didn't change. So all that's happening is that you've taken a date type (Luxon's DateTime) that supports arbitrary zones and converted it to a type (JS Date) that does not.

What you're expecting is something very different -- for the time to change such that its local representation remains constant. If that's what you want, that's a pretty excotic use case and you should be sure you really do want it, because you are creating a JS Date object that intentionally misrepresents the time. But of course you can do it. You can use [keepLocalTime](https://moment.github.io/luxon/docs/manual/zones.html#keeplocaltime):

```js
// this one is just for reference. I'm in America/New_York and it's currently 18:45
var localNow = DateTime.local();
console.log(localNow.toJSDate());
//=> Tue Feb 04 2020 18:45:38 GMT-0500 (Eastern Standard Time)

//Luxon supports zones, so if we format it there, we get a local time 5 hours different
var otherZone = localNow.setZone("Europe/London");
console.log(otherZone.toISO());
//=> 2020-02-04T23:45:38.075+00:00

// But the time is still now, so if I turn it back into a JS date and format it in my time zone, I get 18:45 again
console.log(otherZone.toJSDate());
//=> Tue Feb 04 2020 18:45:38 GMT-0500 (Eastern Standard Time)

// But if I convert it back to a local time, specifically telling Luxon to change the underlying date soas to
//maintain a constant local time across the zones, you end up with 23:45, which is what you were expecting:
var backHereButSameLocalTime = otherZone.setZone("local", { keepLocalTime: true });
console.log(backHereButSameLocalTime.toJSDate());
//=> Tue Feb 04 2020 23:45:38 GMT-0500 (Eastern Standard Time)
```

**Comment by wesleyegberto** [comment]
Thank you for the explanation.
Beside that, I also wasn't clear about my scenario, sorry for that.

We have a Nodejs cron job running in a different timezone from the user (currently, the hour is selected by the user and stored using his timezone).
We were trying to get the current datetime in the user's timezone, so we started by getting the job local current timezone, setted the user's timezone and then convert it to JS Date object.

**Comment by icambron** [comment]
That's probably not the best way to do that. Generally, you want to do something with the local time, such as output text that contains the local time, or store the local time, etc. And then the best thing to do is to simply use Luxon's formatting tools to do it, because they will work seamlessly in the zoned time.

The danger of using a modified Date object is that it can lead to very nasty bugs if the operation ends up needing to use the actual time as opposed to just its local representation. For example, it can give wrong answers to questions like "is this time in the past or future?" or "how much time has elapsed between time x and time y"

There are probably exceptions, such as passing the Date object to some third party library that is not zone-aware. But you should be careful.
