### ISSUE TITLE
dateTime.set({weekday: X}) doesn't account for DST when going across DSTs

### ISSUE THREAD

**Issue by IAmMarcellus** [moment/luxon#671]
Browser: Chrome
Local timezone: America/Chicago

Problem: Using `DateTime.fromFormat('2:00, 'H:mm')` to create a DateTime and then using `dt.set({weekday: 7})` will change the hour to change to making it 3:00 am instead of 2. I believe this is because of daylight savings time which changes this Sunday.

According to the docs: "if you add a day to a DateTime, you should always get the same time the next day, regardless of any intervening DSTs. On the other hand, adding 24 hours will result in DateTime that is 24 hours later, which may or may not be the same time the next day." However, changing the weekday seems to work like the latter and add 24 hours across DSTs rather than just changing the day and keeping the same time.

You can see the problem and play around with it here: https://codesandbox.io/s/luxon-playground-15891

Curiously, this only seems to happen if the hour being parsed is 2.

**Comment by icambron** [comment]
No, that's what you're seeing. Instead, you're seeing that 2:00 doesn't actually exist in New York that morning; the local time jumps from 1:59:59.999 to 3:00:00.000 because you're right on the DST shift. Theres simply isn't a local time called 2:00, and that's also why it only happens for 2:00 and not, say, [4:00](https://codesandbox.io/s/luxon-playground-i3ynn). Luxon's behavior for that is defined [here](https://moment.github.io/luxon/docs/manual/zones.html#invalid-times).
