### ISSUE TITLE
DateTime.toFormat('ZZZZ') not showing expected output (Again)

### ISSUE THREAD

**Issue by philiprabbett** [moment/luxon#692]
Previously an issue #499 has raised itself again. To recap:

> According to the [docs](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens), when the `ZZZZ` token is passed in the format string, the abbreviated named offset string should be displayed in the output string.
> However, the timezone offset from GMT is being displayed instead.

Code snippet to test the issue:

```JS
var iso = DateTime.fromISO('2020-01-31T12:18:48+0000', {
    zone : 'Europe/Amsterdam'
});
```

```JS
iso.toFormat('dd MMMM yyyy HH:mm ZZZZ');
```

Expected Output:

> 31 January 2020 13:18 CET

Actual Output:

> 31 January 2020 13:18 GMT+1

```JS
iso.offsetNameShort;
```

Expected Output:

> CET

Actual Output:

> CET

As you can see, we are getting two different results from what should be the same result for the timezone offset name.

Briefly looking into this, this seams to be a locale issue in that the `.offsetNameShort` will use the users / system locale (in my case 'en-GB') while `.toFormat()` is forced to use the locale `en-US' thereby producing two different results.

I've tracked this down to the following place:

https://github.com/moment/luxon/blob/e1f3bb7f7378ea665998079a6763e4bb86f41851/src/impl/locale.js#L290
https://github.com/moment/luxon/blob/e1f3bb7f7378ea665998079a6763e4bb86f41851/src/datetime.js#L1460

To recreate in more detail:

```JS
iso.zone.offsetName(iso.toSeconds(), { format: 'short', locale: 'en-US' })); //=> GMT+1
iso.zone.offsetName(iso.toSeconds(), { format: 'short', locale: 'en-GB' })); //=> CET
```

I'm fine with it being different based on the locale as that's what the browsers are doing by default but the problem is that the same calls via two different methods `.offsetNameShort` and `.toFormat()` results in two different short names meaning `.toFormat()` is not using the same locale as `.offsetNameShort`

**Comment by philiprabbett** [comment]
Oh it looks like this is intentional.

`.offsetNameShort` Defaults to the system's locale if no locale has been specified.
`.toFormat()` Defaults to en-US if no locale has been specified, regardless of the system's locale.

**Comment by icambron** [comment]
Yeah, this is a tricky one. It's pretty unfortunate that en-US returns something different there; in many ways, that's the real issue.

The background here is that if you're formatting a string for use by some parser, you really don't want the format to be dependent on the user's system locale, since you don't typically control that. So we have it default to either a) an explicitly-set default locale or b) fallback directly to en-US. Then you can reliably get the same string.

There are a few work-arounds:

```js
DateTime.fromISO('2020-01-31T12:18:48+0000', { zone: 'Europe/Amsterdam' }).toFormat('dd MMMM yyyy HH:mm ZZZZ', { locale: "en-GB" })

Settings.defaultLocale = "en-GB"
DateTime.fromISO('2020-01-31T12:18:48+0000', { zone: 'Europe/Amsterdam' }).toFormat('dd MMMM yyyy HH:mm ZZZZ')
"31 January 2020 13:18 CET"
```

The one thing missing here is that Luxon doesn't make it easy for you to ask for the system locale. I think I'd take a PR surfacing that in `Info` so you can pass it back in more conveniently into those workarounds above.
