### ISSUE TITLE
Luxon interval returns invalid 

### ISSUE THREAD

**Issue by chahat** [moment/luxon#695]
I have the following code 
s= 2020-04-22T06:00:00.441+08:00 
e= 2020-04-23T00:00:00.442+32:00 
now= 2020-04-22T23:16:34.440+08:00

Interval.fromDateTimes(s, e).contains(now)  <= RETURNING FALSE

![image](https://user-images.githubusercontent.com/2259404/80001059-3bca7c80-84be-11ea-86a8-c2d7732dcff6.png)

What is the problem here?? I am on "luxon": "1.10.0",

Is this a known bug? The above happens on chrome 

However in Firefox it works fine 
![image](https://user-images.githubusercontent.com/2259404/80001626-de82fb00-84be-11ea-821c-4d65e7a29ecd.png)

**Comment by icambron** [comment]
It's different between the browsers because your times are actually different -- e is `2020-04-23T00:00:00.442+32:00` for your example in Chrome, but in Firefox, if you look at the last line, you can see it's a different time.

Luxon is correct in the Chrome case because `2020-04-23T00:00:00.442+32:00` really is before `2020-04-22T06:00:00.441+08:00`; note the massive offset on the end time, which means it's really much earlier than it looks like at first glance. So the real issue is: where did that wild offset come from? +32 is not a reasonable offset.

**Comment by chahat** [comment]
Thanks for replying @icambron 

The code below returns the timestamp you see with the crazy +32 offset on chrome. it was not happening to me earlier but only recently since chrome version Chrome (80.0.3987.163) and above. 

DateTime.local().setZone('Asia/Singapore').set({ hour: 0, minute: 0, second: 0 });

Could you please suggest what is the problem or a workaround ??

**Comment by icambron** [comment]
Upgrade Luxon to the latest version. Chrome released a change that broke offset handling in Luxon but it's fixed in Luxon. This works for me:

```js
DateTime.local().setZone('Asia/Singapore').set({ hour: 0, minute: 0, second: 0 }).toISO()
"2020-04-23T00:00:00.371+08:00"
```

**Comment by chahat** [comment]
Hi @icambron what do you mean Chrome released a change that broke offset handling in **Luxon** but **it's fixed in Luxon** ??

DateTime.local().setZone('Asia/Singapore').set({ hour: 0, minute: 0, second: 0 }).toISO() will return a string right? i want DateTime instance not string to perform operation 

Thanks,
Chahat

**Comment by icambron** [comment]
I mean this: https://github.com/moment/luxon/issues/619#issuecomment-583272934

And yes, that's right, I was just demonstrating the time I got by converting it to an ISO string
