### ISSUE TITLE
Finding luxon's niche

### ISSUE THREAD

**Issue by sesam** [moment/luxon#705]
I found luxon by a link from a moment 2.25.0 bug discussion, and tried to find a reason to switch from moment to luxon. Size? Not a serious advantage. Maintenance / fast evolvement? [Probably not](https://github.com/moment/luxon/issues/594) though this is the main advantage lifted forward in what I've read from the library's creator :) -- and maybe luxon does nearly what moment does but with 1% of the expended maintenance effort? Compatibility with moment? Not sure? Maybe if luxon is a drop-in replacement for moment when you can rely on users having the latest Chrome, this could do it for some. But if you need PWA, then iOS Safari at least with optional polyfills is needed.

So, what's luxons niche? Where does luxon shine? In which case should I pick this tool instead of any other?

(If we can find an answer, consider showing it off prominently)

**Comment by sesam** [comment]
Any good answers could also be added here https://stackshare.io/stackups/luxon-vs-moment-js

**Comment by icambron** [comment]
This is not a forum for debating Luxon's pros and cons. If you don't want to pick this tool over others, don't.

**Comment by sesam** [comment]
Sorry. Meanwhile, I found this https://youtu.be/Qkc8p4D6JM0?t=6893 from the MagnoliaJS virtual conference where they showcase switching from moment to luxon and saw a huge improvement in webpack size. So that's a validated niche right there :)

**Comment by dogoku** [comment]
> Sorry. Meanwhile, I found this https://youtu.be/Qkc8p4D6JM0?t=6893 from the MagnoliaJS virtual conference where they showcase switching from moment to luxon and saw a huge improvement in webpack size. So that's a validated niche right there :)

Honestly looking at their bundle, they didn't bundle moment correctly. You can load moment on its own (~18k gz) and only load the required locales (~2k per locale) instead of loading everything.

Having said that, if you add moment-timezone to the mix and that's ~95k gz right away (moment with ALL locales is only ~70k). And this is where Luxon saves you data and time. You let the browser give u all the IANA timezone data and keep the timezones updated, all thanks to the Intl APIs
