### ISSUE TITLE
Duration as('years') returning incorrect value

### ISSUE THREAD

**Issue by hawkett** [moment/luxon#708]
Luxon 1.24.1 (also 1.22.2) seems to be returning incorrect values using Duration `as('years')`, but correct values for `as('hours')`. 

```
var time1 = luxon.DateTime.fromISO('2021-03-21T05:03:00.000-07:00');
var time2 = luxon.DateTime.fromISO('1988-03-28T02:13:00.000-08:00');

// Years
console.log(time1.diff(time2).as('years'));       // Incorrect: 33.00294901065449
console.log(time1.diff(time2, 'years').years);    // Correct: 32.98114535768645

// Hours
console.log(time1.diff(time2).as('hours'));       // Correct: 289105.8333333333
console.log(time1.diff(time2, 'hours').hours);    // Correct: 289105.8333333333
```

**Comment by icambron** [comment]
That's expected behavior. The first one is taking the diff in milliseconds and rolling it up to years using the default conversion rules. It's converting the milliseconds you got from the diff to years, but not necessarily _those particular_ years. See [Losing Information](https://moment.github.io/luxon/docs/manual/math.html#losing-information). You may also be interested in the section above it, which discusses the mechanics of the conversion you're doing there, and how to modify it.

The second one actually computes the diff in years, so that one does what you want because it actually knows what years are involved.

The hours one doesn't have the same schism because hours and milliseconds convert to one another losslessly; all hours are the same length.
