### ISSUE TITLE
Library fails to parse time using fromFormat

### ISSUE THREAD

**Issue by RuLeZzz1987** [moment/luxon#714]
```
Settings.defaultLocale = 'es-ES';

DateTime.fromFormat('11:22 am', 'hh:mm a');
```
returns `"the input "11:22 am" can't be parsed as format hh:mm a"`
in case of `es-ES` locale `/^(\d{2})(:)(\d{2})(\ )(a\.? m.|p\.? m.)$/i` was used and for `en-US` - `/^(\d{2})(:)(\d{2})(\ )(AM|PM)$/i`

expected result: `DateTime.fromFormat('11:22 am', 'hh:mm a')` to be parsed without exceptions

**Comment by icambron** [comment]
Yes, it looks like the local format for the meridiem is "a. m." or "p. m.":

```js
> DateTime.local().setLocale("es-ES").toFormat("a") //=> 'p. m.'
```

So that's what Luxon is trying to parse. Luxon makes the dots optional for all tokens but it doesn't make spaces optional, hence the regex. So this is expected behavior.

We could offer a locale-insensitive meridiem token -- that would be a reasonable feature request.

**Comment by RuLeZzz1987** [comment]
https://codesandbox.io/s/luxon-playground-lnruf?file=/src/index.js

Doesn't work for me with or without dots and spaces

**Comment by icambron** [comment]
hmm, ok, i'll take a closer look
