### ISSUE TITLE
Detect timezone abbreviation using Luxon

### ISSUE THREAD

**Issue by brijesh-pant** [moment/luxon#715]
Moment timezone results with short timezone abbreviations, e.g
```
moment.tz([2012, 0], 'America/New_York').format('z');    // EST
moment.tz([2012, 5], 'America/New_York').format('z');    // EDT
```
Is there a similar way we can achieve that using luxon

I tried `offsetNameShort`, but, it results to `GMT+5:30` for a date like `"2020-05-23T13:30:00+05:30"`

Something like `DateTime.fromISO(""2020-05-23T13:30:00+05:30"").toFormat('z')` doesn't work either

Is there a way we can remove the `+5:30` timezone from the format avoiding use of `moment-timezone` library?

**Comment by icambron** [comment]
`moment-timezone` won't help you here either, because you aren't specifying the zone. You are trying to derive a time zone from a UTC offset, which does not work.

I live in America/New_York, which is currently in -4 and locally called ETD. Hence:

```js
DateTime.local().setZone("America/New_York").offsetNameShort
'EDT'
```

Knowing I'm in America/New_York is enough to know that. But the opposite is not true: knowing I'm in -4 isn't enough to know that I'm in America/New_York and thus locally EDT. For example, perhaps I'm in [Brazil](https://www.timeanddate.com/worldclock/brazil/manaus) and the local name is AMT (short for Amazon Time). There simply isn't enough information to  translate the offset to a specific zone. It may be the case that India is the only location that has a 5:30 offset, but Luxon doesn't keep track of that very specific fact, because it isn't true for most offsets.

You can read more here: https://spin.atomicobject.com/2016/07/06/time-zones-offsets/.
