### ISSUE TITLE
Duration as months incorrect

### ISSUE THREAD

**Issue by starkgoat** [moment/luxon#723]
I'm getting more months than expected, reproduce:

```
past = DateTime.fromFormat("09-04-1987", "dd-MM-yyyy")
today = DateTime.fromObject({})
months = dur.as("months")
```
months returns ~ 403. It should be ~ 397.

**Comment by GillesDebunne** [comment]
Assuming `dur` is defined as `dur = today.diff(past)`, this is the expected behavior.

Calling `diff` results in a number of milliseconds by default. Converting those to months later is lossy, since months are assumed to last 30 days on average.

To fix the problem, specify the duration unit(s) you want to use: 
```
dur = today.diff(past, 'months')   // ~397 months
```

**Comment by icambron** [comment]
Relevant docs here: https://moment.github.io/luxon/docs/manual/math.html#losing-information. @GillesDebunne's answer is definitely the recommended way to do this. 

But for completeness, also see the section just above that one (https://moment.github.io/luxon/docs/manual/math.html#casual-vs-longterm-conversion-accuracy) that allows you to switch to treating months as 30.436875 days and also gives you the result you expect:

```js
today.diff(past, "milliseconds",  { conversionAccuracy: "longterm"}).as("months") //=> 397.8106375129005
```

The difference in the two approaches is whether we're diffing those _specific_ months--or months in general. Typically you want the calendar-aware math, so you want `today.diff(past, "months")`
