### ISSUE TITLE
Can't get padding option to do what I expect for DateTime.toRelative() method

### ISSUE THREAD

**Issue by verheyenkoen** [moment/luxon#745]
As per the [docs](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelative) `DateTime.toRelative()` has a padding option, defined in milliseconds for custom rounding. Correct me if I'm wrong (no example provided) but I expect this to work like so:

    DateTime.local().plus({seconds: 14}).toRelative({padding: 5000})

would round to the nearest 5 second step and result in the text "in 15 seconds" but instead I get "in 18 seconds". Can someone explain if it is doing the right thing or if there is another way in achieving what I want?

Using v1.24.1.

**Comment by GillesDebunne** [comment]
Just looking at the code, `padding` does not seem intended to round the relative string.

It is simply added to the difference between the DateTime and the `base` (which defaults to now).

In my tests,

```DateTime.local().plus({seconds: 86400}).toRelative()```

returns _"in 23 hours"_ 95% of the time and _"in 1 day"_ otherwise. 
This is due to the short time between the object creation and the `toRelative()` call (using the `{round:false}` option indeed displays _"in 23.99 hours"_)

Using `DateTime.local().plus({seconds: 86400}).toRelative({padding:10})` reliably returns _"in 1 day"_.

I agree an example with this option is missing in the documentation.

----

Now to solve your initial problem, I think you need to compute and round the time difference manually:

```
step = 5 // in seconds
base = luxon.DateTime.local()
end = base.plus({seconds: 14})
diffInSeconds = end.diff(base, 'seconds').as('seconds')
roundedDiffInSeconds = step * Math.round(diffInSeconds / step)
roundedEnd = base.plus({seconds: roundedDiffInSeconds})
roundedEnd.toRelative({base}) // -> "in 15 seconds"
```

**Comment by verheyenkoen** [comment]
Oh, great. Thanks!
