### ISSUE TITLE
Deserializing Json to object with DateTime property stores it as string

### ISSUE THREAD

**Issue by tank104** [moment/luxon#750]
I have a Typescript object:

```
export interface ObjectA {
  created: DateTime;
}
```

When I use (in Angular):
`this.http.get<ObjectA>(`APIURL`)`
the created comes back as a string not DateTime object.

This is the same as if I was to use JSON.parse()

This might not be specific to luxon, or it might be - but is there a way to make serialisation into a proper DateTime object by default?

**Comment by GillesDebunne** [comment]
This is the expected behavior. 

JSON objects can only contain a limited number of types (string, number, JSON object, array, boolean or `null`), so there is no way to preserve the DateTime type when serializing.

The `DateTime.toJSON()` method is called when serializing to JSON, which actually calls `toISO()` and creates a string. Note that some information is lost in the process (the locale, the zone (but not its offset) are for instance not serialized).

Call `DateTime.fromISO(str)` to create a DateTime object from your http result.

This is not specific to luxon, that's a JSON limitation.

**Comment by wh1t3cAt1k** [comment]
@GillesDebunne 

I was thinking about this behaviour recently, and maybe a different approach deserves a thought, where `toJSON` would return a lossless string representation of the datetime.

Along with that, `luxon` could provide an opt-in polyfill module for `JSON.parse` that would allow to revive such objects.

e.g. in my React application, I generally prefer not to deal with serialization at the Redux state level; however, out of the box, solutions like `redux-persist` fail with `luxon` objects because serialization is effectively one-directional. I have to revert to custom state transformers, but I wish there was a more convenient way.

I understand this would be a breaking change, but perhaps, if this is a popular request and/or inconvenience (is it?), it could be done in one of the major releases.
