### ISSUE TITLE
It looks that when I pass a wrong object to `fromObject` it creates `DateTime` object with current timestamp

### ISSUE THREAD

**Issue by anatoly314** [moment/luxon#767]
```
const date = new Date(2019,0,0);
const dateTime = DateTime.fromObject(date);
console.log(dateTime.year); // will print 2020
```
Expected behavior will be to throw an error, otherwise it can lead to misunderstanding and bugs.

**Comment by GillesDebunne** [comment]
Indeed, `fromObject` picks its properties from the parameters, ignoring unknown keys, and using sensible default values.

Allowing extra properties enables a custom objects such as `{ year: 2020, isLeapYear: true }` to be parsed.

The current date time is used for missing large units, so that `{month:5}` is `2020-05-01T00:00` and `{hour:2}` is `[current date]T02:00`. For consistency `fromObject({})` (which is equivalent to your code example) returns the current time.

An empty object and an object with none of the expected keys (such as a `Date` object), could indeed throw an exception (or return an invalid DateTime) instead. This would be consistent with `fromISO("")` (i.e. with an empty string), and would prevent the potential bugs you describe.

Such a breaking change can be considered for v2.0.

**Comment by icambron** [comment]
I thought about this a bit and I'm 👎 on it. The current behavior is certainly confusing for type errors (e.g. you meant to pass an object but you passed a date), but I'm afraid the cure would be worse than the disease. For example, consider the scenario in which the object is filled out programmatically, with keys being added by upstream logic or a user interface. The caller would then have to say "Does this have any keys? Because if it doesn't, I need avoid calling `fromObject(myObj)`, lest I get an error". These kinds of special cases -- we accept objects unless they have no keys -- cause confusion and inconsistency in their own right. They're a gotcha.

**Comment by anatoly314** [comment]
I would suggest just rename from `fromObject` to something more `meaningful` for example, `fromTemplate`, `fromLuxonObject`, etc... It will cause people to read the documentation more thoroughly and every time when someone will use this method it will remember that it's a special object.

**Comment by icambron** [comment]
But it's not a special case. The contract of the method is that it will take known keys off the object you pass in, defaulting the ones that are missing; an object is how JS implements associative data structures, so `fromObject` means the equivalent of `fromHash` or `fromDictionary` in other languages. This is about _avoiding_ special cases that make it harder to reason about the expected behavior.

Honestly, I think a lot of the complaints about this sort of thing (see also: why doesn't it complain when I pass in undefined?) are really complaints about Javascript and its type system. Those complaints are often perfectly reasonable, but a library like Luxon needs to go with the shape of the language, not fight against it.

For example, you can totally pass a Date in if it you make it follow the contract:

```js
var date = new Date()
date.year = 2019
date.month = 5
date.day = 25
var luxonDate = DateTime.fromObject(date)
luxonDate.toString() // => "2019-05-25T00:00:00.000-04:00"
```
