### ISSUE TITLE
Timezone Description on Docs

### ISSUE THREAD

**Issue by icywolfy** [moment/luxon#81]
> Don't make servers think about local times. Configure them to use UTC and write your server's code to work in UTC. Times can often be thought of as a simple count of epoch milliseconds; what you would call that time (e.g. 9:30) in what zone doesn't (again, often) matter.
>
> Communicate times between systems in ISO 8601, like "2017-05-15T13:30:34Z" where possible (it doesn't matter if you use Z or some local offset; the point is that it precisely identifies the millisecond on the global timeline)

Coming from working with a calendar application, that above advice is the source of many many bugs that are next to impossible to track down. 

### Best practice:
- For any event, ALWAYS store times local time with named timezone as to where it occured, or where it is planned to occur. 
- If only dealing with events that are happening "now", timestamps can be converted immediately to UTC/timestamp.  This is a special case of the the above where location of the event happening is "the server" and the local time can be unquestionably converted to UTC.  (submission, post, email-received, inserted row time, etc)

### To highlight the problem:

Times in the past can be converted to a timestamp.
This timestamp can be represented in any timezone** 
For long-term stability and to prevent curruption of data, use the local time with timezone name (not offset).
** Usually, there are bug-fixes to past timezone transitions regularly.

Times in the future can-not be safety converted to a timestamp.
Times in the future must have a timezone stored with it (not an offset)

The reasoning, 
Timezone rules change several many times a year.  
Sometimes, with a only a day or two notice before the change (like DST being cancelled, or extended).  

#### Future Event
On 2017 Mar 01, you made a event at "2017-03-30 12:00 America/Port-au-prince", 
As a timestamp, you would get 1490889600, (17:00 UTC)

If on 2017-04-30, you create an event at "2017-03-30 12:00 America/Port-au-prince"
As a timestamp, you would get 1490893200, (16:00 UTC)

If you were to show users the event on their calendar, all the events created in the future before Mar 07, will now be incorrect by an hour.

Because, on Mar 07, they announced  that DST would start Mar 12, and it was published to the Olsen TZ database Mar 23 (hot-fixes available for OS's within two days of the announcement for those needing it ASAP).

Thus, because you converted to a timestamp server side or converted to UTC, all your times will be one hour off, in a horrible to track down bug that can't be reproduced, because your timezone definition files were updated.

#### Recurring Event
The same logic goes for recurring events: You have a start-time that is local-time, and named offset.

There is a recurring event at 13:00 America/Port-Au-Prince, to put on my calendar in America/Los_Angeles, Mar 01 .. Mar 30.

If you convert timezones or to timestamp when it was created, all the times after Mar 12 would be incorrect by an hour.  The LA offices would see it every day at 10am, those in Haiti would see it switch from 13:00 to 12:00 when their timezone rules were updated.

#### Past Event
If one converts to a timestamp in the past without a timezone, when errors are corrected in the underlying transition data, all your your timestamps can be now incorrect.

e.g.
Created date "1994-03-20 12:00 Africa/Windhoek" on Sept 30, 2017.
It would convert to Timestamp: 765021600 (10:00 UTC)
After you updated with 2017 Oct Timezone Fixes
It would convert to Timestamp: 765025200 (11:00 UTC)
And all your stored data would be incorrect, and new data with the "same" time, would be inconsistent with previous events.

For just changes last month: see http://mm.icann.org/pipermail/tz-announce/2017-October/000047.html

**Comment by icambron** [comment]
Yes and no. Most generally: Events in the sense you are using it are not the same as times. If we're talking about a calendar event where, say, two people plan to call one another at some time in the feature, then I agree: they plan to chat at some specific local time and the relevant information for that local time must be stored. Doubly so for recurring meetings that may shift according to one time's DST. But coordinated future events are a small subset of times that need to be stored! Many things will happen at a specific moment  in the global timeline, and thus your "always" creates a ton of overhead with only occasional gains.

Specifically:

 * Your example for future events is incorrect. Luxon (and other time libraries) don't generate their timestamps based on the *current* local offset; they base on it on the offset at the proposed local time. Try it in Luxon! The real argument for future events keeping explicit zones is what you mentioned in the "highlight" section: that the zone may change its DST rules, but the event still happens at some proposed local time. Again this is because events in this sense are a special case: they're coordinated through local times and thus must obviously store that information. But your example is wrong because that has nothing to do with any software's ability to translate timestamps to and from local times. You're conflating the conceptual model for events with the one one for times in general.
 * You are correct about recurring events. I don't think that's worth capturing in that paragraph; that's just an exception to "where possible".
 * You are incorrect about past events. Past events happened at a particular global time. That time can be expressed with any offset, the most convenient of which is UTC. It's true that you can't store some purely local time without providing the zone context, but that is not what I proposed at all. What I proposed is that you store and communicate those times in UTC, which precisely captures the time universally and which can be converted into any local time. If the DST rules change, the moment in time at which some event took place does not retroactively change, as you seem to be proposing. That would be bonkers.

Taking all that together: yes, there are situations in which storing and communicating the local time + zone is preferable because that's the information that accurately captures an event's semantics. That's why the whole zone document exists! But it is not most or even many situations and thus your proposed guidelines are mistaken.
