### ISSUE TITLE
Error incompatible tokens on ad-hoc format

### ISSUE THREAD

**Issue by mcrodrig** [moment/luxon#817]
**Describe the bug**
An error is generated when using incompatible tokens in the ad-hoc format (

**To Reproduce**
DateTime.fromFormat("1/1/18 12:00 AM", "M/d/yy HH:mm a").isValid;

**Actual vs Expected behavior**
Current error:
core.js:4352 ERROR Error: Can't include meridiem when specifying 24-hour format
    at explainFromTokens (luxon.js:5679)

Expected: Generate an invalid object. Or a function to validate a format.

**Desktop (please complete the following information):**

- OS: OSX 10.15.6
- Browser: Chrome 86.0.4240.80
- Luxon version: 1.25.0

**Additional context**

**Comment by icambron** [comment]
yeah, you want `hh`, not `HH`. `HH` is for 24-hour time, so "12 am" doesn't make sense.

**Comment by mcrodrig** [comment]
I agree I should use hh and not HH, but shouldn't the library control the wrong format and generate an invalid date?

**Comment by icambron** [comment]
In general, Luxon tries to turn data errors into invalid dates and programmer errors into exceptions. Of course there's a lot of fuzziness there, and you can data-drive anything, but in practice, it works pretty well to assume that having `HH` and `a` in the same format string is a developer making a mistake, and they'd like to know simply and clearly through an exception.

FWIW, Luxon 2 is discontinuing invalid dates altogether, since they cause so many issues in their own right.
