### ISSUE TITLE
How to get the missing timestamp due to the time change?

### ISSUE THREAD

**Issue by federicogatti** [moment/luxon#822]
Before the hour change at  midnight (`hour=0`) offset was GMT is +01:00
```
DateTime.fromObject({
    year: 2020,
    month: 10,
    day: 25,
    hour: 0,
    minute: 0,
    second: 0,
    millisecond: 0,
    zone: 'Europe/London'
}).toUTC().toISO()

2020-10-24T23:00:00.000Z 
```
At `hour=1` GMT is already change to offset +00:00

```
DateTime.fromObject({
    year: 2020,
    month: 10,
    day: 25,
    hour: 1,
    minute: 0,
    second: 0,
    millisecond: 0,
    zone: 'Europe/London'
}).toUTC().toISO()

2020-10-25T01:00:00.000Z
```
There is a jump from `2020-10-24T23:00:00.000Z` to `2020-10-25T01:00:00.000Z` (or in the same way using offset instead UTC `2020-10-25T0:00:00.000+01:00` to `2020-10-25T01:00:00.000+00:00`), there is any way to obtain `2020-10-2T00:00:00.000Z` (`2020-10-25T01:00:00.000+01:00`) using `fromObject` constructor method?

**Comment by icambron** [comment]
Not using that zone, no. See [ambiguous times](https://moment.github.io/luxon/docs/manual/zones.html#ambiguous-times)

**Comment by GillesDebunne** [comment]
The DST happened at 2AM local time in London.

At 2AM that night, the +1h offset changed to 0, meaning it was 1AM [again](https://www.timeanddate.com/time/change/uk/london).

Your second example is hence ambiguous, and in that case the "second" 1AM is picked, i.e after the offset change, when you expected the "first 1AM" that night to be picked.

You can define the timestamp you want using for instance
```
DateTime.fromObject({
    year: 2020,
    month: 10,
    day: 25,
    hour: 0,
    minute: 0,
    second: 0,
    millisecond: 0,
    zone: 'Europe/London'
}).plus({hour:1})
```
but not strictly using `fromObject`

**Comment by federicogatti** [comment]
Hi @icambron, Hi @GillesDebunne  thenk you for your answer.

So considering that that is an ambiguous date and Luxon doesn't handle these cases deterministically, I have to "manually" handle this case, right? There is a suggested way to handle these special cases? Consider that my input is not a date in the ISO or UTC format and therefore it is an ambiguous from the beginning

**Comment by icambron** [comment]
I'd like to add an "offset bias" to fromObject's options object in 2.0. That would let callers who know what time they mean pass in the offset they want to use. It's easy to implement in Luxon's architecture compared to alternative ways of specifying which "side" to take, while still being relatively easy to use.

That wouldn't help you, though, since you don't know which side you want to take either. It's pretty tricky, essentially for the same reason it's tricky for Luxon. You need a policy on how you'll interpret ambiguous times. I recommend you do what Luxon does: it's undefined, and you get what you get. Not only is that simple, it matches Luxon. It also only comes up one hour per year.

This is also part of why you should work exclusively in UTC times if it's at all possible. I recognize that sometimes that's just not an option, but app developers should be willing to try hard to make it one.
