### ISSUE TITLE
Need some details of minimum/maximum dates, time resolution, plus INF & more

### ISSUE THREAD

**Issue by dpatte** [moment/luxon#832]
1) I am hoping to use this for astronomical calculations, so I would like to know the minimum DateTime you support, the maximum Date/Time you support, and the resolution of time units you support (milliseconds through the full range of dates?).

2) I am also interested in knowing whether your support -INF (far past) and +INF (far future), and if not, whether they could be be easily supported. In astronomical calculations, I would like to be able to use -INF and +INF as results of long term, out of range, calculations, and for comparisons.
 
3) Is there any thought of supporting Julian calendar? Many astronomical events are described using Julian dates. 'Mixed'  support would also require a 'transition datetime' to Gregorian, defaulting to the original Gregorian decree date.

4) Which TZ files do you use, and can the version be directly specified by the developer?

5) What TZ rules do you use before TZs came into practice? Do you use to LMT for the zone city, or do you instead prolepticly continue using timezone rules?

Thanks

**Comment by icambron** [comment]
1. Approximately the min and max of the JS Date object (it's slightly more complicated than this due to offsets). Probably not what you need for astronomical calculations
2. No, Luxon doesn't support that. It's not immediately clear how we would (e.g. what would it display as?) and how much it would have to innervate the code (i.e. every operation needing an "if the input is INF, do this")
3. Unlikely for Julian. We do support one "non-native" calendar, which is the ISO Week calendar, just by translating back and forth with the native Gregorian one. We also support [output calendars](https://moment.github.io/luxon/docs/manual/calendars.html) (meaning, you can format dates in them, but not actually represent dates in those calendars) provided by the Intl API, but these don't typically support Julian calendars (e.g. just checked that Chrome/Node does not)
4. We don't use any TZ files; the zone data is implicit in the Intl API. These typically get their zone data out of the ICU.
5. This depends on the Intl implementation, but for example webkit's uses the time zone rules for the relevant slice of time. The historic data seems to vary a bit from browser to browser, especially for ancient times.
