### ISSUE TITLE
IANAZone.isValidSpecifier returns false on valid timezone

### ISSUE THREAD

**Issue by klefevre** [moment/luxon#833]
**Describe the bug**

We found that the method `IANAZone.isValidSpecifier` has an issue. It returns `false` when trying to pass the valid `'Etc/GMT-1'` timezone as argument.

**To Reproduce**

```javascript
IANAZone.isValidSpecifier('Etc/GMT-1') // -> returns false whereas it should returns true
```

**Desktop (please complete the following information):**

- Luxon version 1.25.0

**Additional context**

We found that the `ianaRegex`  works but the `matchingRegex` doesn't

```javascript
export const ianaRegex = /[A-Za-z_+-]{1,256}(:?\/[A-Za-z_+-]{1,256}(\/[A-Za-z_+-]{1,256})?)?/;
const matchingRegex = RegExp(`^${ianaRegex.source}$`);
```

```javascript
ianaRegex.test('Etc/GMT-1') // -> true
matchingRegex.test('Etc/GMT-1') // -> false
```

**Comment by icambron** [comment]
See also #834. `Etc/GMT-1` is not supported because Chrome/Node simply doesn't support that specifier. I'd love for it to, but Chrome needs to fix it first, or we should continue considering it an invalid specifier.

There are probably some context where we incorrectly *do* consider it valid, simply because we match on the regex without word endings or similar. Those are bugs (for now).

**Comment by icambron** [comment]
Going to close this one. To follow the why-don't-we-support-that-zone? issue, let's use #834
