### ISSUE TITLE
Support valid ISO 8601 date with year omitted using fromISO

### ISSUE THREAD

**Issue by johnmalatras** [moment/luxon#843]
**Is your feature request related to a problem? Please describe.**
`DateTime.fromISO` doesn't accept a valid ISO 8601 date without year (i.e. "--12-03"). The ISO Standard states that components can be excluded using a hyphen. Pulled from [here](https://stackoverflow.com/questions/25161485/is-the-mm-dd-format-for-month-day-part-of-iso-8601):

> in paragraph 4.4, ISO 8601:1988 says:
> 

> > Note - The hyphen is also used to indicate omitted components

As the link mentions, java has its own `MonthDay` [class](https://docs.oracle.com/javase/8/docs/api/java/time/MonthDay.html) to support this. 

**Describe the solution you'd like**
It would be great if `fromISO` could have built in support for `--MM-dd`.

**Describe alternatives you've considered**
I'm currently using `DateTime.fromFormat("--12-03", "--MM-dd")`

**Comment by icambron** [comment]
> The ISO Standard states that components can be excluded using a hyphen

Sort of. Older versions of it do. The standards released in 2004 or after do not permit it. However, that doesn't in itself necessarily mean Luxon can't support it.

> As the link mentions, java has its own MonthDay class to support this.

Luxon doesn't have the concept of a MonthDay. That Java class represents the day independent of the year, as in "my son's birthday is on August 6". You can then convert into a `LocalDate` by specifying the year, like `myMonthDay.atYear(2020)`. Luxon has DateTimes, so the only available behavior here is to use the _current_ year when constructing the object. While that would be relatively easy to implement, it violates the spirit of the format; the whole point was to exclude the year so that the year is implicitly _any year_. Since defaulting to this year a little dishonest, or at least confusing, we haven't implemented it. (Luxon has does take a similar shortcut with ISO formats of just the year, or just the year and month, where it uses the first day of that year or month. In principle, that's the same issue; in practice, it's far less confusing.)

Can you tell me more about your use case for it?

**Comment by johnmalatras** [comment]
Thanks for that information. The reasoning there makes sense, it would indeed be confusing to potentially lose track of a `DateTime` and later forget that the year is moot. I suppose the same could be said when parsing from `--MM-dd` although that's more directly attributable to user error versus Luxon. 

Our use case is actually the example you gave: birthdays. We don't ask for the year (and don't plan to) so `--MM-dd` seemed to be the most standardized way to store that information. The first party support in Java is also nice on the Android side of things. Ultimately, in our case, I think there'd be a little less room for error across our Luxon using services if `fromISO` was supported.

**Comment by icambron** [comment]
I'd like to suggest an alternative: make MonthDay and hide the secret year. This is exactly the sort of thing I'd love to see swirling around Luxon: small libraries that implement stuff like this. Here's a quick stab I threw together:

```js
import luxon from "luxon";
const { DateTime } = luxon;

export default class MonthDay {

  constructor(month, day, options = {}) {
    this.month = month;
    this.day = day;
    this.locale = options.locale || 'en-US';

    this._secretDT = DateTime.fromObject({month, day, locale: this.locale});
  }

  toLocaleString(fmt = MED) {
    // todo - could strip out year explicitly
    return this._secretDT.toLocaleString(fmt);
  }

  setLocale(loc) {
    return new MonthDay(this.month, this.day, { locale: loc});
  }

  static fromIso(s, opts = {}) {
    const regex = /--(\d\d)-(\d\d)/;
    const [, month, day] = regex.exec(s);
    return new MonthDay(month, day, opts);
  }
  
  // could have lots of other methods here...
}

export const SHORT = {
  month: "numeric",
  day: "numeric"
};

export const MED = {
  month: "short",
  day: "numeric"
};

export const LONG = {
  month: "long",
  day: "numeric"
};

// DEMO

let md = new MonthDay(8, 6);
console.log(md.toLocaleString()); // => Aug 6
console.log(md.setLocale("ru").toLocaleString()); // => 6 авг.
console.log(md.toLocaleString(SHORT)); // => 8/6
console.log(md.toLocaleString(LONG)); // => August 6

md = MonthDay.fromIso("--05-15")
console.log(md.toLocaleString()); // => May 15


console.log(
  MonthDay
    .fromIso("--11-16", { locale: "es"})
    .toLocaleString(LONG)); //=> 16 de noviembre
```

**Comment by johnmalatras** [comment]
Sorry for the late reply here. That's a great idea! Will look into implementing this properly when I have time
