### ISSUE TITLE
WeekNumber returns 53 on the 2nd day of the year 2021

### ISSUE THREAD

**Issue by Wardormeur** [moment/luxon#845]
**Describe the bug**
Using 
```
let d = DateTime.local();
console.log(d.weekNumber);
```
We get '53', which seems wrong considering we're on the first week of the year. 

**Actual vs Expected behavior**
It should return 1

**Desktop (please complete the following information):**

- OS: Fedora
- Browser: Node v14
- Luxon version: 1.25.0

**Additional context**
```
DateTime {
  ts: 1609611734201,
  _zone: LocalZone {},
  loc: Locale {
    locale: 'en-IE',
    numberingSystem: null,
    outputCalendar: null,
    intl: 'en-IE',
    weekdaysCache: { format: {}, standalone: {} },
    monthsCache: { format: {}, standalone: {} },
    meridiemCache: null,
    eraCache: {},
    specifiedLocale: null,
    fastNumbersCached: null
  },
  invalid: null,
  weekData: {
    weekYear: 2020,
    weekNumber: 53,
    weekday: 6,
    hour: 19,
    minute: 22,
    second: 14,
    millisecond: 201
  },
  c: {
    year: 2021,
    month: 1,
    day: 2,
    hour: 19,
    minute: 22,
    second: 14,
    millisecond: 201
  },
  o: 60,
  isLuxonDateTime: true
}
```

**Comment by icambron** [comment]
It's the first week in the Gregorian calendar year, but it's the last week of 2020 in the [ISO week calendar](https://en.wikipedia.org/wiki/ISO_week_date).

**Comment by Wardormeur** [comment]
Thanks for the explanation ! 
It seems `toObject` does not return the Gregorian week as per the doc (https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toObject) 
```
DateTime.local().toObject() //=> { year: 2017, month: 4, day: 22, hour: 20, minute: 49, second: 42, millisecond: 268 }

```

**Comment by icambron** [comment]
The problem is that Gregorian weeks aren't really well-defined. Like when does the first week of the year start? When does the last week end? Moment struggled with this and created locale-specific settings for it, which isn't satisfactory. It's hard because weeks and years don't line up, which is why the ISO week calendar exists.

Worse, Luxon doesn't have a locale-aware concept of when a week starts. In the US, it starts on Sunday. In Europe, Monday. Any definition of a Gregorian week number would likely be dependent on the week's starting day, which Luxon doesn't know. That's why Luxon just follows the ISO spec.

I have no problem supporting `gregorianWeekNumber` in principle. In practice it needs an unambiguous, universally agreeable definition to be included. I'm definitely willing to consider proposals.

**Comment by Wardormeur** [comment]
Understood!
Ultimately I don't need the precision and can work with the ISO one, so I'll leave it to somebody more in need of a more local solution.
