### ISSUE TITLE
Better handling of invalid/ambiguous dates (summertime boundaries)

### ISSUE THREAD

**Issue by synotna** [moment/luxon#914]
Hello,

I am researching how we could detect / prevent the entry of invalid or ambiguous dates e.g. summertime boundaries

Do you think trying to create an invalid date should error instead of silently taking the next valid timestamp?

luxon.DateTime.fromObject({year: 2021, month: 3, day: 28, hour: 2, minute: 0, zone: 'Europe/Berlin' }).toISO()

"2021-03-28T03:00:00.000+02:00"

Expectation: Error because there was no 02:00 Europe/Berlin

Do you think trying to create an ambiguous date should error instead of silently taking the earliest valid timestamp?

luxon.DateTime.fromObject({year: 2021, month: 10, day: 31, hour: 2, minute: 0, zone: 'Europe/Berlin' }).toISO()

"2021-10-31T02:00:00.000+02:00"

Expectation: ambiguous, did you mean 02:00+02 (CEST) or 02:00+01? (CET)

If you agree we would consider trying to contribute :)

**Comment by icambron** [comment]
I could imagine doing this for invalid times. Certainly, Luxon knows that the time is invalid and could act accordingly. I'd certainly consider it.

We can't do anything like that for ambiguous times, for two reasons. First, it is, in fact, a valid time! It would be weird if there were local times you simply couldn't express. Second, Luxon actually doesn't know that it's an ambiguous time, because it doesn't have first-class access to the time zone rules. All it can do is check if the zone agrees with the local time about what the offset should be, and for ambiguous times, that's already true.

Or as I put it in the docs:

> If you're curious, this lack of definition is because Luxon doesn't actually know that any particular DateTime is an ambiguous time. It doesn't know the time zones rules at all. It just knows the local time does not contradict the offset and leaves it at that. To find out the time is ambiguous and define exact rules for how to resolve it, Luxon would have to test nearby times to see if it can find duplicate local time, and it would have to do that on every creation of a DateTime, regardless of whether it was anywhere near a real DST shift. Because that's onerous, Luxon doesn't bother.

Back to invalid times: the issue then becomes, does it make sense to reject those if we are accepting ambiguous times?

**Comment by synotna** [comment]
Hello,

First of all my sincerest apologies for overlooking this being documented in the docs!

For invalid times: would certainly be nice to have that, either a "strict" option that errors, or otherwise is exposed in the returned data

For ambiguous: I agree it is not strictly speaking invalid but still ambiguous, luxon does not know if it returning correct data

I think one way to detect this case could be to do the reverse two times, generate the object from with and without DST - if both outputs match the input then the input must have been ambiguous

Or from another perspective: check if the time with and without DST is "valid" for that time, where "valid" mean should / could the time bein DST at that moment. E.g. CEST in December is not valid. If both are valid, it is ambiguous.

**Comment by synotna** [comment]
I realise it is not possible to do that right now because Luxon does not make it possible to specify whether a time is DST when creating/modifying the object - you can only get whether it is in DST

Is being able to specify DST when creating something you may consider in future?

**Comment by icambron** [comment]
It doesn't work that way. It might be helpful to look at the implementation of `isInDST()`; it takes a day in Jan and a day in May and sees if they're different: 

https://github.com/moment/luxon/blob/e0c8f874304cd4ecc3944bdcff3d8f8c27102a18/src/datetime.js#L1194

I also have at least one bug report that it doesn't work as expected in some zones, presumably because those dates are poorly chosen.

I bring this up because it might help clarify what I suspect is the fundamental confusion here: Luxon has no idea when the DSTs are. A zone is basically a function that maps a timestamp to a local time. Luxon can use that compute the offset at any given time, but it can't inspect the zone's implementation to see what the zone's decision logic is. It's just a black box. So you end up "probing" dates to learn even basic things like whether a zone has a DST this year.

Given that, the way Luxon creates a specific local time in a specific zone is to try an offset (using the _current_ offset for the zone) to compute a universal timestamp. Then it "calls" the zone function to see if that spits out the local time we want. If not, we know how far off it is and can find out the correct local offset. If we fail at that, where in a hole time. But we never find out at that ambiguous times are ambiguous because the pass the first test (the current local offset corresponds to one side of the ambiguity and is therefore valid). You can see the relevant code here:

https://github.com/moment/luxon/blob/e0c8f874304cd4ecc3944bdcff3d8f8c27102a18/src/datetime.js#L76

So to know that a time is ambiguous, we'd have to "try" the offset on either side of the DST. That means for every datetime we create, we'd have to probe that year's DST dates, and then plug both those offsets into the calculation. That's both a lot of complexity and a real performance hit, effectively doubling the cost of creating a datetime for something that happens for one hour every year (doubles because the expensive part is using Intl to compute a local time for a zone). Not doing this was an explicit decision.

> Is being able to specify DST when creating something you may consider in future?

The best we could do here is allow the caller to specify their own default offset, which would tell Luxon to "try" that offset first instead of defaulting to `now()`'s offset. That would effectively determine which side of the DST ambiguous local times would be interpreted as. Something like `DateTime.local(2021, 5, 22, { defaultOffset: -420})`, but I haven't thought too hard about it. We'd also need to figure out what happens if you specify something bogus there.

**Comment by synotna** [comment]
Thank you for the great explanation. I suppose for luxon to have the missing data it needs to know / be able to look up, it would require browsers to make more tzdata available, or to ship like moment did? to be able to have a function like getTimeZoneOffsets(ts, tz)-> [ (CET,+1), (CEST, +2) ]

I understand the trade off, it is very frustrating though having to trade correctness for performance, for a regular, normal case - though infrequent in the grand scheme of things :)

**Comment by icambron** [comment]
Right, if we had explicit access to the zone's rules, we could use them to figure out when a local time is ambiguous. But that's unlikely to happen without, as you say, shipping our own TZ rules. So I think we need to live with this limitation, especially given how poor Intl's performance is on most browsers.
