### ISSUE TITLE
How to work with Intervals, now, next day, etc.

### ISSUE THREAD

**Issue by dreambit** [moment/luxon#963]
If i have intervals like this, one comes after another, there are no gaps
1) 2021-06-27T00:00:00.000Z-2021-06-27T23:59:59.999Z
2) 2021-06-28T00:00:00.000Z-2021-06-28T23:59:59.999Z
3) 2021-06-29T00:00:00.000Z-2021-06-29T23:59:59.999Z

all methods like abutsEnd, abutsStart checks that a.end === b.start, but how to work when you have intervals like above?
In my opinion, they are adjacent, cause one starts immediately after the previous end.

**Comment by icambron** [comment]
Intervals in Luxon are half-open, meaning they include the start time but do NOT include the end time. So, e.g. `2021-06-27T00:00:00.000Z-2021-06-27T23:59:59.999Z` has the last millisecond at 23:59:59.998, and .999 is not included. So typically, you'd just define the "all day" interval as `2021-06-27T00:00:00.000Z-2021-06-28T00:00:00.000Z`, so that the last millisecond is .999. That's why `abutsStart` is defined how it is, so that the first interval's end time (not included in the interval) matches the start time of the second one (_is_ included in that interval), meaning the actual included times are right up against each other.
