### ISSUE TITLE
Settings.defaultZoneName no longer gives default zone name in Version 2 and above

### ISSUE THREAD

**Issue by bobskigit** [moment/luxon#985]
In version 1.28 let tz = Settings.defaultZoneName would give you the current zone , 'Europe/London' in my case.

In 2 and greater let tz = Settings.defaultZoneName gives **undefined**.

**Comment by dasa** [comment]
I think this was changed to `Settings.defaultZone.name`: https://moment.github.io/luxon/#/upgrading?id=default-zone

**Comment by icambron** [comment]
Yeah, I should add that to the upgrade guide

**Comment by pedrocalderon** [comment]
I have a similar problem on Luxon 2.0.1 migration.

As @bobskigit has said, in version 1.x I was using `Settings.defaultZoneName = 'America/Sao_Paulo'` to set the timezone in my project. But when I follow the upgrading guide and use `Settings.defaultZone = "America/Sao_Paulo"` I get an error `Cannot assign to 'defaultZone' because it is a read-only property`.

Using the `Settings.defaultZone.name` has not worked either for me.

I'm using Typescript.

**Comment by dasa** [comment]
> I'm using Typescript.

I think you'll need this PR to merge: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54595

**Comment by pedrocalderon** [comment]
Thank you @dasa
