### ISSUE TITLE
DateTime.local().toISO() !== DateTime.utc().toISO() even when zone is UTC

### ISSUE THREAD

**Issue by richardscarrott** [moment/luxon#992]
**Describe the bug**
In our node.js program the timezone is set to UTC:

```js
new Date(); // 2021-07-20T10:56:02.802Z
```

We're therefore writing our code using `DateTime.local()` however it generates a different ISO string than `DateTime.utc()`:

```js
DateTime.local().toISO(); // '2021-07-20T10:49:32.602+00:00'
DateTime.utc().toISO(); // '2021-07-20T10:49:41.232Z'
```

I know they represent the same moment in time but the latter (with the abbreviated offset `Z`) is what I prefer for our current use case (file names).

Is this expected behaviour?

**Actual vs Expected behavior**
```js
// Assume same ms
const local = DateTime.local();
const utc = DateTime.utc();
local.zoneName === utc.zoneName; // true
// EXPECTED:
local.toISO() === utc.toISO(); // true
// ACTUAL:
local.toISO() === utc.toISO(); // false
```

**Desktop (please complete the following information):**

- Container: [node:12.14.0](https://hub.docker.com/_/node)
- OS:  Linux
- Luxon version: 2.0.1
- Your timezone: UTC

**Comment by icambron** [comment]
This is tough edge case for Luxon. The local zone is UTC but to Luxon it's still of type `SystemZone`, not `FixedOffsetZone`, so it fails the equality check simply on the type. Meaning, they're the same zone conceptually but Luxon doesn't really know that.

We similarly return `false` there if you're comparing a datetime with, say, a system zone that happens to be America/New_York with one where we explicitly set the zone to that IANA string. The core issue there is that Luxon doesn't have first-class access to the system zone; it can only format its name and query for the offset of specific times.

We could potentially special case the equality checkers on those two types to return true under the specific UTC circumstance, since we can be reasonably sure the system zone that calls itself "UTC" will work the same way as the explicit UTC zone. However, that requires actually asking Intl to format the zone's name and checking that it returns "GMT" or whatever, and that's a pretty strange thing for an equality check to do. Needs some thought.

A workaround is simply to set the default zone to UTC in Luxon. Won't make the dates act any differently, but will make `local()` return datetime that Luxon explicitly knows are in UTC

**Comment by icambron** [comment]
After some thought, I've decided not to fix this. It's annoying and I agree it's a bug, but the fix is too complicated.
